* Demografi

Demografi er studiet af humane befolkningers størrelse, sammensætning
og udvikling over tid og sted. Demografi beskæftiger sig særligt med
tre kernebegivenheder: Fødsel, migration og død. Kendskab til
befolkningens sammensætning og struktur er vigtig for forståelsen af
befolkningens udvikling. Derfor er demografi også mere end metoder til
at at holde regnskab over befolkninger, og beskæftiger sig med
aldersfordeling, kønsfordeling, etnicitet, familiedannelse,
fertilitet, sprog, religion, uddannelse, erhverv og andre relevante
faktorer som påvirker befolkningens udvikling.

Demografer anvender forskellige metoder, såsom dataindsamling og
statistisk analyse, til at undersøge og beskrive befolkningstendenser- og
mønstre. Demografi spiller en vigtig rolle i samfundsplanlægning
og i politikudvikling, da det kan give vigtig information om en
befolknings sundhedstilstand, uddannelsesbehov, arbejdsstyrke og
økonomisk udvikling. Nogle af de områder, hvor demografi er relevant,
inkluderer folkesundhed, økonomi,  byplanlægning,
arbejdsmarked og socialpolitik. Metoderne, som vi bruger til demografi,
er tæt beslægtet med metoder fra epidemiologi og statistik.

* Befolkning
:PROPERTIES:
:CUSTOM_ID: k1_befolkning
:END:
I demografi refererer udtrykket /befolkning/ til den gruppe af
mennesker, der bor inden for et geografisk område eller en juridisk
enhed ved et bestemt tidspunkt. Dermed kan man tale om Danmarks
befolkning den 26. juni 1992, og om Nordeuropas befolkning den 1.
april 2000. En befolkning kan opdeles og analyseres efter kriterier
som for eksempel bopæl, køn, alder, civilstand, etnisk gruppe,
uddannelse, erhverv, fag og stilling. Tilsammen er alle disse grupper
udtryk for befolkningsstrukturen. En /befolkningsgruppe/ er en del af
en befolkning som opfylder yderlige kriterier. For eksempel danner
alle kvinder, som modtager SU, er yngre end 25 år, og bor i Region
Sjælland 1. januar 2023, en befolkninggruppe.

Befolkning i demografi kan beskrives og analyseres med statistikker
som befolkningsstørrelse, befolkningstæthed, aldersfordeling,
kønsfordeling, etnicitet og mange andre faktorer, der kan give indsigt
i befolkningens dynamik og sammensætning. Disse statistikker bruges
til at forudsige og planlægge behovet for offentlige tjenester på
eksempeltvis sundheds-, uddannelses- og beskæftigelsesområdet.

** Lukkede og åbne befolkninger
:PROPERTIES:
:CUSTOM_ID: k1-lukket-befolkning
:END:

Hvis befolkningen ikke er genstand for ind- og udvandring, kaldes den
en lukket befolkning. Hvis befolkningen ikke er lukket, er det en åben
befolkning. De allerfleste befolkninger er åbne. Lukkede befolkninger
er typisk af hypotetisk/tænkt natur og et /demografisk værktøj/, der
bruges til at forklare komplekse principper og regnestykker i en
simplificeret situation.

** Kohorte

En kohorte er en gruppe personer som oplever en bestemt (demografisk)
begivenhed i en bestemt periode og følges derefter, for eksempel alle
kvinder født i Danmark i året 1900 (fødselskohorte) eller alle mænd,
som påbegyndte FSV studiet mellem 2017 og 2020.

** Befolkningens størrelse

Lad os tage udgangspunkt i den danske befolkning og starte med at se
på dens størrelse. Folketal $N(t)$ angiver befolkningens størrelse til
tid $t$, hvor $t$ er en dato i kalenderen. Ifølge statistikbanken [fn:1] var
der 5.806.081 personer i Danmarks befolkning den 1. januar 2019:

\begin{align*}
\text{Befolkning} &= \text{Hele Danmark} \\
t_1&= \texttt{2019-01-01} \\
N(t_1) &= 5.806.081
\end{align*}

På et senere tidspunkt vil befolkningens størrelse have
ændret sig som følge af fødsler, dødsfald og ind- og
udvandring. Den 1. januar 2023 var der 5.932.654 personer i Danmarks
befolkning. Dermed er den danske befolkning vokset med 126.573
personer i de 1461 dage mellem den 1.  januar 2019 og
den 1. januar 2023. Nedenfor er givet nogle linjer R-koder, som kan
bruges til at beregne antallet af dage mellem to datoer og ændringen i
folketallet i perioden.

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={t,as,c}
#+BEGIN_SRC R  :results output verbatim :exports both  :session *R* :cache yes  
# R-code
t_1= as.Date("2019-01-01")
t_2= as.Date("2023-01-01")
N_1 = 5806081
N_2 = 5932654
data.frame("dato"=c(t_1,t_2),"Folketal"=c(N_1,N_2),
           "Antal dage"=c(NA,t_2-t_1),"Vækst"=c(NA,N_2-N_1))
#+END_SRC

#+RESULTS[(2023-12-27 12:46:31) 3b577630b92663ee94418cfb09bf6c41dd3436f7]:
:         dato Folketal Antal.dage  Vækst
: 1 2019-01-01  5806081         NA     NA
: 2 2023-01-01  5932654       1461 126573

Folketallet ændrer sig hver dag, men det er svært at registrere og
tælle nøjagtigt, hvor mange personer der er i befolkning for hver
enkelt dag. Heldigvis betyder små unøjagtigheder i tallene typisk ikke
særlig meget for demografiske konklusioner. Statistikbanken angiver
folketal i starten af hvert kvartal siden 2008 (register =FOLK1A=),
den 1.  januar per år siden 1971 (register =BEFOLK1= ), den 1. januar
per år siden 1901 (register =HISB3= ). Desuden er der summariske tal
fra folketællinger helt tilbage fra 1769 (register =FT=).
[fn:1] https://statistikbanken.dk/

* Instruks til brugen af R koder

For at hente data fra statistikbanken bruger vi en R pakke, som hedder
=danstat=. Desuden bruger vi en række andre R pakker og også R
funktioner, som gør det nemt arbejde med data fra statistikbanken og
implementere specifikke demografiske metoder. For at afprøve R koder,
som bliver vist her, skal I først hente filen

\small
https://github.com/tagteam/demogRafi/blob/main/R_funk/demofunk.R
\normalsize

og gemme den i projekt folderen =demografi= i undermappen =R-scripts=.
En vigtig funktion hedder =hent_data=. Den henter data fra
statistikbankens register. For at se hvilke register der er og hvad de
hedder, skal man besøge internetsiden https://statistikbanken.dk/ hvor
man finder dem under EMNE Borgere.

#+ATTR_LATEX: :options otherkeywords={hent_data}, deletekeywords={}
#+BEGIN_SRC R  :results output   :exports both  :session *R* :cache yes
# load kursets funktioner direkte fra Internet
source("https://raw.githubusercontent.com/tagteam/demogRafi/main/R-scripts/demofunk.R")
# load fra filen som er gemt i undermappen R-scripts
source("R-scripts/demofunk.R")
# brug funktionen til at hente folketal fra 2023 1. kvartal 
hent_data(register = "folk1a",tid = "2023K1")
#+END_SRC

#+RESULTS[(2024-01-30 09:27:59) 01fc3c5c6ba42288feaed5bb3a3f0193fbfdc7f2]:
: # A tibble: 1 × 2
:   TID    INDHOLD
:   <chr>    <dbl>
: 1 2023Q1 5932654

I register =FOLK1a= kan man hente data per kvartal. I register =BEFOLK1=
kun fra første kvartal:
#+ATTR_LATEX: :options otherkeywords={hent_data}, deletekeywords={}
#+BEGIN_SRC R  :results output   :exports both  :session *R* :cache yes  
hent_data(register = "befolk1",tid = 2023)
#+END_SRC

#+RESULTS[(2024-01-30 09:28:03) f4e39d8ba3b9dc4d0ddbd5b259bab1e25dc5ace2]:
: # A tibble: 1 × 2
:     TID INDHOLD
:   <dbl>   <dbl>
: 1  2023 5932654

I register =HISB3= er folketal rundet af og angivet som antal 1000 personer:
#+ATTR_LATEX: :options otherkeywords={hent_data}, deletekeywords={}
#+BEGIN_SRC R  :results output :exports both  :session *R* :cache yes  
hent_data(register = "HISB3",tid = 2023,bevægelse = "M+K")
#+END_SRC

#+RESULTS[(2024-01-30 09:23:19) 79ebfaa17103ea95643fc14bcb715f7e0ac0e09e]:
: # A tibble: 1 × 3
:     TID BEVÆGELSE         INDHOLD
:   <dbl> <chr>               <dbl>
: 1  2023 Population Janua…    5933

Folketal fra register (=FT=) bliver vist i Figur [[fig:1]]. Her er R-koder
som producerer denne figur:
#+ATTR_LATEX: :options otherkeywords={ggplot,hent_data}, deletekeywords={list,dt,data,scale}
#+BEGIN_SRC R :results file graphics :file ./kapitel1/figure1.pdf :exports code :session *R* :cache yes
# R-koder der producerer figur 1
dt=hent_data(register = "FT",tid = "all")
ggplot(dt,aes(TID,INDHOLD))+geom_line()+geom_point()+
  theme_wsj()+ scale_colour_wsj("colors6")
#+END_SRC

#+RESULTS[(2023-11-06 11:34:16) e930586f8196697970f2e417b783cab3dc1c97f7]:
[[file:./kapitel1/figure1.pdf]]

#+NAME: fig:1
#+ATTR_LATEX: :width 0.7\textwidth
#+CAPTION: Figuren viser udviklingen af det danske folketal siden 1769 fra folketællinger, statistikbankens register FT.
[[file:./figure1.pdf]]


* Befolkningsstatistik i Denmark

Befolkningsstatistikken i Danmark har en lang historie. Siden den
første folketælling i 1769 er der foretaget regelmæssig og
systematisk optælling af befolkningen. Efter folkestyrets indførelse i
1849 blev opgaven med at gennemføre folketællinger varetaget af Det
Statistiske Bureau, som blev etableret i 1850. Det Statistiske Bureau
blev senere til Danmarks Statistik, der siden har udgivet de
officielle demografiske statistikker for Danmark som den centrale
myndighed for dansk statistik. Danmarks Statistik udarbejder alene
officiel statistik for Danmark, mens Statistik for de andre lande i
rigsfællesskabet varetages af Naatsorsueqqissaartarfik (Grønlands
Statistik) og Hagstova Føyora (Færøernes Statistik).

** Administrative registre i demografisk statistik

På det demografiske område har Danmarks Statistik været en
foregangsinstitution på et særligt område: Registerbaseret statistik. I
1968 blev Det Centrale Personregister oprettet, og CPR-nummeret
indføres som identifikationsnummer for personer for at lette den
offentlige administration. Sammen med en række andre administrative
kilder som Det Centrale Erhvervsregister (1975) og Bygnings- og
Boligregistret (1977) gjorde CPR det muligt at lave mange typer af
demografisk statistik på baggrund af administrative registre. Som en
konsekvens af de nye muligheder lavede Danmarks Statistisk i 1981 en
af de første folketællinger, der alene var baseret på administrative
registre. I dag er CPR registeret rygraden i den demografiske
statistik.

CPR er et administrativt register. Det betyder, at registeret er
lavet for at kunne bruges til at understøtte den offentlige
administration generelt gennem let identifikation, for eksempel for at
sikre adgang til offentlige ydelser (for eksempel lægebehandlinger,
biblioteksadgang) og korrekte beskatning (for eksempel kilde- og
ejedomsbeskatning).

CPR administreres af kommuner og indeholder oplysninger om de centrale
begivenheder, som er nødvendige for at belyse fænomener af særlig
demografisk interesse. Fordi CPR indeholder datoerne for fødsler,
indvandring, udvandring og død, så kan CPR bruges direkte til at
opgøre komponenterne i den demografiske ligevægtsligning, som er en
helt central størrelse i demografien. CPR indeholder også information
om ægtefælle, link mellem børn og forældre, samt information om
bopæl. De informationer kan bruges til for eksempel familiedemografi,
der beskæftiger sig med formation, ændring, sammensætning og udvikling
i familier og husholdninger.

Kvaliteten af oplysningerne i CPR og de forskellige andre
administrative registre, der anvendes til demografisk statistik er
ikke altid af perfekt kvalitet. Kvaliteten af oplysningerne afhænger i
praksis af om borgerne er motiveret til at sikre at oplysningerne er
korrekte eller at oplysningerne er kvalitetssikret af de myndigheder,
der skal bruge oplysningerne til administrative formål. En anden
svaghed ved at anvende administrative registerdata fra for eksempel
CPR er, at der ofte vil være oplysninger, som ikke er
tilgængelige. Det kan for eksempel være oplysninger om kønsidentitet,
familieformer eller religiøst tilhørsforhold, som ikke er noget, der
findes data på i CPR. Styrken ved registerbaseret demografiske
statistisk er, at den opgøres meget ofte og uden ret store
omkostninger, sammenlignet med for eksempel demografisk statistik
baseret på spørgeskema eller besøgsinterview.

** Definitioner af befolkning

For at kunne opgøre befolkningstallet i den officielle statistik er
det nødvendigt at have en præcis definition, som kan implementeres i
data. Ydermere, er det i praktisk også sådan, at definitionerne er
samordnet mellem lande, sådan at alle personer tælles en gang og kun
en gang. I de nordiske lande foregår samordningen ved, at de
administrative registre er koordinerede, mens man i EU/EØS generelt
sikre overensstemmelse ved at dele statistikoplysninger mellem
landene. Særligt i små og åbne lande som Danmark er det ikke helt
trivielt at sikre, at befolkningen tælles korrekt på baggrund af
registerdata. Det gælder generelt, at migrationskomponenten er langt
sværere både at registrere og at fremskrive end fødsler og dødsfald.


* Middelfolketal

Vi indfører nu begrebet middelfolketal, som bruges til at estimere det
gennemsnitlige folketal i en given tidsperiode.  Middelfolketallet er
en vigtig demografisk indikator, der indgår for eksempel i fertilitetsrater
og dødelighedstavler.

#+begin_export latex
\mybox{Middelfolketallet er defineret som det gennemsnitlige folketal i en
given tidsperiode.  Vi betegner middelfolketallet med $\tilde N$.}
#+end_export


For at beregne middelfolketallet helt korrekt, ville man for alle
personer være nødt til at tælle, hvor mange dage de har levet i befolkningen i
perioden. Så kunne man beregne middelfolketallet
eksakt som den samlede gennemlevede tid divideret med periodens
længde. Denne beregning giver et gennemsnitligt antal mennesker, der
bor i området over en given tidsperiode.

Rent praktisk kender man desværre ikke de præcise tal, altså hvor
mange dage alle personer fra en befolkning har levet i en given
tidsperiode. Fødselsdage og dødsdage har man typisk registreret
korrekt, men ind- og udvandringsdatoer har man typisk mindre nøjagtig
registreret. Flere metoder kan dog bruges til at beregne
middelfolketallet approksimativt baseret på enkelte folketal i en
given tidsperiode.

**  Metode 1

Her skal man kun kende et enkelt folketal, nemlig folketallet cirka i
midten af perioden. Hvis perioden starter i tidspunkt $t_1$ og slutter
i tidspunkt $t_2$, så er tidspunktet i midten af perioden given som $(t_1+t_2)/2$, og
folketallet i midten af perioden er given ved formlen:

#+begin_export latex
\begin{equation*}
\tilde N[t_1,t_2]=N((t_1+t_2)/2). 
\end{equation*}
#+end_export

Dette tal bruges som et estimat for middelfolketallet. Metode er
simpel og tilstrækkelig for mange formål, især når folketallet ikke
ændrer sig særlig meget i den givne tidsperiode. For eksempel bruger
Danmark Statistik folketal fra den 1. juli som årets middelfolketal i
deres årlige rapporter om befolkningens udvikling [fn:2].

[fn:2] https://www.dst.dk/da/Statistik/nyheder-analyser-publ/Publikationer/

**  Metode 2

For at bruge denne metode skal man kende folketallet i starten og i
slutningen af perioden. Det estimerede middelfolketal er gennemsnittet
af de to folketal:

#+begin_export latex
\begin{equation*}
\tilde N[t_1,t_2]=(N(t_1)+N(t_2))/2. 
\end{equation*}
#+end_export

**  Metode 3 

Her skal man kende folketallet i starten, i slutningen og ved mindst et
tidspunkt mere i perioden. Lad os antage, at vi kender folketal til $J$
forskelige tidspunkter $t_1 < t_2 < \dots <t_J$. Det estimerede
middelfolketal for perioden $[t_1,t_J]$ kan beregnes med følgende
formel:

#+begin_export latex
\begin{align*}
\tilde N[t_1,t_J] &= \frac 1 {(t_J-t_1)}\sum_{j=2}^J (t_j-t_{j-1}) \frac{(N(t_{j-1})+N(t_j)}{2}\\
             &= \frac{(t_2-t_1)}{(t_J-t_1)}  \frac{(N(t_{2})+N(t_1)}{2} +\cdots +\frac{(t_J-t_{J-1})}{(t_J-t_1)}  \frac{(N(t_{J})+N(t_{J-1})}{2}
\end{align*}
#+end_export

Alle tre metoder er lige gode, hvis folketallet er
relativt stabil i perioden.  Ændrer folketallet sig meget i perioden,
er metode 2 en bedre tilnærmelse til det sande ukendte
middelfolketal end metode 1, og ligeledes er metode 3
bedre end metode 2. Figur [[fig:2]] visualiserer
forskellen mellem de 3 metoder.

#+BEGIN_SRC R :results file graphics :file ./kapitel1/figure2.pdf :exports none :session *R* :cache yes
par(mfrow=c(2,2))
## Metode 1
x <- as.Date(c(paste0("2019-",c("01","04","07","10"),"-01"),"2020-01-01"))
y <- c(5806081, 5811413,5814461,5827463,5822763)
plot(x,y,type="b",main=" Metode 1",xlim=as.Date(c("2019-01-01","2019-12-31")),ylab="Folketal N(t)",xlab="Kalenderår 2019",ylim=c(5800000,5850000),lty=1,lwd=3,pch=8,axes=FALSE)
rect(xleft=x[1],xright=x[5],ybottom=5800000,ytop=y[3],col="orange",border=NA,density=70)
lines(x,y,type="b",lwd=3)
axis(1,at=x,lab=c(paste0("K",1:4),"2020-01-01"))
axis(2)
## Metode 2
x <- as.Date(c(paste0("2019-",c("01","04","07","10"),"-01"),"2020-01-01"))
y <- c(5806081, 5811413,5814461,5827463,5822763)
plot(x,y,type="b",main=" Metode 2",xlim=as.Date(c("2019-01-01","2019-12-31")),ylab="Folketal N(t)",xlab="Kalenderår 2019",ylim=c(5800000,5850000),lty=1,lwd=3,pch=8,axes=FALSE)
u <- polygon(x=c(x[1],x[length(x)],x[length(x)],x[1]),y=c(y[1],y[length(y)],0,0),col=2,density=70)
lines(x,y,type="b",lwd=3)
axis(1,at=x,lab=c(paste0("K",1:4),"2020-01-01"))
axis(2)
## Metode 3
x <- as.Date(c(paste0("2019-",c("01","04","07","10"),"-01"),"2020-01-01"))
y <- c(5806081, 5811413,5814461,5827463,5822763)
plot(x,y,type="b",main=" Metode 3",xlim=as.Date(c("2019-01-01","2019-12-31")),ylab="Folketal N(t)",xlab="Kalenderår 2019",ylim=c(5800000,5850000),lty=1,lwd=3,pch=8,axes=FALSE)
polygon(x=as.numeric(c(x, rev(x))),y=as.numeric(c(y,rep(0,length(y)))),col=3,density=70)
lines(x,y,type="b",lwd=3)
axis(1,at=x,lab=c(paste0("K",1:4),"2020-01-01"))
axis(2)
## Summary
plot(0,0,type="n",xlab="",ylab="",main="Middelfolketal 2019",axes=0L)
library(plotrix)
library(data.table)
tab <- t(data.table("Metode 1"=y[3],
                    "Metode 2"=(y[1]+y[5])/2,
                    "Metode 3"=round(sum((y[-length(y)]+y[-1])/2*diff(as.numeric(x)))/365)))
tab <- cbind(rownames(tab),tab)
colnames(tab) <- c("Metode","Værdi")
plotrix::addtable2plot(x=-.7,y=-.5,tab,cex=1.3,hlines=1,vlines=1,xpad=.5,ypad=1)
#+END_SRC

#+RESULTS[(2023-11-06 13:21:05) 77ea44b083d599c057c029220aed9c1dbe33c8e7]:
[[file:./kapitel1/figure2.pdf]]

#+NAME: fig:2
#+ATTR_LATEX: :width 0.9\textwidth
#+CAPTION: Figuren viser de 3 metoder for at beregne middelfolketal baseret på 5 folketal: 1. januar 2019, 1. april 2019, 1. juli 2019, 1. oktober 2019, 1. januar 2023.
[[file:./figure2.pdf]]


*** Eksempel

Vi beregner middelfolketal for den danske befolkning i en periode, som
starter den 1. januar 2009 og slutter den 1. januar 2023. Fra
statistikbankens =BEFOLK1= henter vi folketal i starten, midten og
slutningen af perioden:

#+ATTR_LATEX: :options otherkeywords={hent_data}, deletekeywords={list,dt,c}
#+BEGIN_SRC R  :results output  :exports both  :session *R* :cache yes
dt=hent_data("BEFOLK1",tid=c(2009,2016,2023))
dt
#+END_SRC

#+RESULTS[(2024-01-31 07:45:30) 619e6b446610e8bd71de7c064f4f9e0620c46756]:
: # A tibble: 3 × 2
:     TID INDHOLD
:   <dbl>   <dbl>
: 1  2009 5511451
: 2  2016 5707251
: 3  2023 5932654

Det er nemmest at anvende metode 1. Med metode 1 er
det estimerede middelfolketal $\tilde N[\texttt{1 januar 2016}] = 5.707.251$ personer. For at benytte metode 2
bruger vi R som lommerregner:

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output  example  :exports both  :session *R* :cache yes
# Metode 2
(5511451 + 5932654)/2
#+END_SRC

#+RESULTS[(2023-11-06 10:01:11) 78791514d677aa50d446ee4966a524a61a369c65]:
: [1] 5722052.5

Med metode 2 estimerer vi middelfolketallet i perioden mellem 1. januar 2009 og 1 januar 2023 dermed til
$5.722.053$ personer. For metode 3 er beregningen i R den følgende:

#+ATTR_LATEX: :options otherkeywords={hent_data,format_dato}, deletekeywords={rep,dt,variable}
#+BEGIN_SRC R  :results output example  :exports both  :session *R* :cache yes  
# Metode 3
(2016-2009)/(2023-2009)*(5511451+5707251)/2 + (2023-2016)/(2023-2009)*(5707251+5932654)/2
#+END_SRC

#+RESULTS[(2023-11-06 10:00:59) f21cbcd580ee62077267204df1a604fd2ff170a1]:
: [1] 5714652

Med metode 3 estimerer vi middelfolketallet i perioden 1. januar 2009
og 1 januar 2023 til $5.714.652$ personer baseret på de 3 folketal fra
perioden.  Vi ser i dette eksempel, at der er mindre end 10.000
personers forskel mellem metode 3 og metode 2. Om denne forskel er
vigtig eller ej ville afhænge af formålet med den konkrete
demografiske undersøgelse. Er den vigtigt, ville man prøve at estimere
middelfolketallet så godt som muligt. For at gøre det ville man hente
så mange folketal som muligt fra perioden, og så beregne
middelfolketallet med metode 3 på alle disse tal. Følgende R-koder
henter alle folketal mellem 1. januar 2009 og 1. januar 2023 fra
statistikbankens register FOLK1a og anvender metode 3.

#+ATTR_LATEX: :options otherkeywords={hent_data,format_dato,pull,summarise}, deletekeywords={rep,c,variable,dt,length,as,numeric}
#+BEGIN_SRC R  :results output verbatim  :exports both  :session *R* :cache yes  
# Metode 3 baseret på 57 folketal mellem 2009 og 2023
# konstruere vektor 2009K1, 2009K2, ..., 2022K4
kvartal_years <- paste0(rep(2009:2022,rep(4,14)),"K",1:4)
# tilføj 2023K1
kvartal_years <- c(kvartal_years,"2023K1")
# hent data fra FOLK1a 
dt <- hent_data(register = "FOLK1a",tid=kvartal_years)
# transform årstal + kvartal til dato
dt <- format_dato(dt,variable = "TID")
# anvend middelfolketal metode 3
summarise(dt,{
  len <- length(TID)
  len_periode_total <- as.numeric(TID[length(TID)]-TID[1])
  len_periode <- as.numeric(TID[-1]-TID[-len])
  ft_gennemsnit <-(INDHOLD[-len]+INDHOLD[-1])/2 
  sum(len_periode*ft_gennemsnit)/len_periode_total
})%>% pull()
#+END_SRC

#+RESULTS[(2023-12-27 12:49:25) acf9e2e6dec3dd8e3603e015f0d425addbdad9c4]:
: [1] 5717974

Baseret på 57 folketal i perioden mellem den 1. januar 2009 og den 1.
januar 2023 estimerer vi middelfolketal for perioden til at være 5.717.974
personer.

* Den demografiske ligevægtsligning

Den demografiske ligevægtsligning er en formel, der bruges i
demografisk analyse til at beskrive forholdet mellem antallet af
fødsler, dødsfald og migration i en periode i en befolkning. Jo flere
dødsfald og jo flere personer, der emigrerer, jo mindre er folketallet i
slutningen af perioden sammenlignet med starten af perioden. Ligeledes
er folketallet i slutningen af perioden højere jo flere personer bliver født og
indvandrer til befolkningen. Den demografiske ligevægtsligning for en
periode $[t_1,t_2]$ er:
#+begin_export latex
\begin{equation}\label{eq:ligevaekst}
N(t_2) = N(t_1) + (F[t_1,t_2] - D[t_1,t_2]) + (I[t_1,t_2] - U[t_1,t_2]). 
\end{equation}
#+end_export
hvor vi har brugt følgende notation:
- $N(t_1)$ er folketal på tidspunkt $t_1$.
- $N(t_2)$ er folketal på tidspunkt $t_2$.
- $F(t_1,t_2)$ er antallet af fødsler i perioden.
- $D(t_1,t_2)$ er antallet af dødsfald i perioden.
- $I(t_1,t_2)$ er antallet af indvandrere i perioden.
- $U(t_1,t_2)$ er antallet af udvandrere i perioden.

Formlen siger kort sagt, at den samlede befolkning på et tidspunkt
$t_2$ er lig den samlede befolkning på tidspunktet $t_1$ plus en
stigning i befolkningen på grund af fødsler og indvandring og en
reduktion i befolkningen på grund af dødsfald og udvandring. Vi kalder
forskellen mellem fødsler og dødsfald $(F[t_1,t_2] - D[t_1,t_2])$ for
/naturlig vækst/ og forskellen mellem ind- og udvandring $(I[t_1,t_2] -
U[t_1,t_2])$ for /nettovandring/. Det giver følgende version af den
demografiske ligevægtsligning (formel eqref:eq:ligevaekst):

$$
\underbrace{N(t_2)-N(t_1)}_{\text{Vækst}}=\quad\underbrace{(F[t_1,t_2]-D[t_1,t_2])}_{\text{Naturlig vækst}} + 
\quad \underbrace{(I[t_1,t_2]-U[t_1,t_2])}_{\text{Nettovandring}}
$$

*** Eksempel

Vi henter tal fra den danske befolkning i 2022 fra
statistikbankens register FOLK1a, DOD, FOD, INDVAN og UDVAN.

#+ATTR_LATEX: :options otherkeywords={hent_data,tibble}, deletekeywords={list,c,D,I}
#+BEGIN_SRC R  :results output verbatim  :exports both  :session *R* :cache yes
N <- hent_data("FOLK1a",tid = c("2022K1","2023K1"))[["INDHOLD"]]
D <- hent_data("DOD",tid=2022)[["INDHOLD"]]
F <- hent_data("FOD",tid = 2022)[["INDHOLD"]]
I <- hent_data("INDVAN",tid=2022)[["INDHOLD"]]
U <- hent_data("UDVAN",tid=2022)[["INDHOLD"]]
# data for ligevægtsligningen
tibble(X=c("Folketal jan 2022",
           "Folketal jan 2023",
           "Fødsler 2022",
           "Dødsfald 2022",
           "Indvandring 2022",
           "Udvandre 2022"),
       Antal=c(N[1],N[2],F,D,I,U))
#+END_SRC

#+RESULTS[(2023-12-27 12:56:13) 3fc37cfa2bc47461c8cfc979a8fd2669c11b29d8]:
: # A tibble: 6 × 2
:   X                   Antal
:   <chr>               <dbl>
: 1 Folketal jan 2022 5873420
: 2 Folketal jan 2023 5932654
: 3 Fødsler 2022        58430
: 4 Dødsfald 2022       59435
: 5 Indvandring 2022   121183
: 6 Udvandre 2022       62927


Baseret på disse tal beregner vi vækst i den danske befolkningens i
perioden til $(5.932.654 - 5.873.420) = 59.234$ personer. Den
naturlige vækst i perioden er negativ: $(58.430 - 59.345) = -915$
personer og nettovandring i perioden positiv: $(121.183 - 62.927) =
58.256$ personer. Vi ser, at ligevægtsligningen (formel eqref:eq:ligevaekst) ikke går op, da der
mangler 1893 personer:

#+begin_export latex
$$
\underbrace{59.234}_{\text{Vækst}}=\quad\underbrace{-915}_{\text{Naturlig vækst}} + 
\quad \underbrace{58.256}_{\text{Nettovandring}} + \underbrace{1893}_{\text{fejl}}.
$$
#+end_export

Det vil sige, at de forskelige registre, som statistikbanken internt
bogfører, ikke er konsistente. Det kan der være mange grunde til. En
vigtig grund er, at det er svært at registrere de præcise datoer,
hvornår ind- og udvandringer sker.

Figur [[fig:3]] viser vækst, fødsler, dødsfald, ind- og udvandring
mellem 1980 og 2023 i den danske befolkning. Det er tydeligt, at
indvandring er den dominerede faktor for ændringer af folketallet i
denne periode, hvorimod fødsler og dødsfald er på et rimeligt konstant
niveau. Man kan også se, at udvandring er stigende helt op til 2019 men
knækker i 2020 på grund af coronakrisen.

#+ATTR_LATEX: :options otherkeywords={ggplot,hent_data,mutate,tibble}, deletekeywords={c,D,cbind,length,I,scale,legend,title,factor,rbind}
#+BEGIN_SRC R :results file graphics :file ./kapitel1/figure3.pdf :exports code :session *R* :cache yes 
# R-koder der producerer figur 3
V = hent_data("BEFOLK1",tid=1980:2022)
V = V %>% mutate(INDHOLD = INDHOLD- c(INDHOLD[1],INDHOLD[-length(INDHOLD)]))
D = hent_data("dod",tid=1980:2022)
D = D %>% mutate(INDHOLD = -INDHOLD)
F = hent_data("FOD",tid=1980:2022)
I = hent_data("INDVAN",tid=1980:2022)
U = hent_data("UDVAN",tid=1980:2022)
U = U %>% mutate(INDHOLD = -INDHOLD)
# samle data
dat <- tibble(rbind(cbind(X="Vækst",V),
                    cbind(X="Dødsfald",D),
                    cbind(X="Fødsler",F),
                    cbind(X="Indvandring",I),
                    cbind(X="Udvandring",U)))
dat <- dat %>% mutate(X = factor(X))
ggplot(dat,aes(TID,INDHOLD,color=X,group=X))+geom_line()+
  geom_point()+theme_wsj()+ scale_colour_wsj("colors6") +
theme(legend.title=element_blank())
#+END_SRC

#+RESULTS[(2023-11-07 16:42:12) 81d0b22d2b67c2707054181d6f5676bef69b9d78]:
[[file:./kapitel1/figure3.pdf]]

#+NAME: fig:3
#+ATTR_LATEX: :width 0.9\textwidth
#+CAPTION: Figuren viser ændringen i folketal (vækst), antal fødsler, dødsfald, ind- og udvandring siden 1980. 
[[file:./figure3.pdf]]



* Rater

I demografi bruger vi rater til at beskrive befolkningens relative
ændringer for at sammenligne forskelige befolkninger og for at
sammenligne befolkningsgrupper indenfor en befolkning. For eksempel
beskriver dødsraten antal døde relativt til befolkningens
størrelse. Det er som udgangspunkt typisk ikke meningsfyldt at
sammenligne absolut antal døde mellem befolkninger. For eksempel døde
569 personer på Bornholm og 2 personer på Christiansø i 2022. Her kan
man næppe konkludere, at dødeligheden var højere på Bornholm end på
Christiansø. Brugen af rater frem for absolut antal er yderst
relevant, når formålet er at sammenligne befolkninger, som har
forskellig størrelse. For eksempel var mortalitetsraten på Bornholm i
2022 lig med $569/39817 = 14,3$ per 1000 personår og på Christiansø
$2/91 = 22,0$ per 1000 personår i samme tidsperiode.

Som enhed for dødsraten bruges ofte /antal døde per personår/. Her
dividerer man antal døde i en periode med antal personår, som personer
fra befolkningen har levet i samme periode. Mere generelt har en rate
som kendetegn, at den er defineret som kvotient af to størrelser i
forskelige måleenheder. Ved beskrivelse af en rates enheder bruges
ordet ``per'' til at adskille enhederne for de to målinger, der bruges
til at beregne raten. For eksempel er hastighed af en cykel en rate,
som kan beskrives med enheden /kilometer per time/. Der findes også
dimensionsløse rater, som er kvotient af to forskelige størrelser med
samme måleenhed. Disse kan udtrykkes som en procentdel. De fleste
demografiske rater bruger /risikotid/ i nævneren og antal begivenheder
i tælleren og har dermed en enhed /antal begivenheder per personår/.


** Risikotid

Vi betegner med $R[t_1,t_2]$ den samlede gennemlevede tid i perioden
$[t_1,t_2]$ for alle personer i en befolkning og kalder den også for
/risikotid/. Udtrykket /risikotid/ giver egentlig kun mening når man
studerer en risikabel hændelse, som for eksempel død blandt personer,
som er eksponeret for risikoen for denne hændelse i perioden. Det er
især i epidemiologi, hvor man for eksempel kan interessere sig for
sygdomsrater, hvor nævneren er risikotid for personer, som var
eksponeret for sygdomsrisiko. I demografi bruger vi udtrykket
/risikotid/ også i andre sammenhænge. Enheden for risikotid er antal
personår. For at beskrive risikotid i små befolkninger kan den regnes
om til antal personuger eller antal persondage. For store befolkninger
vil man typisk regne om til enheder som /10.000 personår/, /100.000
personår/ eller /1.000.000 personår/. Kender man det eksakte antal
dage, som alle personer i en befolkning har levet i en given periode,
beregner man risikotiden eksakt som sum af alle persondage. Det kræver
dog, at man kender eksakte datoer for alle fødsler, dødsfald samt ind-
og udvandringer i perioden. Det gør man sjældent. Man kan dog estimere
risikotid baseret på registerdata. For at estimere risikotid i en
befolkning baseret på registerdata ganger vi typisk periodens
middelfolketal med periodens længde. For eksempel var
middelfolketallet i 2022 på Bornholm 39.817 personer (tal fra
statistikbankens register FOLK1a, metode 2 for middelfolketallet). Vi
estimerer dermed risikotid af Bornholms befolkning i året 2022 til
39.817 personår.

** Perioderater

Mange demografiske rater er defineret som antal begivenheder i en
periode, for eksempel antal dødsfald eller antal indvandringer, relativt til risikotid, altså antal
gennemlevede personår i samme periode i en befolkning:

#+begin_export latex
\begin{equation}\label{eq:rate}
\mbox{Rate}_X[t_1,t_2]=\frac{\text{Antal begivenheder X i perioden } [t_1,t_2]}{R[t_1,t_2]} 
\end{equation}
#+end_export

Denne formel kan anvendes rimelig generelt. Man skal dog være opmærksom
på at en korrekt fortolkning af  perioderater kræver
kendskab til begivenheden (hvad), befolkningen (hvem) og perioden
(hvornår). Desuden skal man huske at angive enheder, når man
rapporterer perioderater.

Vi beregner mortalitetsraten for Bornholm i året 2022:
#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output :exports both  :session *R* :cache yes  
1000*569/39817 
#+END_SRC

#+RESULTS[(2024-01-31 10:20:58) 7ae843ef05f0fad63be7b2e8f354f451b0fc7417]:
: [1] 14.29038
og konkluderer:

/Mortalitetsraten på Bornholm i året 2022 var 14.3 per 1000 personår./

#+begin_export latex
\mybox{
{\bf Bemærkning til terminologi}\\
Rater som tæller hændelser og risikotid i hele populationen kalder vi
for {\it summariske rater}. I det her kapitel omtaler vi kun {\it summariske
rater}. I næste kapitel, diskuterer vi også
{\it aldersspecifikke rater} og {\it standardiserede rater}. I det her
kapitel udelader vi at bruge prædikatet ``summarisk''. }
#+end_export

*** Eksempel

Vi illustrerer beregningen af perioderater og bruger flytningsrater
for flytninger indenfor Danmark i perioden fra 1. januar 2020
til 1. januar 2023 som eksempel. Først henter vi antal flytninger fra
statistikbankens register FLY.

#+ATTR_LATEX: :options otherkeywords={hent_data,summarise,pull}, deletekeywords={list,c,as,numeric}
#+BEGIN_SRC R  :results output verbatim :exports both  :session *R* :cache yes  
# Antal flytninger indenfor Danmark i årene 2020, 2021, 2022
FL <- hent_data("FLY",tid=2020:2022)
# Antal flytninger i perioden [2020,2022]
X <- pull(summarise(FL,sum(INDHOLD)))
X
#+END_SRC

#+RESULTS[(2023-12-27 12:51:00) 9494432020a4aba56ab25eb2bb41dc11270727c8]:
: [1] 2773056

Der er registreret 2.773.056 flytninger indenfor Danmark i perioden
fra 1. januar 2020 til 1. januar 2023. Bagefter henter vi folketal fra statistikbankens
register FOLK1a og beregner middelfolketal med metode 2. Vi beregner
også risikotid.

#+ATTR_LATEX: :options otherkeywords={hent_data,summarise,pull}, deletekeywords={list,c,as,numeric,R}
#+BEGIN_SRC R  :results output verbatim  :exports both  :session *R* :cache yes  
# Folketal for den danske befolkning i perioden
N <- hent_data("FOLK1a",tid = c("2020K1","2023K1"))
# Middelfolketal metode 2
NN <-  summarise(N,middelfolketal=mean(INDHOLD))
# Risikotid
Risikotid <-  summarise(NN,R= middelfolketal * as.numeric(as.Date("2023-01-01")-as.Date("2020-01-01"))/365.25)
R <- pull(Risikotid)
R
#+END_SRC

#+RESULTS[(2023-12-27 12:51:14) c345c07e30946352892dfc58fc3d2e0508268826]:
: [1] 17637149


Riskotiden af den danske befolkning i perioden fra 1. januar 2020 til 1.
januar 2023 er estimeret til 17.637.149 personår.

Til sidst beregner vi flytningsraten i perioden.

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={R}
#+BEGIN_SRC R  :results output verbatim  :exports both  :session *R* :cache yes
# Flytningsrate per personår
X/R
# Flytningsrate per 1000 personår
1000*X/R
#+END_SRC

#+RESULTS[(2023-12-27 12:51:27) ad0d4da845b6ec2a7cba09fce292c851fcca22f6]:
: [1] 0.1572281
: [1] 157.2281

Flytningsraten for flytninger internt i Danmark var 157.2 flytninger per 1000 personår i
perioden fra 1. januar 2020 til 1. januar 2023. 

** Demografiske vækstrater

Vi kan anvende formlen for perioderater (formel eqref:eq:rate) til
mortalitetsrater (begivenhed X er et dødsfald), fødselsrater
(begivenhed X er en fødsel), indvandringsrater (begivenhed X er en
indvandring) og udvandringsrater (begivenhed X er en udvandring). På
den måde kan vi beskrive en dekomposition af demografiske vækstrater.

Vi trækker $N(t_1)$ fra begge sidder af den demografiske
ligevægtsligning (formel eqref:eq:ligevaekst) og dividerer på begge
sidder af lighedstegnet med $R[t_t,t_2]$. Det giver følgende
dekomposition af befolkningens vækstrate i perioden $[t_1,t_2]$:

#+begin_export latex
\begin{multline}\label{eq:ligevaekstrate}
\underbrace{\frac{N(t_2)-N(t_1)}{R[t_1,t_2]}}_{\text{Vækstrate}}=
\underbrace{\frac{F[t_1,t_2]}{R[t_1,t_2]}}_{\text{Fødselsrate}}
-
\underbrace{\frac{D[t_1,t_2]}{R[t_1,t_2]}}_{\text{Mortalitetsrate}}
\\
+
\underbrace{\frac{I[t_1,t_2]}{R[t_1,t_2]}}_{\text{Immigrationsrate}}
-
\underbrace{\frac{U[t_1,t_2]}{R[t_1,t_2]}}_{\text{Emigrationsrate}}
\end{multline} 
#+end_export

Vi bemærker at mortalitetsrater og udvandringsrater er
begivenhedsrater/eksponeringsrater. Her giver udtrykket /risikotid/ mening,
fordi $R[t_1,t_2]$ stammer fra de personer som faktisk var under
risiko for hændelsen.

*** Eksempel

Vi beregner vækstrater, som defineret i ligning
eqref:eq:ligevaekstrate, for den danske befolkingen i
perioden 1. januar 2022 til 1. januar 2023. Ud over data, som vi
allerede har brugt i eksempel for den demografiske ligevægtsligning,
har vi nu brug for risikotid for den danske befolkning i perioden. Vi
anvender metode 2 for middelfolketallet og beregner risikotid ved at
gange med 1 år:

#+ATTR_LATEX: :options otherkeywords={hent_data}, deletekeywords={c}
#+BEGIN_SRC R  :results output verbatim  :exports both  :session *R* :cache yes  
N <- hent_data("FOLK1a",tid=c("2022K1","2023K1"))[["INDHOLD"]]
vækst <- N[2]-N[1]
middelfolketal  <- mean(N)
risikotid <- middelfolketal*1
risikotid
#+END_SRC

#+RESULTS[(2023-12-27 12:51:52) 52e600a64c087c75992022191cf31e8be4d71e5b]:
: [1] 5903037

Risikotiden i den danske befolkning var således 5.903.037 personår mellem 1.
januar 2022 og 1. januar 2023. Vi henter antal begivenhedder og beregner raterne.

#+ATTR_LATEX: :options otherkeywords={hent_data}, deletekeywords={D,I}
#+BEGIN_SRC R  :results output verbatim  :exports both  :session *R* :cache yes
# mortalitetsrate
D <- hent_data("DOD",tid=2022)[["INDHOLD"]]
Drate <- 1000*D/risikotid
# fødselsrate
F <- hent_data("FOD",tid=2022)[["INDHOLD"]]
Frate <- 1000*F/risikotid
# indvandringsrate
I <- hent_data("INDVAN",tid=2022)[["INDHOLD"]]
Irate <- 1000*I/risikotid
# udvandringsrate
U <- hent_data("UDVAN",tid=2022)[["INDHOLD"]]
Urate <- 1000*U/risikotid
# væksrate
Vrate <- 1000*vækst/risikotid
# naturlige væksrate
NaturVrate <- Frate-Drate
# nettovandringsrate
NettoVrate <- Irate-Urate
x=tibble(X=c("Vækstrate",
           "Mortalitetsrate",
           "Fødselsrate",
           "Indvandringsrate",
           "Udvandringsrate",
           "Naturlige_vækst_rate",
           "Netto_vandrings_rate"),
       Rate=c(Vrate,Drate,Frate,Irate,Urate,NaturVrate,NettoVrate))
x
#+END_SRC

#+RESULTS[(2023-12-27 12:52:58) f9f279f1e0bea9f2c5ec1ac906aa06971a75c8cc]:
#+begin_example
# A tibble: 7 × 2
  X                      Rate
  <chr>                 <dbl>
1 Vækstrate            10.0  
2 Mortalitetsrate      10.1  
3 Fødselsrate           9.90 
4 Indvandringsrate     20.5  
5 Udvandringsrate      10.7  
6 Naturlige_vækst_rate -0.170
7 Netto_vandrings_rate  9.87
#+end_example

I 2022 voksede den danske befolkning med 10,0 personer per 1000
personår. Den naturlige vækstrate var -0,2 personer per 1000 personår
og nettovandringsraten var 9,9 personer per 1000 personår. Ligesom
den demografiske ligevægtsligning ikke går op, gør denne formel heller
ikke, og der er en fejlrate:

# silent
#+BEGIN_SRC R  :results output raw  :exports none  :session *R* :cache yes
1000*(59234  + 915 - 58256)/risikotid
10.03+0.17-9.87
#+END_SRC

#+begin_export latex
\begin{xalignat*}{2}
\underbrace{\mbox{10,0}}_{\text{Vækstrate}}&
=\underbrace{\mbox{-0,2}}_{\text{Naturlig vækstrate}} 
&+ \underbrace{\mbox{9,9}}_{\text{Nettovandringsrate}}+ \underbrace{\mbox{0,3}}_{\text{fejlrate}}.
\end{xalignat*}
#+end_export   



#+TITLE: Grundbegreber
#+AUTHOR: Anna-Vera Jørring Pallesen, Johan Sebastian Ohlendorff, Laust Hvas Mortensen and Thomas Alexander Gerds
#+DATE: 
#+LANGUAGE: dk
#+LaTeX_CLASS: danish-article
#+OPTIONS: toc:nil
#+LaTeX_HEADER:\usepackage{authblk}
#+LaTeX_HEADER:\usepackage{natbib}
#+LaTeX_HEADER:\usepackage{listings}
#+LaTeX_HEADER:\usepackage{color}
#+LaTeX_HEADER:\usepackage[usenames,dvipsnames]{xcolor}
#+LaTeX_HEADER:\usepackage[utf8]{inputenc}
#+LaTeX_HEADER:\usepackage{graphicx}
#+LaTeX_HEADER:\usepackage{hyperref}
#+LaTeX_HEADER:\usepackage{amssymb}
#+LaTeX_HEADER:\usepackage{latexsym}
#+LaTeX_HEADER: \renewcommand{\figurename}{Figur}
#+LaTeX_HEADER:\usepackage{tcolorbox}
#+LaTeX_HEADER:\definecolor{lightGray}{gray}{0.98}
#+LaTeX_HEADER:\definecolor{medioGray}{gray}{0.83}
#+LATEX_HEADER:\definecolor{mygray}{rgb}{.95, 0.95, 0.95}
#+LATEX_HEADER:\newcommand{\mybox}[1]{\vspace{.5em}\begin{tcolorbox}[boxrule=0pt,colback=mygray] #1 \end{tcolorbox}}
#+OPTIONS:   H:3  num:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:t todo:t pri:nil tags:not-in-toc author:t
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://publicifsv.sund.ku.dk/~tag/styles/all-purpose.css" />
