* Demografi

Demografi er studiet af menneskers befolkningsegenskaber og deres
forandringer over tid og sted. Det inkluderer undersøgelser af
befolkningens størrelse, aldersfordeling, kønsfordeling, etnicitet,
sprog, religion, uddannelse, erhverv og andre relevante faktorer.
Demografer anvender forskellige metoder, såsom dataindsamling og
statistisk analyse, til at undersøge og beskrive befolkningstrends og
-mønstre. Demografi spiller en vigtig rolle i samfundets planlægning
og politikudvikling, da det kan give vigtig information om en
befolknings sundhedstilstand, uddannelsesbehov, arbejdsstyrke og
økonomisk udvikling. Nogle af de områder, hvor demografi er relevant,
inkluderer folkesundhed, økonomi, planlægning af byer og samfund,
arbejdsmarked og socialpolitik. Metoderne som vi bruger til demografi
er tæt beslægtet med metoder fra epidemiologi og statistik.

* Befolkning

I demografi refererer udtrykket /befolkning/ til den gruppe af
mennesker, der bor inden for et geografisk område eller en juridisk
enhed ved et bestemt tidspunkt. Dermed kan man tale om Danmarks
befolkning den 26 juni 1992, og om Nordeuropas befolkning den første
april 2000. En befolkning kan opdeles og analyseres efter kriterier
som for eksempel bopæl, køn, alder, civilstand, etnisk gruppe,
uddannelse, erhverv, fag og stilling. Tilsammen er alle disse grupper
udtryk for befolkningsstrukturen. En /befolkningsgruppe/ er en del af
en befolkning som opfylder yderlige kriterier. For eksempel, danner
alle Kvinder, som modtager SU, er yngre end 25 år, og bor i Region
Sjælland den 1 januar 2023, en befolkninggruppe.

Befolkning i demografi kan beskrives og analyseres med statistikker
som befolkningsstørrelse, befolkningstæthed, aldersfordeling,
kønsfordeling, etnicitet og mange andre faktorer, der kan give indsigt
i befolkningens dynamik og sammensætning. Disse statistikker bruges
ofte til at forudsige og planlægge behovet for offentlige tjenester og
politikker, såsom sundhedsvæsnet, uddannelse og beskæftigelse.


** Befolkningens størrelse

Lad os tage udgangspunkt i den danske befolkning og starte med at se
på dens størrelse. Folketal $N(t)$ angiver befolkningens størrelse til
tid $t$, hvor $t$ er en dato i kalenderen. Ifølge statistikbanken [fn:1] var
der 5.806.081 personer i Danmarks befolkning den 1 januar 2019:

\begin{align*}
\text{Befolkning} &= \text{Hele Danmark} \\
t_1&= \texttt{2019-01-01} \\
N(t_1) &= 5.806.081
\end{align*}

På et senere tidspunkt vil befolkningens størrelse have ændret sig som
følge af fødsler, dødsfald og ind- og udvandring. Den 1 januar 2023
var der 5.932.654 personer i Danmarks befolkning. Dermed er den danske
befolkning vokset med 126.573 personer i de 1461 dage mellem den 1
januar 2019 og den 1 januar 2023. Her er R-koder som kan bruges til at
beregne antal dage mellem to datoer og ændring af folketal i perioden.

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={t,as}
#+BEGIN_SRC R  :results output example :exports both  :session *R* :cache yes  
# R-code
t_1= as.Date("2019-01-01")
t_2= as.Date("2023-01-01")
N_1 = 5806081
N_2 = 5932654
data.frame("dato"=c(t_1,t_2),
           "Folketal"=c(N_1,N_2),
           "Antal dage"=c(NA,t_2-t_1),
           "Vækst"=c(NA,N_2-N_1))
#+END_SRC

:         dato Folketal Antal.dage  Vækst
: 1 2019-01-01  5806081         NA     NA
: 2 2023-01-01  5932654       1461 126573

Folketallet ændrer sig jo hver dag, men det er svært at registrere og
tælle nøjagtigt for enkelte dage. Heldigvis betyder små unøjagtigheder
i tallene typisk ikke meget for demografiske
konklusioner. Statistikbanken angiver folketal i starten af
hvert kvartal siden 2008 (FOLK1A), den første januar per år siden 1971
(BEFOLK1), den første januar per år siden 1901 (HISB3). Desuden er der
summariske tal fra folketællinger hele vejen fra 1769 (FT). Disse tal
bliver vist i Figure ref:fig:1.

#+BEGIN_SRC R :results file graphics :file ./kapitel1/figure1.pdf :exports none :session *R* :cache yes
library(danstat)
library(ggplot2)
library(ggthemes)
options(readr.show_col_types = FALSE)
dt_meta <- get_table_metadata("FT")
dt=get_data("FT",variables=list(list(code="tid",values=dt_meta$variables$values[[2]][[2]])))
ggplot(dt,aes(TID,INDHOLD))+geom_line()+geom_point()+theme_wsj()+ scale_colour_wsj("colors6")
#+END_SRC

#+RESULTS[(2023-11-06 11:34:16) e930586f8196697970f2e417b783cab3dc1c97f7]:
[[file:./kapitel1/figure1.pdf]]

#+name: fig:1
#+ATTR_LATEX: :width 0.7\textwidth
#+CAPTION: Udvikling af den danske befolkning siden 1769. Summariske tal fra folketællinger, statistikbankens register FT.
[[file:./figure1.pdf]]



[fn:1] https://statistikbanken.dk/

** Middelfolketal

Vi indfører nu begrebet middelfolketal, som bruges til at estimere et
gennemsnitlige folketal i en given tidsperiode.  Middelfolketallet er
en vigtig demografisk indikator, der indgår f.eks., i fertilitetsrater
og dødelighedstavler. Middelfolketallet er defineret som det
gennemsnitlige folketal i en given tidsperiode.  Vi betegner
middelfolketallet med $\tilde N$.

For at beregne middelfolketallet helt korrekt, ville man for alle
personer være nødt til at tælle hvor mange dage de har levet i
perioden i befolkningen.  Så kunne man beregne middelfolketallet
eksakt som den samlede gennemlevede tid divideret med periodens
længde. Denne beregning giver et gennemsnitligt antal mennesker, der
bor i området over en given tidsperiode.

Praktisk kender man desværre ikke de præcise tal, altså hvor mange
dage alle personer fra en befolkning har levet i en given
tidsperiode. Derfor er flere metoder, der kan bruges til at beregne
middelfolketallet approksimativt baseret på enkelte folketal i en
given tidsperiode.

***  Metode 1

Her skal man kun kende et enkelt folketal, nemlig folketallet cirka i
midten af perioden. Hvis perioden starter i tidspunkt $t_1$ og slutter
i tidspunkt $t_2$, så er tidspunkt i midten given som $(t_1+t_2)/2$ og
folketal i midten er given ved $\tilde N[t_1,t_2]=N((t_1+t_2)/2)$.

Dette tal bruges som et estimat for middelfolketallet. Denne metode er
simpel og tilstrækkeligt for mange formål, især når folketallet ikke
ændrer sig særlig meget i den given tidsperiode. For eksempel bruger
Danmark Statistik folketal fra den 1. juli som årets middelfolketal i
de årlige rapporter om befolknings udvikling [fn:2].

[fn:2] https://www.dst.dk/da/Statistik/nyheder-analyser-publ/Publikationer/

***  Metode 2

For at bruge denne metode skal man kende folketal i starten og i
slutningen af perioden. Det estimerede middelfolketal er
gennemsnit af de to folketal: $\tilde N[t_1,t_2]=(N(t_1)+N(t_2))/2$.

***  Metode 3 

Her skal man kende folketal i starten, i slutningen og ved mindst et
tidspunkt mere i perioden. Lad os antage at vi kender folketal til $J$
forskelige tidspunkter $t_1 < t_2 < \dots <t_J$. Det estimerede
middelfolketal for perioden $[t_1,t_J]$ kan beregnes med følgende
formel:

\begin{align*}
\tilde N[t_1,t_J] &= \frac 1 {(t_J-t_1)}\sum_{j=2}^J (t_j-t_{j-1}) \frac{(N(t_{j-1})+N(t_j)}{2}\\
             &= \frac{(t_2-t_1)}{(t_J-t_1)}  \frac{(N(t_{2})+N(t_1)}{2} +\cdots +\frac{(t_J-t_{J-1})}{(t_J-t_1)}  \frac{(N(t_{J})+N(t_{J-1})}{2}
\end{align*}

Alle tre metoder kan bruges ligeværdig hvis folketallet er
relativt stabil i perioden.  Ændrer folketallet sig meget i perioden,
er metode 2 en bedre tilnærmelse til det sande ukendte
middelfolketal end metode 1, og ligeligt er metode 3
er bedre end metode 2. Figure ref:fig:2 visualiserer
forskellen mellem de 3 metoder.

#+BEGIN_SRC R :results file graphics :file ./kapitel1/figure2.pdf :exports none :session *R* :cache yes
par(mfrow=c(2,2))
## Metode 1
x <- as.Date(c(paste0("2019-",c("01","04","07","10"),"-01"),"2020-01-01"))
y <- c(5806081, 5811413,5814461,5827463,5822763)
plot(x,y,type="b",main=" Metode 1",xlim=as.Date(c("2019-01-01","2019-12-31")),ylab="Folketal N(t)",xlab="Kalenderår 2019",ylim=c(5800000,5850000),lty=1,lwd=3,pch=8,axes=FALSE)
rect(xleft=x[1],xright=x[5],ybottom=5800000,ytop=y[3],col="orange",border=NA,density=70)
lines(x,y,type="b",lwd=3)
axis(1,at=x,lab=c(paste0("K",1:4),"2020-01-01"))
axis(2)
## Metode 2
x <- as.Date(c(paste0("2019-",c("01","04","07","10"),"-01"),"2020-01-01"))
y <- c(5806081, 5811413,5814461,5827463,5822763)
plot(x,y,type="b",main=" Metode 2",xlim=as.Date(c("2019-01-01","2019-12-31")),ylab="Folketal N(t)",xlab="Kalenderår 2019",ylim=c(5800000,5850000),lty=1,lwd=3,pch=8,axes=FALSE)
u <- polygon(x=c(x[1],x[length(x)],x[length(x)],x[1]),y=c(y[1],y[length(y)],0,0),col=2,density=70)
lines(x,y,type="b",lwd=3)
axis(1,at=x,lab=c(paste0("K",1:4),"2020-01-01"))
axis(2)
## Metode 3
x <- as.Date(c(paste0("2019-",c("01","04","07","10"),"-01"),"2020-01-01"))
y <- c(5806081, 5811413,5814461,5827463,5822763)
plot(x,y,type="b",main=" Metode 3",xlim=as.Date(c("2019-01-01","2019-12-31")),ylab="Folketal N(t)",xlab="Kalenderår 2019",ylim=c(5800000,5850000),lty=1,lwd=3,pch=8,axes=FALSE)
polygon(x=as.numeric(c(x, rev(x))),y=as.numeric(c(y,rep(0,length(y)))),col=3,density=70)
lines(x,y,type="b",lwd=3)
axis(1,at=x,lab=c(paste0("K",1:4),"2020-01-01"))
axis(2)
## Summary
plot(0,0,type="n",xlab="",ylab="",main="Middelfolketal 2019",axes=0L)
library(plotrix)
library(data.table)
tab <- t(data.table("Metode 1"=y[3],
                    "Metode 2"=(y[1]+y[5])/2,
                    "Metode 3"=round(sum((y[-length(y)]+y[-1])/2*diff(as.numeric(x)))/365)))
tab <- cbind(rownames(tab),tab)
colnames(tab) <- c("Metode","Værdi")
plotrix::addtable2plot(x=-.7,y=-.5,tab,cex=1.3,hlines=1,vlines=1,xpad=.5,ypad=1)
#+END_SRC

#+RESULTS[(2023-11-06 13:21:05) 77ea44b083d599c057c029220aed9c1dbe33c8e7]:
[[file:./kapitel1/figure2.pdf]]

#+name: fig:2
#+ATTR_LATEX: :width 0.9\textwidth
#+CAPTION: Figuren viser de 3 metoder for at beregne middelfolketal baseret på 5 folketal: 1 januar 2019, 1 april 2019, 1 juli 2019, 1 october 2019, 1 januar 2023.
[[file:./figure2.pdf]]


*** Eksempel

Vi beregner middelfolketal for den danske befolkning i en periode, som
starter den 1 januar 2016 og slutter den 1 januar 2023. Fra
statistikbankens =BEFOLK1= henter vi folketal i starten, midten og
slutningen af perioden:

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output   :exports both  :session *R* :cache yes
library(danstat)
library(tidyverse)
library(stringi)
dt=get_data("BEFOLK1",variables=list(list(code="tid",values=c(2009,2016,2023))))
dt
#+END_SRC

#+RESULTS[(2023-11-02 17:57:32) dbd8ef89df9cf9a03dde3688b241153a20e5a806]:
#+begin_example
# A tibble: 3 × 2
    TID INDHOLD
  <dbl>   <dbl>
1  2009 5511451
2  2016 5707251
3  2023 5932654
#+end_example

Det er nemmest at anvende metode 1. Med metode 1 er
det estimerede middelfolketal \(\tilde N[\texttt{1 januar 2016},\texttt{1
jan 2023}] = 5.707.251\) personer. For at beregne metode 2
bruger vi R som lommerregner:

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output  example  :exports both  :session *R* :cache yes
# Metode 2
(5511451 + 5707251)/2
#+END_SRC

#+RESULTS[(2023-11-06 10:01:11) 78791514d677aa50d446ee4966a524a61a369c65]:
: [1] 5609351

Med metode 2 estimerer vi middelfolketallet i perioden 2009--2023 dermed til
\(5.609.351\) personer. For metode 3 er beregningen i R den følgende:

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output example  :exports both  :session *R* :cache yes  
# Metode 3
(2016-2009)/(2023-2009)*(5511451+5707251)/2 + (2023-2016)/(2023-2009)*(5707251+5932654)/2
#+END_SRC

#+RESULTS[(2023-11-06 10:00:59) f21cbcd580ee62077267204df1a604fd2ff170a1]:
: [1] 5714652

Med metode 3 estimerer vi middelfolketallet i perioden 2009--2023 til
\(5.714.652\) personer baseret på de 3 folketal fra perioden.  Vi ser
i det her eksempel at der er mere end 100.000 personer forskel mellem
metode 3 og metode 2. Om denne forskel er vigtigt eller ej, ville
afhænge formålet med den konkrete demografiske undersøgelse. Er den
vigtigt, ville man prøve at estimere middelfolketallet så godt som
muligt. For at gør det ville man hente så mange folketal som muligt
fra perioden, og så beregne middelfolketallet med metode 3 på alle
disse tal. Følgende R-koder henter alle folketal mellem 1 januar 2009
og 1 januar 2023 fra statistikbankens register FOLK1a og andvender
metode 3.

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output example  :exports both  :session *R* :cache yes  
library(tidyverse)
library(stringi)
# Metode 3 baseret på 57 folketal mellem 2009 og 2023
# konstruere vektor 2009K1, 2009K2, ..., 2022K4
kvartal_years <- paste0(rep(2009:2022,rep(4,14)),"K",1:4)
# tilføj 2023K1
kvartal_years <- c(kvartal_years,"2023K1")
# hent data fra FOLK1a 
dt <- get_data("FOLK1a",variables=list(list(code="tid",
                                            values=kvartal_years)))
# transform årstal + kvartal til dato
patt <- pattern=c("Q1","Q2","Q3","Q4")
repl <- c("-01-01","-01-04","-01-07","-01-10")
dt <- mutate(dt,
             TID=stri_replace_all_regex(TID,
                                        pattern=pat,
                                        replace=repl,
                                        vectorize_all=FALSE))
# transform fra character til dato
dt <- mutate(dt, TID=as.Date(TID)) 
# anvend middelfolketal metode 3
summarise(dt,{
  len <- length(TID)
  len_periode_total <- as.numeric(TID[length(TID)]-TID[1])
  len_periode <- as.numeric(TID[-1]-TID[-len])
  ft_gennemsnit <-(INDHOLD[-len]+INDHOLD[-1])/2 
  sum(len_periode*ft_gennemsnit)/len_periode_total
})
#+END_SRC

#+RESULTS[(2023-11-06 11:51:27) 3634bb3bd997b9588f2b0571e5cc102ae568a38d]:
: 5717974

Baseret på 57 folketal i perioden mellem den 1 januar 2009 og den 1
januar 2023 estimerer vi middelfolketal for perioden til 5.717.974
personer.

* Den demografiske ligevægtsligning

Den demografiske ligevægtsligning er en formel, der bruges i
demografisk analyse til at beskrive forholdet mellem antallet af
fødsler, dødsfald og migration i periode i en befolkning. Jo flere
dødsfald sker og jo flere personer emigrerer jo mindre er folketal i
slutningen af perioden sammenlignet med starten af perioden. Ligeligt
er folketal i slutningen jo højere jo flere personer bliver født og
indvandrer til befolkningen. Den demografiske ligevægtsligning for en
periode \([t1,t2]\) er:
\begin{equation*}
N(t_2) = N(t_1) + (F[t_1,t_2] - D[t_1,t_2]) + (I[t_1,t_2] - U[t_1,t_2]).
\end{equation*}
hvor vi har brugt følgende notation:
- $N(t_1)$ er folketal på tidspunkt $t_1$
- $N(t_2)$ er folketal på tidspunkt $t_2$
- $F(t_1,t_2)$ er antallet af fødsler i perioden
- $D(t_1,t_2)$ er antallet af dødsfald i perioden
- $I(t_1,t_2)$ er antallet af indvandrere i perioden
- $U(t_1,t_2)$ er antallet af udvandrere i perioden

Formlen siger kort sagt, at den samlede befolkning på et tidspunkt
$t_2$ er lig den samlede befolkning på tidspunktet $t_1$ plus en
stigning i befolkningen på grund af fødsler og indvandring og en
reduktion i befolkningen på grund af dødsfald og udvandring. Vi kalder
forskel mellem fødsler og dødsfald \((F[t_1,t_2] - D[t_1,t_2])\) for
/naturlig vækst/ og forskel mellem ind- og udvandring \((I[t_1,t_2] -
U[t_1,t_2])\) for /nettovandring/. Det giver følgende version af den
demografiske ligevægtsligning:

\begin{equation*}
\underbrace{N(t_2)-N(t_1)}_{\text{Vækst}}=\quad\underbrace{(F[t_1,t_2]-D[t_1,t_2])}_{\text{Naturlig vækst}} + 
\quad \underbrace{(I[t_1,t_2]-U[t_1,t_2])}_{\text{Nettovandring}}
\end{equation*}

Figure ref:fig:3 viser vækst, fødsler, dødsfald, ind- og udvandring
mellem 1980 og 2023 i den danske befolkning. Det er tydeligt at
indvandring er er den dominerede faktor for ændringer af folketal i
denne periode hvorimod fødsler og dødsfald holder et rimlig konstant
niveau. Man kan også se at udvandring er stigende helt op til 2019 men
knækker i 2020 på grund af corona krisen.

#+BEGIN_SRC R :results file graphics :file ./kapitel1/figure3.pdf :exports none :session *R* :cache yes 
setwd("~/metropolis/Teaching/demogRafi/")
library(data.table)
library(ggthemes)
library(ggplot2)
X <- data.table(rbind(cbind(X="Vækst",get_data("BEFOLK1",list(list(code="tid",values=1980:2022)))),
                      cbind(X="Dødsfald",get_data("DOD",list(list(code="tid",values=1980:2022)))),
                      cbind(X="Fødsler",get_data("FOD",list(list(code="tid",values=1980:2022)))),
                      cbind(X="Indvandring",get_data("INDVAN",list(list(code="tid",values=1980:2022)))),
                      cbind(X="Udvandring",get_data("UDVAN",list(list(code="tid",values=1980:2022))))))
X[X=="Vækst",INDHOLD:=INDHOLD- c(INDHOLD[1],INDHOLD[-length(INDHOLD)])]
X[X%in%c("Udvandring","Dødsfald"),INDHOLD:=-INDHOLD]
X[,X:=factor(X,levels=c("Dødsfald","Fødsler","Vækst","Indvandring","Udvandring"),labels=c("Dødsfald","Fødsler","Vækst","Indvandring","Udvandring"))]
ggplot(X,aes(TID,INDHOLD,color=X,group=X))+geom_line()+geom_point()+theme_wsj()+ scale_colour_wsj("colors6") +theme(legend.title=element_blank())
#+END_SRC

#+RESULTS[(2023-11-07 16:42:12) 81d0b22d2b67c2707054181d6f5676bef69b9d78]:
[[file:./kapitel1/figure3.pdf]]

#+name: fig:3
#+ATTR_LATEX: :width 0.9\textwidth
#+CAPTION: Siden 1980 ændring i folketal (vækst), antal fødsler, dødsfald, ind- og udvandring.
[[file:./figure3.pdf]]

*** Eksempel

Vi henter tal fra den danske befolkning i året 2022 fra
statistikbankens register FOLK1a, DOD, FOD, INDVAN og UDVAN.

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={list,c,D,I}
#+BEGIN_SRC R  :results output example  :exports both  :session *R* :cache yes
N <- get_data("FOLK1a",
              list(list(code="tid",
                        values=c("2022K1","2023K1"))))[["INDHOLD"]]
D <- get_data("DOD",
              list(list(code="tid",
                        values=2022)))[["INDHOLD"]]
F <- get_data("FOD",
              list(list(code="tid",
                        values=2022)))[["INDHOLD"]]
I <- get_data("INDVAN",
              list(list(code="tid",
                        values=2022)))[["INDHOLD"]]
U <- get_data("UDVAN",
              list(list(code="tid",
                        values=2022)))[["INDHOLD"]]
})
# data for ligevægtsligningen
data.frame(X=c("Folketal jan 2022",
               "Folketal jan 2023",
               "Fødsler 2022",
               "Dødsfald_2022",
               "Indvandring 2022",
               "Udvandre 2022"),
           Antal=c(N[1],N[2],F,D,I,U))
#+END_SRC

#+RESULTS[(2023-11-06 13:58:23) fef9517e3a345af0707b735604a6d6d84f13b2e9]:
:                   X   Antal
: 1 Folketal jan 2022 5873420
: 2 Folketal jan 2023 5932654
: 3     Fødsler 2022   58430
: 4    Dødsfald_2022   59435
: 5  Indvandring 2022  121183
: 6     Udvandre 2022   62927

Baseret på disse tal beregner vi at den danske befolkningens vækst i
perioden til (5.932.654 - 5.873.420) = 59.234 personer. Den naturlige
vækst i perioden er negativt: (58.430 - 59.345) = -915 personer og
nettovandring i perioden positivt: (121.183 - 62.927) = 58.256
personer. Vi ser at ligevægtsligningen ikke går op, der mangler 1893
personer:

#+begin_export latex
\begin{equation*}
\underbrace{59.234}_{\text{Vækst}}=\quad\underbrace{-915}_{\text{Naturlig vækst}} + 
\quad \underbrace{58.256}_{\text{Nettovandring}} + \underbrace{1893}_{\text{fejl}}.
\end{equation*}
#+end_export

Det vil sige at de forskelige register
som statistikbanken bogfører er ikke intern konsistent. Det kan være
mange grunde til. En vigtig grund er at det er svært at registrere de
præcise datoer hvor ind- og udvandringer sker.

* Rater

I demografi bruger vi rater til at beskrive befolkningens relative
ændringer, for at sammenligne forskelige befolkninger og for at
sammenligne befolkningsgrupper indenfor en befolkning. For eksempel
beskriver dødsraten antal døde relativt til befolkningens
størrelse. Det er som udgangspunkt typisk ikke meningsfyld at
sammenligne absolut antal døde i forskellige stor befolkninger. For
eksempel døde 569 personer på Bornholm og 2 personer på Christiansø
i 2022. Her kan man næppe konkludere at dødeligheden var højere på
Bornholm end på Christiansø. Brugen af rater frem for absolut antal er
yderst relevant når formålet er at sammenligne befolkninger som har
forskellig størrelse. For eksempel var mortalitetsraten på Bornholm i
2022 lige med 569/39817 = 14,3 per 1000 personår og på Christiansø
2/91 = 22,0 per 1000 personår i samme tidsperiode.

Som enhed for dødsraten bruges ofte /antal døde per personår/. Her
dividerer man antal døde i en periode med antal personår som personer
fra befolkningen har livet i samme periode. Mere generalt har en rate
som kendetegn at den er defineret som kvotient af to størrelser i
forskelige måleenheder. Ved beskrivelse af en rates enheder bruges
ordet ``per'' til at adskille enhederne for de to målinger, der bruges
til at beregne raten. For eksempel er hastighed af en cykel en rate
som kan beskrives med enheden /kilometer per time/. Der findes også
dimensionsløse rater som er kvotient af to forskelige størrelser med
samme måleenhed. Disse kan udtrykkes som en procentdel. De fleste
demografiske rater bruger /risikotid/ i nævneren og antal begivenheder
i tælleren og har dermed en enhed /antal begivenheder per personår/.


** Risikotid

Vi betegner med \(R[t_1,t_2]\) det samlede gennemlevede tid i perioden
\([t_1,t_2]\) af alle personer i en befolkning og kalder den også for
/risikotid/. Udtrykket /risikotid/ giver egentlig kun mening når man
studerer en risikabel hændelse, som for eksempel død, blandt personer,
som er eksponeret for denne hændelse i perioden. Det er især i
epidemiologi hvor man for eksempel kan interessere sig for
sygdomsrater hvor nævneren er risikotid fra personer som var
eksponeret til sygdomsrisiko. Men, i demografi bruger vi udtrykket
/risikotid/ også i andre sammenhænge. Enheden for risikotid er antal
personår. For at beskrive risikotid i lille befolkninger kan den
regnes om til antal personuger eller antal persondage. For stor
befolkninger vil man typisk regne om til enheder som /10.000
personår/, /100.000 personår/ eller /1.000.000 personår/. Kender man
det eksakte antal dage som alle personer fra en befolkning har livet i
en given periode beregner man risikotiden eksakt som sum af alle
persondage. Det kræver dog at man kender eksakte datoer for alle
fødsler, dødsfald, ind- og udvandringer i perioden.  Det gør man
sjældent. Men, man kan estimere risikotid baseret på registerdata. For
at estimere risikotid i en befolkning baseret på registerdata
multiplicerer vi typisk periodens middelfolketal med periodens
længde. For eksempel var middelfolketallet i 2022 på Bornholm 39.817
personer (tal fra statistikbankens register FOLK1a, metode 2 for
middelfolketallet). Vi estimerer dermed risikotid af Bornholms
befolkning i året 2022 til 39.817 personår.

** Perioderater

Mange demografiske rater er defineret som antal begivenheder i en
periode (f.eks., dødsfald eller indvandringer) relativt til antal
gennemlevede personår i samme periode i en befolkning:

\begin{equation*}
\mbox{Rate}_X[t_1,t_2]=\frac{\text{Antal begivenheder X i perioden } [t_1,t_2]}{R[t_1,t_2]}
\end{equation*}

Denne formel kan anvendes rimlig generalt. Man skal dog være opmærksom
på at en korrekt fortolkning af  perioderater kræver
kendskab af begivenheden (hvad), befolkningen (hvem) og perioden
(hvornår). Desuden skal man huske at angive enheden når man
rapporterer perioderater.

** Terminologi

Rater som tæller hændelser og risikotid i hele populationen kalder vi
for summariske rater. I det her kapitel omtaler vi kun summariske
rater. Senere i dette kompendium, introducerer vi også
aldersspecifikke rater og især standardiserede rater. I det her
kapitel glemmer vi prædikatet ``summarisk'' systematisk fra raterne.

*** Eksempel

Vi illustrerer beregningen af perioderater og bruger inderdanske
flytningsrater i perioden fra 1 januar 2020 til 1 januar 2023 som
eksempel. Først henter vi antal flytninger fra statistikbankens
register FLY.

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={list,c,as,numeric}
#+BEGIN_SRC R  :results output :exports both  :session *R* :cache yes  
# Antal flytninger indenfor Danmark i årene 2020, 2021, 2022
FL <- get_data("FLY",
               list(list(code="tid",
                         values=2020:2022)))
# Antal flytninger i perioden [2020,2022]
X <- pull(summarize(FL,sum(INDHOLD)))
X
#+END_SRC

: [1] 2773056

Der er 2.773.056 flytninger indenfor Danmark registreret i perioden
fra 1 januar 2020 til 1 januar 2023. Bagefter henter vi folketal fra statistikbankens
register FOLK1a og beregner middelfolketal med metode 2. Vi beregner
også risikotid.

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={list,c,as,numeric,R}
#+BEGIN_SRC R  :results output raw drawer  :exports both  :session *R* :cache yes  
# Folketal for den danske befolkning i perioden
N <- get_data("FOLK1a",list(list(code="tid",values=c("2020K1","2023K1"))))
# Middelfolketal metode 2
NN <-  summarise(N,middelfolketal=mean(INDHOLD))
# Risikotid
Risikotid <-  summarise(NN,R= middelfolketal * as.numeric(as.Date("2023-01-01")-as.Date("2020-01-01"))/365.25)
R <- pull(Risikotid)
R
#+END_SRC

: [1] 17637149

Riskotiden af den danske befolkning i perioden fra 1 januar 2020 til 1
jan 2023 er estimeret til 17.637.149 personår.

Til sidst beregner vi flytningsraten i perioden.

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output raw drawer  :exports both  :session *R* :cache yes
# Flytningsrate per personår
X/R
# Flytningsrate per 1000 personår
1000*X/R
#+END_SRC

: [1] 157.2281

Den inderdanske flytningsrate var 157.2 flytninger per 1000 personår i
perioden fra 1 januar 2020 til 1 januar 2023. Vi bemærker at vi har
brugt folketal fra den 1 januar 2023 i stedet for folketal fra den 31
december 2022. 

** Demografiske vækstrater

Vi kan anvende formlen for perioderater til mortalitetsrater
(begivenhed X er et dødsfald), fødselsrater (begivenhed X er en
fødsel), indvandringsrater (begivenhed X er en indvandring) og
udvandringsrater (begivenhed X er en udvandring). På den måde kan vi
beskrive en dekomposition af demografiske vækstrater.

Vi subtraherer \(N(t_1)\) fra begge sidder af den demografiske
ligevægtsligning og dividerer begge sidder med \(R[t_t,t_2]\). Det
giver følgende dekomposition af befolkningens vækstrate i perioden
\([t_1,t_2]\):

\begin{multline*}
\underbrace{\frac{N(t_2)-N(t_1)}{R[t_1,t_2]}}_{\text{Vækstrate}}=
\underbrace{\frac{F[t_1,t_2]}{R[t_1,t_2]}}_{\text{Fødselsrate}}
-
\underbrace{\frac{D[t_1,t_2]}{R[t_1,t_2]}}_{\text{Mortalitetsrate}}
\\
+
\underbrace{\frac{I[t_1,t_2]}{R[t_1,t_2]}}_{\text{Immigrationsrate}}
-
\underbrace{\frac{U[t_1,t_2]}{R[t_1,t_2]}}_{\text{Emigrationsrate}}
\end{multline*}

Vi bemærker at mortalitetsrater og udvandringsrater er
begivenhed/eksponering rater. Her giver udtrykket /risikotid/ mening,
fordi $R[t_1,t_2]$ stammer fra de personer som faktisk var under
risiko for hændelsen.

*** Eksempel

Vi beregner vækstrater i den danske befolkingen i perioden 1 januar
2022 til 1 januar 2023. Ud over samme data som vi har brugt i eksempel
for den demografiske ligevægtsligning, har vi nu brug for risikotid
for den danske befolkning i perioden. Vi anvender metode 2 for
middelfolketallet og beregner risikotid ved at gange med 1 år:

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output raw drawer  :exports both  :session *R* :cache yes  
N <- get_data("FOLK1a",
              list(list(code="tid",
                        values=c("2022K1","2023K1"))))[["INDHOLD"]]
vækst <- N[2]-N[1]
middelfolketal  <- mean(N)
risikotid <- middelfolketal*1
risikotid
#+END_SRC

: [1] 5903037

Risikotiden i den danske befolkning var 5903037 personår mellem 1
januar 2022 og 1 januar 2023.

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output raw drawer  :exports both  :session *R* :cache yes
# mortalitetsrate
D <- get_data("DOD",list(list(code="tid",values=2022)))[["INDHOLD"]]
Drate <- 1000*D/risikotid
# fødselsrate
F <- get_data("FOD",list(list(code="tid",values=2022)))[["INDHOLD"]]
Frate <- 1000*F/risikotid
# indvandringsrate
I <- get_data("INDVAN",list(list(code="tid",values=2022)))[["INDHOLD"]]
Irate <- 1000*I/risikotid
# udvandringsrate
U <- get_data("UDVAN",list(list(code="tid",values=2022)))[["INDHOLD"]]
Urate <- 1000*U/risikotid
# væksrate
Vrate <- 1000*vækst/risikotid
# naturlige væksrate
NaturVrate <- Frate-Drate
# nettovandringsrate
NettoVrate <- Irate-Urate
data.frame(X=c("Vækstrate",
               "Mortalitetsrate",
               "Fødselsrate",
               "Indvandringsrate",
               "Udvandringsrate",
               "Naturlige_vækst_rate",
               "Netto_vandrings_rate"),
           Rate=c(Vrate,Drate,Frate,Irate,Urate,NaturVrate,NettoVrate))
#+END_SRC

:                       X Rate    
: 1            Vækstrate 10.0344958
: 2       Mortalitetsrate 10.0685461
: 3          Fødselsrate  9.8982947
: 4      Indvandringsrate 20.5289243
: 5       Udvandringsrate 10.6601060
: 6 Naturlige_vækst_rate -0.1702513
: 7  Netto_vandrings_rate  9.8688184

I 2022, voksede den danske befolkning med 10,0 personer per 1000
personår. Den naturlige vækstrate var -0,2 personer per 1000 personår
og netto--vandringsraten var 9,9 personer per 1000 personår. Ligesom
den demografiske ligevægtsligning ikke går op, gør denne formel heller
ikke, og der er en fejlrate:

# silent
#+BEGIN_SRC R  :results output raw  :exports none  :session *R* :cache no  :eval always
1000*(59234  + 915 - 58256)/risikotid
10.03+0.17-9.87
#+END_SRC

#+begin_export latex
\begin{xalignat*}{2}
\underbrace{10,0}_{\text{Vækstrate}}&
=\underbrace{-0,2}_{\text{Naturlig vækstrate}} 
&+ \underbrace{9,9}_{\text{Nettovandringsrate}}+ \underbrace{0,3}_{\text{fejlrate}}.
\end{xalignat*}
#+end_export   



#+TITLE: Grundbegreber
#+LANGUAGE: dk
#+LaTeX_CLASS: danish-article
#+OPTIONS: toc:nil
#+LaTeX_HEADER:\usepackage{authblk}
#+LaTeX_HEADER:\usepackage{natbib}
#+LaTeX_HEADER:\usepackage{listings}
#+LaTeX_HEADER:\usepackage{color}
#+LaTeX_HEADER:\usepackage[usenames,dvipsnames]{xcolor}
#+LaTeX_HEADER:\usepackage[utf8]{inputenc}
#+LaTeX_HEADER:\usepackage{hyperref}
#+LaTeX_HEADER:\usepackage{amssymb}
#+LaTeX_HEADER:\usepackage{latexsym}
#+OPTIONS:   H:3  num:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:t todo:t pri:nil tags:not-in-toc author:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://publicifsv.sund.ku.dk/~tag/styles/all-purpose.css" />
