* HEADER                                                           :noexport:
#+TITLE: Modul 3: Livstabel og demografisk fortolkning
#+DATE: 
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:t todo:t pri:nil tags:not-in-toc author:nil
#+PROPERTY:= header-args :session *R* 
#+PROPERTY: header-args :cache no
#+superman-org-export-target: docx
#+ODT_STYLES_FILE: "~/metropolis/Teaching/demogRafi/holdundervisning/style/DemoStyle.xml"

* COMMENT word export                                              :noexport:

#+BEGIN_SRC  emacs-lisp :export code :eval never-export
(defun make-docx (&optional open-both)
  (interactive "p")
  (shell-command "killall openoffice")
  (superman-export-as-demografi-opgave open-both))
#+END_SRC

#+RESULTS:
: make-docx


* Holdundervisning :ignore:solution:

#+BEGIN_EXPORT odt
<text:p text:style-name="CourseCredentials">
Løsningsforslag
</text:p>
#+END_EXPORT


* Holdundervisning :ignore:nosolution:opgave:

#+BEGIN_EXPORT odt
<text:p text:style-name="CourseCredentials">
Demografi 3934-F26 <text:line-break/>
Folkesundhedsvidenskab, 2. semester
</text:p>
#+END_EXPORT

** Vejledning                                                        :opgave:ignore:
*** Vejledning 

/Den gode besvarelse er kort og præcis. Det er vigtigt at dine svar er klart struktureret og skrevet i fulde sætninger./
/Skriv dine svar i de udvidende svarfelter og udfyld tabeller/indsæt grafer./
/Du må ikke ændre tabellernes formatering og det er forbudt at sætte egne tabeller ind./
/Din besvarelse til hvert opgave bør ikke overskride 1/2 normalsides tekst svarende til maksimalt 1200 anslag med mindst 10pt skriftstørrelse f.eks., Courier New, men ikke medregnende tabeller o.a../

/Tal i resultaterne skal rundes af og enheder skal angives hvis relevant./
/R-koder som bruges til at besvare opgaverne findes i Rmd-filen på Absalon./

/Når du har besvaret alle opgaver, afleverer du denne fil i Absalon./


#+ODT: <text:p text:style-name="PageBreak"/>


** Baggrund                                                         :opgave:ignore:
*** Baggrund: Livslængde og dødelighed i Danmark

#+BEGIN_EXPORT odt
<text:p text:style-name="Baggrund">
I Danmark lever vi længere end nogensinde før. Ifølge den officielle
statistik fra Danmarks Statistik er den gennemsnitlige forventede
levetid ved fødsel for både mænd og kvinder omkring 80 år eller mere,
når man ser på de seneste perioder med tilgængelige tal. Dette
betyder, at et barn født i Danmark i dag i gennemsnit kan forvente at
blive omkring 80 år, hvis dødeligheden i populationen forbliver på det
nuværende niveau.

Bag denne høje middellevetid ligger en række samfundsmæssige
forbedringer, herunder bedre ernæring, sundhedspleje, forebyggelse og
kontrol af mange smitsomme sygdomme, som tidligere var hyppige
dødsårsager. Samtidig er sygdomsmønstret i Danmark ændret over tid mod
kroniske, ikke-smitsomme sygdomme, som bliver de dominerende årsager
til dødsfald. For eksempel udgør kræft og hjerte-kar-sygdomme en stor
andel af de samlede dødsårsager i befolkningen. Begge disse
sygdomsgrupper er tæt knyttet til livsstilsfaktorer som tobaksrygning,
kost, fysisk aktivitet og alkoholforbrug, og de har stor betydning for
både individuel og folkelig sundhed i befolkningen. 

Denne udvikling
betyder, at de demografiske mål og metoder, som livstabeller og
middellevetid, i stigende grad afspejler ændringer i aldersspecifik
dødelighed fra kroniske sygdomme fremfor akutte
infektionssygdomme. Forståelse af disse mønstre er derfor vigtig, når
man tolker dødelighed og overlevelse i en moderne befolkning.
</text:p>
#+END_EXPORT

#+ODT: <text:p text:style-name="PageBreak"/>

* Opgave 1

1. [@1] Angiv mindst en årsag til, hvorfor aldersspecifikke mortalitetsrater
   ikke var konstant de sidste 100 år i Danmark.
2. [@2] Beskriv mindst en grund til, hvorfor de Danske aldersspecifikke 
   mortalitetsrater ikke ville være konstant de næste 100 år.
3. [@3] Hvad er forskellen mellem en aldersspecifik dødsrate og en dødelighedssandsynlighed?
4. [@4] Hvorfor kan middellevetiden stige selv om de aldersspecifikke mortalitetsrater blandt ældre ikke ændrer sig?   

** Dine svar til opgave 1                                 :nosolution:nokode:ignore:
*** Dine svar til opgave 1.1

#+BEGIN_EXPORT odt
<text:p text:style-name="DineSvar">
<text:line-break/>
<text:line-break/>
<text:line-break/>
</text:p>
#+END_EXPORT

** Dine svar til opgave 1.2                               :nosolution:ignore:
*** Dine svar til opgave 1.2

#+BEGIN_EXPORT odt
<text:p text:style-name="DineSvar">
<text:line-break/>
<text:line-break/>
<text:line-break/>
</text:p>
#+END_EXPORT

** Dine svar til opgave 1.3                               :nosolution:ignore:
*** Dine svar til opgave 1.3

#+BEGIN_EXPORT odt
<text:p text:style-name="DineSvar">
<text:line-break/>
<text:line-break/>
<text:line-break/>
</text:p>
#+END_EXPORT

** Dine svar til opgave 1.4                               :nosolution:ignore:
*** Dine svar til opgave 1.4

#+BEGIN_EXPORT odt
<text:p text:style-name="DineSvar">
<text:line-break/>
<text:line-break/>
<text:line-break/>
</text:p>
#+END_EXPORT

** Løsningsforslag                             :solution:ignore:
*** Løsningsforslag                             opgave 1
**** Opgave 1.1

#+BEGIN_EXPORT odt
<text:p text:style-name="Loesningsforslag">
Aldersspecifikke mortalitetsrater har ikke været konstante de sidste 100 år i Danmark på grund af en række vigtigere samfundsmæssige og medicinske fremskridt. Et væsentligt eksempel er introduktionen og udbredelsen af penicillin og andre antibiotika i det 20. århundrede, som har reduceret dødeligheden fra infektioner betydeligt. Før antibiotika var infektionssygdomme som tuberkulose, lungebetændelse og sepsis almindelige dødsårsager, både hos børn og voksne. Samtidig har forbedringer i folkesundhed, som adgang til rent drikkevand, vaccinationsprogrammer og bedre fødselshjælp, ført til markant lavere dødelighedsrater, især blandt spædbørn og unge aldersgrupper.
</text:p>
#+END_EXPORT


**** Opgave 1.2

#+BEGIN_EXPORT odt
<text:p text:style-name="Loesningsforslag">
Krig og pandemier kan have en betydelig indvirkning på aldersspecifikke mortalitetsrater i de kommende århundreder. For eksempel kan fremtidige pandemier, som vi så med COVID-19, medføre en pludselig stigning i dødsrater for bestemte aldersgrupper, især ældre og kronisk syge. På samme måde kan krige føre til direkte tab af liv, men også indirekte forværre sundhedsforholdene gennem ødelæggelse af sundhedsinfrastruktur, fødevaremangel og spredning af sygdomme. Desuden kan faktorer som klimaforandringer og miljøforringelse, der påvirker levevilkår, føre til ændringer i dødelighedsmønstre. Øget migration som følge af klimaforandringer eller konflikter kan desuden påvirke befolkningssammensætningen og resultere i ændrede mortalitetsrater. Disse dynamiske faktorer gør det sandsynligt, at de aldersspecifikke dødelighedsrater vil fortsætte med at variere, og det er usandsynligt, at de forbliver konstante fremover.
</text:p>
#+END_EXPORT

**** Opgave 1.3

#+BEGIN_EXPORT odt
<text:p text:style-name="Loesningsforslag">
Aldersspecifik dødsrate og dødelighedssandsynlighed er beslægtede men forskellige mål:

Aldersspecifik dødsrate er antallet af dødsfald per personår i en specifik aldersgruppe. Den beregnes som antallet af dødsfald i aldersgruppen divideret med den samlede risikotid for samme gruppe.

Dødelighedssandsynlighed repræsenterer sandsynligheden for, at en person i en bestemt alder vil dø inden for en given tidsperiode.

Forskellen er, at dødsrate bruger en befolkningsgruppe i løbet af tiden som reference, mens dødelighedssandsynlighed er et direkte mål for risikoen for, at en enkelt person dør inden for et tidsrum.
</text:p>
#+END_EXPORT


**** Opgave 1.4


#+BEGIN_EXPORT odt
<text:p text:style-name="Loesningsforslag">
Middellevetiden kan stige, selvom dødeligheden blandt ældre ikke ændrer sig, fordi dødeligheden blandt yngre aldersgrupper falder. Hvis færre mennesker dør i en tidlig alder på grund af forbedringer i folkesundhed, medicinsk behandling, ernæring og levevilkår, øges den gennemsnitlige levetid for hele befolkningen. Denne udvikling påvirker middellevetiden proportionalt mere, selv hvis dødeligheden blandt ældre forbliver stabil.
</text:p>
#+END_EXPORT

#+ODT: <text:p text:style-name="PageBreak"/>

* Opgave 2

Beregn middellevetid for kvinder i Allerød kommune og i København
kommune i 2025. Svar på følgende spørgsmål til konstruktion af
overlevelsestavlen, udfyld nedenstående tabel, og rapporter
resultaterne i sammenhængende tekst.

1. [@1] Beskriv forskellen mellem \(l_x\) og \(L_x\).

Fortolk den forventede restlevetid af en 85-årig kvinde.

#+BEGIN_SRC R  :results output raw drawer  :exports results  :session *R* :cache no :eval always  
source("https://raw.githubusercontent.com/tagteam/demogRafi/main/R-scripts/demofunk.R")
a <- hent_mortalitetsrate_data(område = "allerød",tid = 2025,breaks = c(0,1,seq(5,95,10),Inf),køn = "Kvinder")
a <- mutate(a,
            M = Dod/R,
            k = c(1,4,rep(10,10)),
            a = c(0.1,rep(0.5,11)))
overlevelsestavle(a,mortalitet = "M")
b <- hent_mortalitetsrate_data(område = "københavn",
                               tid = 2025,
                               breaks = c(0,1,seq(5,95,10),Inf),
                               køn = "Kvinder")
b <- mutate(b,
            M = Dod/R,
            k = c(1,4,rep(10,10)),
            a = c(0.1,rep(0.5,11)))
Ok <- overlevelsestavle(b,mortalitet = "M")
#+END_SRC   

*** Tabel :opgave:nosolution:ignore: 
**** Tabel

Svar på følgende spørgsmål til konstruktion af overlevelsestavlen:

1. [@1] Forklar forskellen mellem \(d_x\) og \(D_x\).
2. [@2] Beskriv forskellen mellem \(l_x\) og \(L_x\).
3. [@3] Hvis \(l_x = 273\) og \(d_x = 17\), hvad er værdien af \(l_{x+1}\)?
4. [@4] Benyt formlerne \(l_{x+1} = l_x p_x\) og \(d_x = l_x q_x\) fra
   formelsamlingen til at vise, at \(l_{x+1} = l_x - d_x\). Substituér
   \(p_x\) med \((1 - q_x)\) i den første formel, og løs den anden
   formel for \(l_x\). Indsæt resultatet i den første formel og
   simplificér udtrykket.
5. [@5] Beregn dødshyppigheden i tabellens sidste aldersinterval,
   \(q_{x^{max}}\) og fortolk resultatet.

** Dine svar til opgave 2                          :nosolution:nokode:ignore:
*** Dine svar til opgave 2.1

#+BEGIN_EXPORT odt
<text:p text:style-name="DineSvar">
<text:line-break/>
<text:line-break/>
<text:line-break/>
</text:p>
#+END_EXPORT

** Dine svar til opgave 2.2                               :nosolution:ignore:
*** Dine svar til opgave 2.2

#+BEGIN_EXPORT odt
<text:p text:style-name="DineSvar">
<text:line-break/>
<text:line-break/>
<text:line-break/>
</text:p>
#+END_EXPORT

** Dine svar til opgave 2.3                               :nosolution:ignore:
*** Dine svar til opgave 2.3

#+BEGIN_EXPORT odt
<text:p text:style-name="DineSvar">
<text:line-break/>
<text:line-break/>
<text:line-break/>
</text:p>
#+END_EXPORT

** Dine svar til opgave 2.4                               :nosolution:ignore:
*** Dine svar til opgave 2.4

#+BEGIN_EXPORT odt
<text:p text:style-name="DineSvar">
<text:line-break/>
<text:line-break/>
<text:line-break/>
</text:p>
#+END_EXPORT

** Dine svar til opgave 2.5                               :nosolution:ignore:
*** Dine svar til opgave 2.5

#+BEGIN_EXPORT odt
<text:p text:style-name="DineSvar">
<text:line-break/>
<text:line-break/>
<text:line-break/>
</text:p>
#+END_EXPORT

** Løsningsforslag                             :solution:ignore:
*** Løsningsforslag                             opgave 1
**** opgave 2.1

#+BEGIN_EXPORT odt
<text:p text:style-name="Loesningsforslag">
\(D_x\) er antal døde i den rigtige befolkningen, \(d_x\) er antal døde i den hypotetiske tabelbefolkning.
</text:p>
#+END_EXPORT

**** opgave 2.2

#+BEGIN_EXPORT odt
<text:p text:style-name="Loesningsforslag">
Begge størrelser hører til den hypotetiske tabelbefolkning: \(l_x\) er antal personer i starten af alderstrin \(x\), og \(L_x\) er antal gennemlevede tid i intervallet fra alderstrin \(x\) til næste alderstrin.
</text:p>
#+END_EXPORT

**** opgave 2.3

#+BEGIN_EXPORT odt
<text:p text:style-name="Loesningsforslag">
I starten af alderstrin er der 273 personer. Der dør 17 personer i intervallet. Dermed er der 256 tilbage i starten af det næste aldersinterval.
</text:p>
#+END_EXPORT


**** opgave 2.4

#+BEGIN_EXPORT odt
<text:p text:style-name="Loesningsforslag">
\(l_xd_x/q_x\) og dermed \(l_{x+1}  d_x/q_x (1- q_x)  d_x/q_x -d_x  l_x- d_x\).
</text:p>
#+END_EXPORT

**** opgave 2.5

#+BEGIN_EXPORT odt
<text:p text:style-name="Loesningsforslag">
Resultatet er \(q_x^{max}=1\) uanset værdien af \(M_x\). Dødshyppigheden i det sidste aldersinterval er 100\%. Det betyder at den resterende del af tabelbefolkningen dør i det sidste aldersinterval.
</text:p>
#+END_EXPORT


#+ODT: <text:p text:style-name="PageBreak"/>

*** Opgave 3

3. [@3] Hvilket tal i forlæsningsnoterne angiver middellevetid for en
   nyfødt dreng i 2020 under den forudsætning at mortalitetsraterne
   fra 2008/2009 for alle grupperinger af køn og alderstrin holder sig
   på samme niveau i al fremtid? 
3. [@3] Under antagelsen at mortalitetsraterne ville følge samme kalendartidstrends 
   som de sidste 12 år (se diagram i forlæsningsnoterne) også de næste 
   100 år, ville den forventede restlevetid for en 4-årig dreng i 2009
   være mindre eller højere end 72,78 år (se forlæsningsnoterne)?

Middellevetiden for en nyfødt dreng i 2020, under antagelsen af at mortalitetsraterne fra 2008/2009 forbliver konstante, er 76,52 år. Dette tal repræsenterer den gennemsnitlige forventede levetid ved fødslen og beregnes på baggrund af de aldersspecifikke dødsrater for det givne år. Det betyder, at et nyfødt drengebarn, forudsat at de observerede dødsrater forbliver uændrede gennem hele livet, vil have en gennemsnitlig forventet levetid på 76,52 år.


4. [@4] Hvorfor er det forkert at fortolke =65,9= (se forlæsningsnoterne) som den 
   forventede tid, som en 11 årige dreng i 2008/2009 kan forvente at leve? 

Det er forkert at fortolke tallet 65,92 som den forventede restlevetid for en 11-årig dreng i 2008/2009, uden at tage forbehold for de underliggende antagelser. Dette tal er baseret på en livstabel, der forudsætter, at de dødsrater, der blev observeret i 2008/2009, forbliver konstante i al fremtid. I virkeligheden ændrer mortalitetsrater sig over tid som følge af forbedringer i sundhedspleje, levevilkår, forebyggelse af sygdomme og andre samfundsforhold. Derfor kan den reelle restlevetid for en 11-årig dreng variere betydeligt, hvis dødeligheden enten stiger eller falder over de kommende år. En korrekt fortolkning af 65,92 er derfor, at det repræsenterer den gennemsnitlige restlevetid under den strenge antagelse, at dødsraterne i 2008/2009 forbliver uændrede i fremtiden, hvilket sjældent er realistisk.
Den forventede restlevetid for en 4-årig dreng i 2009 ville være højere end 72,78 år, hvis mortalitetsraterne fortsætter med at følge de samme kalendertidsbaserede trends som de sidste 12 år. Dette skyldes, at kalendertidstrends typisk viser faldende dødelighed over tid som følge af medicinske fremskridt, forbedrede sundhedsvæsen og forebyggelse af sygdomme. Så hvis dødeligheden fortsætter med at falde i takt med historiske tendenser, vil det føre til en stigning i den forventede restlevetid på tværs af alle aldre, inklusive for en 4-årig dreng i 2009.
