
# Opgave 2


## Data fra statistikbankens register FOLK1a og FOD207

```{r   }
source("https://raw.githubusercontent.com/tagteam/demogRafi/main/R-scripts/demofunk.R")
# hent data i 10-års intervaller men separere det første år
København <- hent_mortalitetsrate_data(område = "København",
                                       tid = 2025,
                                       right = FALSE,
                                       breaks = c(0,1,10,seq(20,90,10),Inf),
                                       køn = "Kvinder")
# beregn aldersspecifikke mortalitetsrater
# tilføj intervallernes bredte k og Chiang's a
København <- mutate(København,
                    M = Dod/R,
                    k = c(1,9,rep(10,9)),
                    a = c(0.1,rep(0.5,10)))
# se resultatet
print(København) 
```


## Beregn overlevelsestavle

```{r   }
# beregn overlevelsestavlen
otavle_København <- overlevelsestavle(København,mortalitet = "M")
# se resultatet
print(otavle_København) 
```


# Opgave 3

```{r   }
# Brug copy-paste og erstat 'København' med 'Allerød'  
```


# Opgave 4


## Hent data

```{r   }
# hent risikotid (FOLK1A) og antal død (DOD) samt antal døde på grund af psykiske lidelser (DODA1)
psykdod <- hent_dodsaarsag_data(køn=c("Mænd","Kvinder"),
                                tid=2022,
                                årsag = "A06") %>% select(-c("ÅRSAG","TID"))
# data i wide format
psykdod <- pivot_wider(psykdod,names_from=KØN,
                       values_from=c("R","Dod","QDod"))
# se data
print(psykdod) 
```


## Standardiserede rater

```{r   }
# Beregn standardiserede rater
# 1. samle risikotid fra mænd og kvinder
psykdod <- psykdod %>% mutate(R_DK = R_Kvinder+R_Mænd)
# 2. beregn standardbefolkningens aldersfordeling af risikotid
psykdod <- psykdod %>% mutate(V_DK = R_DK/sum(R_DK))
# 3. beregn dødelighedsrater på grund af psykiske lidelser
psykdod <- psykdod %>% mutate(M_Kvinder_psykdod = QDod_Kvinder/R_Kvinder,
                              M_Mænd_psykdod = QDod_Mænd/R_Mænd)
# 4. beregn alderstandardiserede rater
# dine R-koder her 
```


## Årsagsspecifikke dødelighedstavler

```{r   }
# beregn andel død på grund af psykiske lidelser
psykdod <- psykdod %>% mutate(hQ_Kvinder = QDod_Kvinder/Dod_Kvinder,hQ_Mænd = QDod_Mænd/Dod_Mænd)
# tilføj intervallernes bredde samt Chiangs a
psykdod <- mutate(psykdod,a = c(0.1,2,rep(2.5,17)),k = c(1,4,rep(5,17)))
# beregn mortalitetsrater
psykdod <- mutate(psykdod, M_Kvinder = Dod_Kvinder/R_Kvinder,M_Mænd = Dod_Mænd/R_Mænd)
# beregn tavlen for kvinder
dtavle_kvinder <- dodsaarsagtavle(psykdod,mortalitet = "M_Kvinder",hQ = "hQ_Kvinder")
# beregn tavlen for mænd
dtavle_mænd <- dodsaarsagtavle(psykdod,mortalitet = "M_Mænd",hQ = "hQ_Mænd")
# se resultaterne for kvinder
dtavle_kvinder %>% select(Alder,l,L,d,dQ,e,LTR_Q,risiko_Q)
# se resultaterne for mænd
dtavle_kvinder %>% select(Alder,l,L,d,dQ,e,LTR_Q,risiko_Q) 
```

