* Introduktion

Overlevelsestavlen repræsenterer en matematisk model, der
kvantificeres ved hjælp af konkrete demografiske data. Modellen
genererer derefter en omfattende beskrivelse af dødelighedsforholdene
i den specifikke befolkning. De forskellige mål for dødelighed
konstrueres på baggrund af overlevelsestavlen. Dette gælder også for
målene vedrørende forekomsten af vielser, skilsmisser, folkevandringer og i
vis grad forskellige fertilitets- og
reproduktionsmål. Overlevelsestavlen kunne derfor gennemgås på en ret
abstrakt måde og fortolkes forskelligt, afhængigt af om den skal
anvendes til at beskrive dødelighed, vielser, skilsmisser eller
fertilitet. I det følgende vil vi dog fokusere på at opbygge modellen
omkring målingen af befolkningens dødelighed for at gøre det lettere
at forstå modellens umiddelbare anvendelighed.

** Middellevetid

Hvor mange år kan en nyfødt i dag forvente at leve? Dette spørgsmål er
umuligt at besvare korrekt, fordi svaret umiddelbart afhænger af, hvad der
sker i fremtiden. Alligevel er middellevetid, altså den forventede
gennemsnitlige levetid af en nyfødt, et demografisk værktøj som
anvendes hyppigt til belysning af befolkningens nuværende
dødelighedsniveau. Middellevetid bruges også som
sammenligningsgrundlag på tværs af befolkninger og tid. Tallet angiver
det gennemsnitlige antal år, som en nyfødt kan forvente at leve
/under den forudsætning/, at de nuværende mortalitetsrater for alle
grupperinger af køn og alderstrin holder sig på samme niveau i fremtiden.
Med middellevetiden har man et relativt simpelt begreb, som
gør det muligt at sammenligne forskellige befolkningers dødelighed. I
praksis vil de nuværende dødshyppigheder formentlig ikke holde sig på
et samme niveau i fremtiden.

Igennem mange år har der været en tendens til faldende
mortalitetsrater, og der er meget, som tyder på, at det er en
udvikling som fortsætter. Den konkrete fortolkning af middellevetiden
for 0-årige som det gennemsnitlige antal år, som en nyfødt kan
forventes at leve, vil derfor formentlig undervurdere den faktiske
middellevetid. Men formålet med middellevetiden er heller ikke at
forudsige præcist, hvor længe en nyfødt vil leve. Formålet er at have et
simpelt begreb, der kan sammenlignes på tværs af befolkninger og tid.
Figur ref:fig:k3-middellevetid viser udviklingen af middellevetid for
0-årige i Danmark siden 1840.

#+BEGIN_SRC R :results file graphics :file ./kapitel3/K3-udvikling-middellevetid.pdf :exports none :session *R* :cache yes
m <- hent_data("HISB7",tid = "all",køn = "all")
m <- mutate(m,kalender = as.numeric(sapply(strsplit(TID,":"),"[",1)))
g <- ggplot(m,aes(kalender,INDHOLD,colour = KØN,group = KØN))+geom_line()
g <- g+theme_wsj()+ scale_colour_wsj("colors6") + theme(axis.text.x = element_text(angle = -45))
g <- g+theme(axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)))
g <- g + theme(axis.title.x = element_text(margin = margin(t = 20, r = 0, b = 0, l = 0)))
g <- g+scale_x_continuous(breaks = seq(1840,2023,10))
g + ylab("Middellevetid for 0-årige (år)")+xlab("")
#+END_SRC

#+RESULTS[(2024-03-01 09:48:59) 906f5d7a78cc606c22b3cb67dfb5c43fd4eafa0a]:
[[file:./kapitel3/K3-udvikling-middellevetid.pdf]]

#+name: fig:k3-middellevetid
#+ATTR_LATEX: :width 0.9\textwidth
#+CAPTION: Udviklingen i middellevetid for 0-årige. Kilde: statistikbankens HISB7.
[[file:./K3-udvikling-middellevetid.pdf]]

** Andre dødelighedsmål

Middellevetiden er måske det vigtigste mål, som resulterer af
overlevelsestavlen. En overlevelsestavle beskriver også en række andre
dødelighedsmål, såsom den forventede restlevetid fra alder \(x\),
sandsynligheden for at dø inden alder \(x\) og sandsynligheden for at
være i live ved alder \(x\).
Figur ref:fig:k3-middellevetid viser middelrestlevetiden for
43-årige i Danmark siden 1981.


#+BEGIN_SRC R :results file graphics :file ./kapitel3/K3-udvikling-middelrestlevetid.pdf :exports none :session *R* :cache yes
m <- hent_data("HISB8",alder = 43,tavle = 3,tid = "all",køn = "all")
m <- mutate(m,kalender = as.numeric(sapply(strsplit(TID,":"),"[",1)))
g <- ggplot(m,aes(kalender,INDHOLD,colour = KØN,group = KØN))+geom_line()
g <- g+theme_economist()+ scale_colour_wsj("colors6") + theme(axis.text.x = element_text(angle = -45))
g <- g+theme(axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)))
g <- g + theme(axis.title.x = element_text(margin = margin(t = 20, r = 0, b = 0, l = 0)))
g <- g+scale_x_continuous(breaks = seq(1840,2023,10))
g + ylab("Middelrestlevetid for 43 årige (år)")+xlab("")
#+END_SRC

#+RESULTS[(2024-03-01 09:48:53) c9af3a242ea2c505b0f102edf2b3639b89c1af65]:
[[file:./kapitel3/K3-udvikling-middelrestlevetid.pdf]]

#+name: fig:k3-middelrestlevetid
#+ATTR_LATEX: :width 0.9\textwidth
#+CAPTION: Udviklingen i middelrestlevetid for 43-årige. Kilde: statistikbankens HISB8.
[[file:./K3-udvikling-middelrestlevetid.pdf]]

** Eksempel

Vi henter data fra statistikbankens register =FOLK1a= og =FOD207= og
beregner aldersspecifikke mortalitetsrater for kvinder i Danmark i 2019.
Vi inddeler i 12 aldersintervaller, hvor det første interval har
længde 1 år, det andet interval har længde 9 år, resten af intervallerne
har længde 10 år og det sidste aldersinterval er fra 90 til 125 år. 

#+ATTR_LATEX: :options otherkeywords={hent_mortalitetsrate_data,filter,mutate,overlevelsestavle}, deletekeywords={c,rep,print,seq,R}
#+BEGIN_SRC R  :results output :exports both  :session *R* :cache yes  
x <- hent_mortalitetsrate_data(tid = 2019,
                               breaks = c(0,1,10,seq(20,90,10),Inf),
                               køn = "kvinder",
                               right = FALSE,
                               alder = "all_no_total")
x <- mutate(x,M = Dod/R)
x
#+END_SRC

#+RESULTS[(2024-03-01 09:55:07) d2db9294abb52f41cc0c375dcce49f61db0a9cf1]:
#+begin_example
# A tibble: 11 × 6
   aldersinterval KØN       TID      R   Dod         M
   <fct>          <chr>   <dbl>  <dbl> <dbl>     <dbl>
 1 0              Kvinder  2019  29448    74 0.00251  
 2 1-9            Kvinder  2019 270111    24 0.0000889
 3 10-19          Kvinder  2019 332202    32 0.0000963
 4 20-29          Kvinder  2019 383578    73 0.000190 
 5 30-39          Kvinder  2019 336414   128 0.000380 
 6 40-49          Kvinder  2019 378914   342 0.000903 
 7 50-59          Kvinder  2019 397594  1160 0.00292  
 8 60-69          Kvinder  2019 336747  2855 0.00848  
 9 70-79          Kvinder  2019 293474  6016 0.0205   
10 80-89          Kvinder  2019 129929  8878 0.0683   
11 90+            Kvinder  2019  32094  6921 0.216
#+end_example

Med disse tal fra den rigtige befolkning konstruerer vi
overlevelsestavlen, som beskriver dødeligheden i en hypotetisk
befolkning, der bliver født i 2019 og lever hele deres ``liv'' igennem
alle alderstrin i 2019, hvor de bliver udsat for mortalitetsraterne
fra 2019.

#+ATTR_LATEX: :options otherkeywords={hent_mortalitetsrate_data,filter,mutate,overlevelsestavle}, deletekeywords={c,rep,print,seq,R}
#+BEGIN_SRC R  :results output :exports both  :session *R* :cache yes  
x <- mutate(x,a = c(0.1,4.5,rep(5,9)),k = c(1,9,rep(10,9)))
tavle_kvinder <- overlevelsestavle(x,
                                   mortalitet = "M",
                                   alder = "aldersinterval")
print(tavle_kvinder,digits = 2)
#+END_SRC

#+RESULTS[(2024-03-01 09:56:07) 05faec4af649b08c3f49cb5ab3d81b1e6fed6ab5]:
#+begin_example
# A tibble: 11 × 9
   Alder      l     d     p        q     o      L        T     e
   <fct>  <dbl> <dbl> <dbl>    <dbl> <dbl>  <dbl>    <dbl> <dbl>
 1 0     100000   251 0.997 0.00251  1      99774 8334430. 83.3 
 2 1-9    99749    80 0.999 0.000799 0.997 897385 8234656. 82.6 
 3 10-19  99670    96 0.999 0.000963 0.997 996216 7337271. 73.6 
 4 20-29  99574   189 0.998 0.00190  0.996 994789 6341056. 63.7 
 5 30-39  99384   377 0.996 0.00380  0.994 991955 5346266. 53.8 
 6 40-49  99007   890 0.991 0.00899  0.990 985620 4354311. 44.0 
 7 50-59  98117  2821 0.971 0.0288   0.981 967065 3368691. 34.3 
 8 60-69  95296  7751 0.919 0.0813   0.953 914204 2401626. 25.2 
 9 70-79  87545 16278 0.814 0.186    0.875 794062 1487422. 17.0 
10 80-89  71267 36296 0.491 0.509    0.713 531192  693360.  9.73
11 90+    34971 34971 0     1        0.350 162168  162168.  4.64
#+end_example


#+Label: tab:overlevelstavle-kolonner
#+CAPTION: Forklaring af kolonner i en overlevelsestavle
#+ATTR_LATEX: :align l|l
| Kolonne | Betydning                                                       |
|---------+-----------------------------------------------------------------|
| =Alder= | Aldersinterval                                                  |
| =l=     | Dekrementfunktion: Antal tabelpersoner i starten af intervallet |
| =d=     | Antal døde i intervallet                                        |
| =p=     | Sandsynlighed for at overleve i intervallet                     |
| =q=     | Dødshyppighed: sandsynlighed for at dø i intervallet            |
| =o=     | Sandsynlighed for at overleve indtil starten af intervallet     |
| =L=     | Samlet risikotid i intervallet                                  |
| =T=     | Samletlevetid fra starten af intervallet                       |
| =e=     | Middelrestlevetid (i første interval =  middellevetid)          |

Fra overlevelsestavlen aflæser vi af kolonne =e=: under antagelsen af, at
mortalitetsraterne i 2019 ikke ændrer sig i al fremtid vil man
forvente, at en nyfødt pige lever 88,3 år og at en kvinde som er 30 år
gammel kan forvente at leve 53,8 år.

* Konstruktion af overlevelsestavler

Overlevelsestavler beskriver, hvordan en tænkt lukket fødselskohorte
reduceres med stigende alder alene på grund af dødsfald. Fordi
kohorten er lukket, er død den eneste mulige afgang fra kohorten. Der
tages udgangspunkt i en fiktiv tabelbefolkning bestående af
\(\ell_0\) personer, som antages at være født på nøjagtig samme
tidspunkt. Antallet af fiktive tabelpersoner \(\ell_0\) kaldes for
`radix', og radix sættes typisk til $\ell_0=100.000$.

** Dekrementfunktionen

Funktionen \(\ell_x\) angiver hvor mange tabelpersoner stadigvæk er i
live ved alder \(x\) og beskriver hvordan tabelbefolkningen reduceres
på grund af dødsfald. Startværdien \(\ell_0\) angiver, hvor mange
tabelpersoner, der er i tabelbefolkningen helt i begyndelsen, hvor alder
er lig med \(0\), og \(\ell_{30}\) angiver hvor mange tabelpersoner
er i live ved alder \(30\). Fordi \(\ell_x\) er monotont faldende som
funktion af alder, det vil sige, at der gælder
\(\ell_x\ge\ell_{x+1}\), kalder man den for dekrementfunktionen. Af
tabellen kan man aflæse, hvor mange personer forventes at overleve til en 
bestemt alder. For eksempel betyder \(\ell_{30}=99.345\), at \(99.345\) personer ud af
\(\ell_0=100.000\) tabelpersoner stadigvæk er i
live ved alder \(30\). I dette eksempel er overlevelsessandsynligheden
i tabelbefolkningen ved alder \(30\) lig med
#+begin_export latex
\begin{equation*}
o(30)=\frac{\ell_{30}}{\ell_0} = \frac{99.345}{100.000} = 99,3\%,
\end{equation*}
#+end_export
eftersom overlevelsesfunktionen er defineret som
#+begin_export latex
\begin{equation*}
o_x=\frac{\ell_x}{\ell_0}. 
\end{equation*}
#+end_export
Under konstruktionen af overlevelsestavler er opgaven at beregne
dekrementfunktionens værdier \(\ell_x\) for alle alderstrin \(x=0,1,
\dots, x^{max}\) hvor \(x^{max}\) er det sidste alderstrin. Per
konstruktion dør alle resterende
tabelpersoner i det sidste alderstrin - det vil sige
\(\ell_{x^{max}+1}=0\) og dermed også \(o_{x^{max}+1}=0\). Vi vil forklare
hvorfor senere. 

** Dødshyppigheder

Dødshyppigheden \(\qxk\) beskriver for en person med eksakt alder
\(x\) sandsynligheden for at dø inden alderen
\(x+k\). Dødshyppigheder forbinder den ægte, åbne befolkning, som man
interesserer sig for, med den tænkte, lukkede tabelbefolkning, der
definerer overlevelsestavlen. Man beregner dødshyppigheder baseret på
aldersspecifikke mortalitetsrater, og den underliggende idé er, at
mortalitetsraterne er ens i den ægte befolkning og i tabelbefolkningen
for begge køn og alle alderstrin.

#+begin_export latex
\mybox{Bemærkning til notation:\\

Det er standardnotation i demografi at have indeks på begge
sidder af symbolet ligesom i \qxk. Her er indeks til højre 
startalderen og indeks til venstre er antal år som tælles med inklusive
startalderen. 
Det er lidt forvirrende, fordi
intervallet inkluderer startalderen \(x\):
\begin{center}
\begin{tabular}{lm{4em}rrl}
Symbol & Start & Længden & Slut & Betydning\\[0pt]
\hline
\({}_{1}D_{0}\) & 0 & 1 & 1 & Antal døde i alder \(0\)\\[0pt]
\({}_{4}D_{1}\) & 1 & 4 & 4 & Antal døde i alder 1, 2, 3, 4\\[0pt]
\({}_{5}D_{5}\) & 5 & 5 & 9 & Antal døde i alder 5, 6, 7, 8, 9\\[0pt]
\end{tabular}
\end{center}
Vi ændrer nu også notationen for de aldersspecifikke
mortalitetsrater. I Kapitel 2 har vi brugt \(M_x\) for mortalitetsraten
i det \(x\)-te aldersinterval.
Fra nu af bruger vi den mere præcise betegnelse
\(\Mxk\) for mortalitetsraten i det aldersinterval, som starter i alderen \(x\)
og slutter i alderen \(x+k\).
}
#+end_export

# | Symbol          | Startalder | Længden | Slutalder | Betydning              |
# |-----------------+------------+---------+-----------+------------------------|
# | \({}_{1}D_{0}\) |          0 |       1 |         1 | Antal døde i \([0,1)\) |
# | \({}_{4}D_{1}\) |          1 |       4 |         4 | Antal døde i \([1,4)\) |
# | \({}_{5}D_{5}\) |          5 |       5 |         9 | Antal døde i \([5,9)\) |

*** Approksimationsformlen

For at beregne dødssandsynligheder i den ægte befolkning vil man gerne
dividere antal dødsfald i en kalenderperiode med antal personer i
starten af perioden. Problemet er, at den ægte befolkning er /åben/:
Dødsfald bliver ikke registreret for personer som udvandrer i
perioden, og både udvandrere og indvandrere i perioden bidrager ikke med
risikotid til hele perioden. Ideen er derfor at tilnærme
dødshyppighederne baseret på mortalitetsrater. Aldersspecifikke
mortalitetsrater kan beregnes på de registrerede data, ved at dividere
antal dødsfald i befolkningen med risikotiden, hvor indvandrere og
udvandrere kun bidrager med den tid de har været i befolkningen (se
Kapitel 1 og 2). Nøglen til en tilnærmelse af dødshyppighederne
baseret på mortalitetsrater er følgende centrale formel for
overlevelsestavlen:

#+begin_export latex 
\begin{equation}\label{k3-dhyppig}
\qxk= \frac{k\cdot \Mxk}{1+(k-\a{k})\cdot \Mxk} 
\end{equation}
#+end_export

Formlen afhænger aldersspecifikke mortalitetsrater \Mxk, længden af
aldersintervallet \(k\) og også en konstant \(\a{k}\), som kaldes
Chiang's a. Konstanten \(\a{k}\) beskriver den gennemsnitlige levetid
i aldersintervallet for personer, der døde mellem alderen \(x\) og aldeen
\(x+k\). Dermed beskriver \((k-\a{k})\) den gennemsnitlige tid som en
person der døde i aldersintervallet var død.  Hvis vi for eksempel ser
på et aldersinterval mellem 70 og 79 år og en person døde i alder 74,
så har den person været i live i 4 år (70, 71, 72, 73) og død i 6
år (74, 75, 76, 77, 78, 79). En person som døde i alder 78 har været i
live i 8 år og død i 2 år, og så videre. Værdien af \({}_{10}a_{70}\)
skal afspejle det gennemsnitlige antal år, som personer der døde i
denne aldersgruppe, var i live. For de fleste intervaller vil man
antage at gennemsnittet ligger i midten, altså i eksemplet vil man
vælge \({}_{10}a_{70} = 5\).

*** Chiang's a
:PROPERTIES:
:CUSTOM_ID: chiang
:END:
For at beregne dødshyppigheder med den centrale formel
eqref:k3-dhyppig har vi brug for at specificere Chiang's a for alle
aldersintervaller. Chiang's a skal tilnærme det forventede antal år
levet i intervallet af en person, som dør i intervallet. Hvis Chiang's
a opfylder dette, kan vi tilnærme den samlede dødstid, som alle
personer der døde i aldersintervallet har været døde:
#+begin_export latex
\begin{equation*}
\begin{split}
\text{Samlede dødstid i aldersintervallet}&=(k- \a{k})\cdot\Dxk,\\
 k &= \text{Antal år i aldersintervallet}\\
 \Dxk &= \text{Antal døde i aldersintervallet}\\
 \a{k} &= \text{Gennemsnitlige antal dødsår i intervallet}\\
 \{x,x+1,\dots,x+k\} &= \text{År i intervallet}.
\end{split}
\end{equation*}
#+end_export
Hvis vi antager at dødstider er
lige fordelt i aldersintervallet, altså at det er lige sandsynligt at
dø i starten som det er at dø i slutningen af aldersintervallet, er
det rimeligt at vælge
#+begin_export latex
\begin{equation*}
\a{k} = \frac k 2.
\end{equation*}
#+end_export
Det første og sidste aldersinterval vil dog altid kræve særlige
værdier af \a{k}. I det første leveår er dødstiderne meget skævt
fordelt over året - de fleste dødstider inden 1-års fødselsdagen ligger
kort efter fødslen. Derfor sætter vi \(\a[0]{1}=0,1\). For det sidste
interval \(x^{max}\) vælger vi
#+begin_export latex
\begin{equation}\label{eq:amax}
\a[x^{max}]{\infty} =
\frac{1}{{}_\infty M_{x^{max}}}, 
\end{equation}
#+end_export
så dødshyppigheden i det sidste interval bliver 1, og det betyder, at
alle tabelpersoner dør i det sidste aldersinterval, dvs. \({}_\infty q_{x^{max}} = 1\).
ved formel eqref:k3-dhyppig. 

#+Label: tab-K3.1
#+CAPTION: Tabellen viser hvordan vi vælger Chiang's a for 1-års, 5-års og 10-års aldersintervaller.
#+ATTR_LATEX: :align l|l|l 
|                        | 5-års aldersintervaller                         | 10-års aldersintervaller                        |
|------------------------+-------------------------------------------------+-------------------------------------------------|
| Første leveår          | \(\a[0]{1}=0,1\)                                | \(\a[0]{1}=0,1\)                                |
| Aldersinterval 1-5 år  | \(\a[1]{4}= 4\cdot 0,5=2\)                      | \(\a[1]{9}= 9\cdot 0,5=4,5\)                    |
| Alle andre intervaller | \(\a[5]{k}=5\cdot 0,5\)=2,5                     | \(\a[10]{k}=10\cdot 0,5=5\)                     |
| Sidste aldersinterval  | \(a_{x^{max}}=\frac{1}{{}_\infty M_{x^{max}}}\) | \(a_{x^{max}}=\frac{1}{{}_\infty M_{x^{max}}}\) |

*** Forklaring af den centrale formel

I det følgende skal vi på en uformel måde forklare formel
eqref:k3-dhyppig. Hvis den ægte befolkning var lukket, altså uden
forekomst af ind- og udvandring, ville man kunne beregne
dødshyppighederne simpelt som antal dødsfald i aldersintervallet
divideret med antal personer i starten af aldersintervallet:
#+begin_export latex
\begin{equation*}
\text{Dødshyppighed} = \frac{\text{Antal dødsfald i aldersintervallet}}{\text{Antal personer i starten}}.
\end{equation*}
#+end_export
Hvis aldersintervallet er over \(k\) år gælder
#+begin_export latex
\begin{equation*}
\text{Antal personer i starten} = \frac{\text{Risikotid} + \text{Dødstid}}{k}.
\end{equation*}
#+end_export
Her er risikotiden det samlede antal år, som befolkningens personer har
levet (i aldersintervallet), og dødstiden er tilsvarende det samlede
antal år, som befolkningens personer var døde. Med denne formel kan
dødshyppigheden skrives som
#+begin_export latex
\begin{equation}\label{eq:k3-uformel}
\text{Dødshyppighed} = \frac{k\cdot \text{Antal dødsfald i aldersinterval}}{\text{Risikotid}+\text{Dødstid}}.
\end{equation}
#+end_export
Vi sætter Chiang's a sådan at
#+begin_export latex
\begin{equation*}
\text{Dødstid i aldersinterval}=(k- \a{k})\cdot\Dxk,
\end{equation*}
#+end_export
er en god tilnærmelse af den samlede dødstid, som alle personer der
døde i aldersintervallet har været døde (c.f., afsnit ref:chiang). Hvis
vi nu anvender formlen for den aldersspecifikke mortalitetsrate
fra Kapitel 2, 
#+begin_export latex
\begin{equation*}
\Mxk = \frac{\Dxk}{\Rxk},
\end{equation*}
#+end_export
ser vi at den centrale formel
eqref:k3-dhyppig faktisk er lig med formel eqref:eq:k3-uformel:
#+begin_export latex
\begin{align*}
\frac{k\cdot\Mxk}{1+(k-\a{k})\cdot \Mxk} &=\frac{k\cdot\frac{\Dxk}{\Rxk}}{1+(k-\a{k})\cdot \frac{\Dxk}{\Rxk}}\\
&=\frac{k\cdot\Dxk}{\Rxk\cdot(1+(k-\a{k})\cdot \frac{\Dxk}{\Rxk})}\\
&=\frac{k\cdot \Dxk}{\Rxk+(k-\a{k})\cdot \Dxk}.
\end{align*}
#+end_export

*** Beregningen af antal dødsfald og overlevelser

Vi fortsætter nu konstruktionen af overlevelsestavlen. Vi starter med
en radix af \(\ell_0\) tabelpersoner. For at beregne antal
tabelpersoner som overlever indtil det første alderstrin, \(x=1\),
skal vi beregne hvor mange tabelpersoner dør mellem alder \(x=0\) og
alder \(x=1\). For at beregne hvor mange tabelpersoner der overlever alder
\(x+k\) skal vi beregne hvor mange af de resterende \(\ell_x\)
tabelpersoner der dør i aldersintervallet. Vi betegner med \(\d{k}\) antal
tabelpersoner som dør mellem alder \(x\) og alder \(x+k\). Dermed er
\(\d{1}\) antal tabelpersoner som dør mellem alder \(x\) og alder
\(x+1\). Sandsynligheden for at dø mellem to alderstrin
(dødshyppighederne) er det centrale element ved konstruktionen af
overlevelsestavlen. Vi beregner antal dødsfald i aldersintervallet ved
at gange antal tabelpersoner i starten af intervallet med
dødshyppigheden:
#+begin_export latex
\begin{equation}\label{antaltabeldod}
\d{k} = \qxk\cdot\ell_x.
\end{equation}
#+end_export
Det er vigtig at skelne mellem antal døde \(\Dxk\) i den ægte
befolkning og antal døde \(\d{k}\) i tabelbefolkningen. Med formel
eqref:antaltabeldod er det en let sag at beregne, hvor mange
tabelpersoner er i live i starten af det næste aldersinterval:
#+begin_export latex
\begin{equation*}
\ell_{x+k}=\ell_{x} - \d{k}.
\end{equation*}
#+end_export
Alternativt kan vi starte med at beregne dekrementfunktionen baseret
på dødshyppigheden
#+begin_export latex
\begin{equation*}
\ell_{x+k}=\ell_{x}\cdot (1-q_x).
\end{equation*}
#+end_export
Bagefter er det simpelt at beregne antal dødsfald som
#+begin_export latex
\begin{equation*}
\d{k} = l_{x} - l_{x+k}.
\end{equation*}
#+end_export
Med disse formler kan vi konstruere overlevelsestavlen vigtigste
kolonner (\(\ell_0\) og \(\d{k}\)). Vi beskriver nu de vigtigste
dødelighedsmål som overlevelsestavlen viser.

*** Beregning af middelrestlevetid og middellevetid 

Vi betegner med \(\L{k}\) den samlede gennemlevede tid i
tabelbefolkningen i alderen mellem \(x\) og \(x+k\). Da dødsfald er
eneste afgangsårsag i tabelbefolkningen har vi
#+begin_export latex
\begin{align*}
\L{k} &= \text{bidrag fra overlevende + bidrag fra døde}\\
    &= k\cdot \ell_{x+k} + \a{k}\cdot \d{k}\\
    &= \a{k}\cdot\ell_x + (k- \a{k})\cdot \ell_{x+k}.
\end{align*}
#+end_export

Vi skal nu beregne den /forventede restlevetid/ for en \(x\)-årig
tabelperson. For en nyfødt er \(x=0\) og dermed bliver den forventede
middelrestlevetid til den forventede levetid, som betegnes med
/middellevetid/. Lad \(T_x\) angive den samlede levetid i
tabelbefolkningen efter \(x\)-års fødselsdagen, specielt er \(T_0\)
den samlede levetid i tabelbefolkningen. Vi beregner
#+begin_export latex
\begin{align*}
T_x &= \L{k} + \cdots + \L[x^{max}]{k}\\
    &= \a{k}\cdot\ell_x + (k- \a{k})\cdot \ell_{x+k} + \cdots + \a[x^{max}]{\infty}\cdot\ell_{x^{max}}.
\end{align*}
#+end_export
I tabelbefolkningen overlever \(\ell_x\) personer til deres \(x\)-års
fødselsdag, så den gennemsnitlige levetid efter \(x\)-års fødselsdagen
bliver
#+begin_export latex
\begin{equation}\label{eq:restlevetid}
e_x=\frac{T_x}{\ell_x} = \text{gennemsnitlige restlevetid}.
\end{equation}
#+end_export
Denne kvotient kaldes den forventede restlevetid eller
middelrestlevetid for en \(x\)-årig tabelperson. På tilsvarende vis
bliver middellevetid beregnet som
#+begin_export latex
\begin{equation}\label{eq:middellevetid}
e_0=\frac{T_0}{\ell_0} = \text{middellevetid}.
\end{equation}
#+end_export

*** Fortolkning

Når man fortolker middellevetid og middelrestlevetid er det vigtigt at huske
og fremhæve at beregningen bygger på en hypotetisk tabelbefolkning som
lever hele deres liv i en kort kalenderperiode. Danmarks Statistik
forklarer middelrestlevetiden sådan[fn:1]:

#+begin_export latex
\mybox{ Middelrestlevetiden er det gennemsnitlige antal år, som personer på en given
fødselsdag har tilbage at leve i, {\it hvis deres dødelighed fremover
(alder for alder) svarer til det niveau, som er konstateret i den
aktuelle periode}.}
#+end_export

[fn:1] https://www.dst.dk/da/Statistik/emner/borgere/befolkning/middellevetid

** Overlevelsestavle med 5-års intervaller

#+ATTR_LATEX: :options otherkeywords={hent_mortalitetsrate_data,filter,mutate,overlevelsestavle}, deletekeywords={c,rep,print,seq,R}
#+BEGIN_SRC R  :results output :exports both  :session *R* :cache yes  
x5 <- hent_mortalitetsrate_data(tid = 2019,
                                breaks = c(0,1,seq(5,95,5),Inf),
                                køn = "kvinder",
                                right = FALSE,
                                alder = "all_no_total")
x5 <- mutate(x5,M = Dod/R)
x5 <- mutate(x5,a = c(0.1,2,rep(2.5,19)),k = c(1,4,rep(5,19)))
tavle_kvinder_5 <- overlevelsestavle(x5,
                                     mortalitet = "M",
                                     alder = "aldersinterval")
print(tavle_kvinder_5,digits = 2,n = 100)
#+END_SRC

#+RESULTS[(2024-03-01 17:24:11) 75f0b77929bc9ca8e1687e834da0c63bfe4265db]:
#+begin_example
# A tibble: 21 × 9
   Alder      l     d     p        q     o      L        T     e
   <fct>  <dbl> <dbl> <dbl>    <dbl> <dbl>  <dbl>    <dbl> <dbl>
 1 0     100000   251 0.997 0.00251  1      99774 8338941. 83.4 
 2 1-4    99749    40 1.00  0.000402 0.997 398917 8239167. 82.6 
 3 5-9    99709    40 1.00  0.000398 0.997 498447 7840250. 78.6 
 4 10-14  99669    30 1.00  0.000303 0.997 498272 7341804. 73.7 
 5 15-19  99639    66 0.999 0.000658 0.996 498033 6843532. 68.7 
 6 20-24  99574    82 0.999 0.000823 0.996 497664 6345499. 63.7 
 7 25-29  99492   107 0.999 0.00108  0.995 497192 5847835. 58.8 
 8 30-34  99385   146 0.999 0.00147  0.994 496558 5350643. 53.8 
 9 35-39  99238   233 0.998 0.00235  0.992 495609 4854085. 48.9 
10 40-44  99005   322 0.997 0.00325  0.990 494219 4358476. 44.0 
11 45-49  98683   561 0.994 0.00568  0.987 492012 3864257. 39.2 
12 50-54  98122  1135 0.988 0.0116   0.981 487773 3372245. 34.4 
13 55-59  96987  1709 0.982 0.0176   0.970 480661 2884472. 29.7 
14 60-64  95278  3081 0.968 0.0323   0.953 468685 2403810. 25.2 
15 65-69  92196  4715 0.949 0.0511   0.922 449195 1935126. 21.0 
16 70-74  87482  6638 0.924 0.0759   0.875 420815 1485930. 17.0 
17 75-79  80844 10209 0.874 0.126    0.808 378699 1065115. 13.2 
18 80-84  70635 15912 0.775 0.225    0.706 313396  686417.  9.72
19 85-89  54723 21608 0.605 0.395    0.547 219597  373021.  6.82
20 90-94  33116 20382 0.385 0.615    0.331 114623  153424.  4.63
21 95+    12734 12734 0     1        0.127  38801   38801.  3.05
#+end_example

** Overlevelsestavle med 1-års intervaller

#+ATTR_LATEX: :options otherkeywords={hent_mortalitetsrate_data,filter,mutate,overlevelsestavle}, deletekeywords={c,rep,print,seq,R}
#+BEGIN_SRC R  :results output :exports both  :session *R* :cache yes  
x1 <- hent_mortalitetsrate_data(tid = 2019,
                               breaks = c(0:99,Inf),
                               køn = "kvinder",
                               right = FALSE,
                               alder = "all_no_total")
x1 <- mutate(x1,M = Dod/R)
x1 <- mutate(x1,a = c(0.1,rep(1,99)),k = rep(1,100))
tavle_kvinder_1 <- overlevelsestavle(x1,
                                     mortalitet = "M",
                                     alder = "aldersinterval")
print(tavle_kvinder_1,digits = 2,n = 100)
#+END_SRC

#+RESULTS[(2024-03-01 17:07:28) ba3872788bb743aa848d97b5cb01a4d38062ef1a]:
#+begin_example
# A tibble: 100 × 9
    Alder      l     d     p         q      o     L        T     e
    <fct>  <dbl> <dbl> <dbl>     <dbl>  <dbl> <dbl>    <dbl> <dbl>
  1 0     100000   251 0.997 0.00251   1      99774 8365844. 83.7 
  2 1-1    99749    16 1.00  0.000164  0.997  99749 8266069. 82.9 
  3 2-2    99733     7 1.00  0.0000658 0.997  99733 8166320. 81.9 
  4 3-3    99726     7 1.00  0.0000671 0.997  99726 8066587. 80.9 
  5 4-4    99720    10 1.00  0.000105  0.997  99720 7966861. 79.9 
  6 5-5    99709    14 1.00  0.000142  0.997  99709 7867141. 78.9 
  7 6-6    99695     3 1.00  0.0000343 0.997  99695 7767432. 77.9 
  8 7-7    99692    10 1.00  0.000101  0.997  99692 7667737. 76.9 
  9 8-8    99682     6 1.00  0.0000638 0.997  99682 7568045. 75.9 
 10 9-9    99675     6 1.00  0.0000619 0.997  99675 7468364. 74.9 
 11 10-10  99669     3 1.00  0.0000304 0.997  99669 7368688. 73.9 
 12 11-11  99666     3 1.00  0.0000300 0.997  99666 7269019. 72.9 
 13 12-12  99663     9 1.00  0.0000915 0.997  99663 7169353. 71.9 
 14 13-13  99654     9 1.00  0.0000906 0.997  99654 7069690. 70.9 
 15 14-14  99645     6 1.00  0.0000607 0.996  99645 6970036. 69.9 
 16 15-15  99639    24 1.00  0.000241  0.996  99639 6870391. 69.0 
 17 16-16  99615     3 1.00  0.0000308 0.996  99615 6770752. 68.0 
 18 17-17  99612     9 1.00  0.0000907 0.996  99612 6671138. 67.0 
 19 18-18  99603     9 1.00  0.0000886 0.996  99603 6571526. 66.0 
 20 19-19  99594    20 1.00  0.000203  0.996  99594 6471923. 65.0 
 21 20-20  99574    17 1.00  0.000169  0.996  99574 6372329. 64.0 
 22 21-21  99557    14 1.00  0.000139  0.996  99557 6272755. 63.0 
 23 22-22  99543    16 1.00  0.000158  0.995  99543 6173198. 62.0 
 24 23-23  99527    16 1.00  0.000156  0.995  99527 6073655. 61.0 
 25 24-24  99512    20 1.00  0.000198  0.995  99512 5974128. 60.0 
 26 25-25  99492    20 1.00  0.000201  0.995  99492 5874616. 59.0 
 27 26-26  99472    28 1.00  0.000277  0.995  99472 5775124. 58.1 
 28 27-27  99445    15 1.00  0.000154  0.994  99445 5675652. 57.1 
 29 28-28  99429    23 1.00  0.000232  0.994  99429 5576207. 56.1 
 30 29-29  99406    21 1.00  0.000211  0.994  99406 5476778. 55.1 
 31 30-30  99385    16 1.00  0.000163  0.994  99385 5377372. 54.1 
 32 31-31  99369    39 1.00  0.000397  0.994  99369 5277987. 53.1 
 33 32-32  99330    29 1.00  0.000290  0.993  99330 5178618. 52.1 
 34 33-33  99301    26 1.00  0.000266  0.993  99301 5079288. 51.2 
 35 34-34  99274    36 1.00  0.000367  0.993  99274 4979987. 50.2 
 36 35-35  99238    46 1.00  0.000467  0.992  99238 4880713. 49.2 
 37 36-36  99191    41 1.00  0.000413  0.992  99191 4781475. 48.2 
 38 37-37  99151    21 1.00  0.000214  0.992  99151 4682284. 47.2 
 39 38-38  99129    88 0.999 0.000887  0.991  99129 4583133. 46.2 
 40 39-39  99041    37 1.00  0.000377  0.990  99041 4484004. 45.3 
 41 40-40  99004    51 0.999 0.000513  0.990  99004 4384963. 44.3 
 42 41-41  98953    39 1.00  0.000395  0.990  98953 4285959. 43.3 
 43 42-42  98914    73 0.999 0.000734  0.989  98914 4187005. 42.3 
 44 43-43  98842    80 0.999 0.000805  0.988  98842 4088091. 41.4 
 45 44-44  98762    77 0.999 0.000784  0.988  98762 3989250. 40.4 
 46 45-45  98685   115 0.999 0.00117   0.987  98685 3890488. 39.4 
 47 46-46  98569    60 0.999 0.000609  0.986  98569 3791803. 38.5 
 48 47-47  98509   131 0.999 0.00133   0.985  98509 3693233. 37.5 
 49 48-48  98379   123 0.999 0.00125   0.984  98379 3594724. 36.5 
 50 49-49  98256   133 0.999 0.00135   0.983  98256 3496345. 35.6 
 51 50-50  98123   169 0.998 0.00172   0.981  98123 3398089. 34.6 
 52 51-51  97954   163 0.998 0.00167   0.980  97954 3299966. 33.7 
 53 52-52  97791   251 0.997 0.00257   0.978  97791 3202012. 32.7 
 54 53-53  97540   263 0.997 0.00269   0.975  97540 3104221. 31.8 
 55 54-54  97277   280 0.997 0.00288   0.973  97277 3006681. 30.9 
 56 55-55  96997   249 0.997 0.00256   0.970  96997 2909404. 30.0 
 57 56-56  96748   297 0.997 0.00307   0.967  96748 2812407. 29.1 
 58 57-57  96452   349 0.996 0.00362   0.965  96452 2715658. 28.2 
 59 58-58  96103   374 0.996 0.00389   0.961  96103 2619207. 27.3 
 60 59-59  95729   461 0.995 0.00481   0.957  95729 2523104. 26.4 
 61 60-60  95268   472 0.995 0.00496   0.953  95268 2427375. 25.5 
 62 61-61  94796   601 0.994 0.00634   0.948  94796 2332107. 24.6 
 63 62-62  94195   613 0.993 0.00651   0.942  94195 2237311. 23.8 
 64 63-63  93582   662 0.993 0.00708   0.936  93582 2143116. 22.9 
 65 64-64  92920   749 0.992 0.00806   0.929  92920 2049533. 22.1 
 66 65-65  92171   826 0.991 0.00897   0.922  92171 1956613. 21.2 
 67 66-66  91344   877 0.990 0.00960   0.913  91344 1864443. 20.4 
 68 67-67  90467   991 0.989 0.0109    0.905  90467 1773098. 19.6 
 69 68-68  89477  1036 0.988 0.0116    0.895  89477 1682631. 18.8 
 70 69-69  88441  1014 0.989 0.0115    0.884  88441 1593154. 18.0 
 71 70-70  87427  1119 0.987 0.0128    0.874  87427 1504713. 17.2 
 72 71-71  86307  1144 0.987 0.0133    0.863  86307 1417287. 16.4 
 73 72-72  85163  1338 0.984 0.0157    0.852  85163 1330979. 15.6 
 74 73-73  83824  1466 0.983 0.0175    0.838  83824 1245816. 14.9 
 75 74-74  82359  1614 0.980 0.0196    0.824  82359 1161992. 14.1 
 76 75-75  80744  1877 0.977 0.0232    0.807  80744 1079633. 13.4 
 77 76-76  78867  1950 0.975 0.0247    0.789  78867  998889. 12.7 
 78 77-77  76918  1990 0.974 0.0259    0.769  76918  920022. 12.0 
 79 78-78  74928  2252 0.970 0.0301    0.749  74928  843104. 11.3 
 80 79-79  72675  2423 0.967 0.0333    0.727  72675  768176. 10.6 
 81 80-80  70252  2742 0.961 0.0390    0.703  70252  695501.  9.90
 82 81-81  67510  2930 0.957 0.0434    0.675  67510  625249.  9.26
 83 82-82  64580  3294 0.949 0.0510    0.646  64580  557740.  8.64
 84 83-83  61286  3610 0.941 0.0589    0.613  61286  493160.  8.05
 85 84-84  57676  3937 0.932 0.0683    0.577  57676  431874.  7.49
 86 85-85  53739  4027 0.925 0.0749    0.537  53739  374198.  6.96
 87 86-86  49712  4573 0.908 0.0920    0.497  49712  320459.  6.45
 88 87-87  45139  4391 0.903 0.0973    0.451  45139  270748.  6.00
 89 88-88  40748  4777 0.883 0.117     0.407  40748  225609.  5.54
 90 89-89  35972  4528 0.874 0.126     0.360  35972  184860.  5.14
 91 90-90  31444  4570 0.855 0.145     0.314  31444  148889.  4.74
 92 91-91  26874  4388 0.837 0.163     0.269  26874  117445.  4.37
 93 92-92  22486  4181 0.814 0.186     0.225  22486   90571.  4.03
 94 93-93  18305  3598 0.803 0.197     0.183  18305   68085.  3.72
 95 94-94  14707  3442 0.766 0.234     0.147  14707   49781.  3.38
 96 95-95  11264  3005 0.733 0.267     0.113  11264   35074.  3.11
 97 96-96   8259  2387 0.711 0.289     0.0826  8259   23810.  2.88
 98 97-97   5873  1776 0.698 0.302     0.0587  5873   15550.  2.65
 99 98-98   4097  1506 0.632 0.368     0.0410  4097    9678.  2.36
100 99+     2591  2591 0     1         0.0259  5580    5580.  2.15
#+end_example


** Danmark statistik

Danmark statistik offentliggør egne beregninger af middellevetiden og
middelrestlevetiden.[fn:3] I dette afsnit forklarer vi hvordan Danmark
Statistiks beregninger bliver mere præcise fordi de bruger datoer for
fødsler, dødsfald og folkevandringer. [fn:4]

Med etableringen af den personstatistiske database har Danmarks
Statistik fået nye muligheder for at beregne dødshyppighederne mere
korrekt, idet databasen for alle personer i Danmark indeholder eksakt
information om eventuel dødsdato og ind- og udvandringsdatoer. Der
kan således for hver enkelt person udregnes nøjagtigt, hvor mange dage
personen i en årsperiode har været i Danmark og hvor mange af dagene i
årsperioden, personen har været død. Den søgte dødshyppighed skal
præcist angive sandsynligheden for at dø i et bestemt alderstrin, 
dvs. mellem to fødselsdage. For at opnå denne hyppighed laves
der en særlig beregning for hver enkelt person fra fødselsdag til
fødselsdag i en periode, der omfatter to kalenderår. I
offentliggørelsen af middellevetid fra 19. marts 2010 er det
kalenderårene 2008 og 2009, der ligger til grund for
beregningerne. For alle personer, der var i den danske befolkning på
et eller andet tidspunkt mellem deres fødselsdag i 2008 og i 2009, er
der lavet en beregning for antallet af dage, personen var i Danmark og
antallet af dage personen var død i perioden mellem de to
fødselsdage. For personer, der ikke dør mellem to fødselsdage, vil
antallet af dage som død naturligvis være 0.  Efterfølgende laves der
en sammenlægning for personer med samme køn og alderstrin for at få
det samlede antal levedage og dødsdage. Personer vil placeres på det
alderstrin, som svarer til det antal år, de fyldte i startåret,
hvilket i eksemplet vil sige 2008. En person, som fyldte 60 år 1. januar 2008 vil f.eks. tilhøre de
60-årige. Det samme vil en person, der fyldte 60 år 31. december 2008.
Der kan altså i yderste konsekvens være næsten et års forskel mellem
den periode, som personer på samme alderstrin følges.

[fn:3] https://www.dst.dk/da/Statistik/emner/borgere/befolkning/middellevetid.
[fn:4] https://www.dst.dk/ext/36380110073/0/befolkning/Hvordan-beregner-vi-middellevetid?--pdf

** Header :noexport:

#+TITLE: Overlevelsestavler
#+AUTHOR: Anna-Vera Jørring Pallesen, Johan Sebastian Ohlendorff, Laust Hvas Mortensen and Thomas Alexander Gerds
#+DATE: 
#+LaTeX_CLASS: danish-article
#+OPTIONS: toc:nil
#+LaTeX_HEADER:\usepackage{authblk}
#+LaTeX_HEADER:\usepackage{natbib}
#+LaTeX_HEADER:\usepackage{listings}
#+LaTeX_HEADER:\usepackage{color}
#+LaTeX_HEADER:\usepackage[usenames,dvipsnames]{xcolor}
#+LaTeX_HEADER:\usepackage[utf8]{inputenc}
#+LaTeX_HEADER:\usepackage{hyperref}
#+LaTeX_HEADER:\usepackage{amssymb}
#+LaTeX_HEADER:\usepackage{latexsym}
#+LaTeX_HEADER:\usepackage{fancyhdr}
#+LaTeX_HEADER:\usepackage[english,danish]{babel}
#+LaTeX_HEADER:\pagestyle{fancy}
#+LaTeX_HEADER:\lhead{Folkesundhedsvidenskab 2. semester, K{\o}benhavns Universitet}
#+LaTeX_HEADER:\rhead{Demografi}
#+LaTeX_HEADER:\renewcommand\theequation{K3.\arabic{equation}}
#+OPTIONS:   H:3  num:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:t todo:t pri:nil tags:not-in-toc author:t
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://publicifsv.sund.ku.dk/~tag/styles/all-purpose.css" />
#+LATEX_HEADER: \RequirePackage{tcolorbox}
#+LATEX_HEADER: \hyphenation{alders-speci-fik-ke}
#+LATEX_HEADER: \hyphenation{be-folk-ning}
#+LATEX_HEADER: \hyphenation{ta-bel-be-folk-ning}
#+LATEX_HEADER: \hyphenation{re-gist-re-ret}
# #+LaTeX_HEADER:\usepackage[table,usenames,dvipsnames]{xcolor}
#+LaTeX_HEADER:\definecolor{lightGray}{gray}{0.98}
#+LaTeX_HEADER:\definecolor{medioGray}{gray}{0.83}
#+LATEX_HEADER:\definecolor{mygray}{rgb}{.95, 0.95, 0.95}
#+Latex_Header: \newcommand{\qxk}{\ensuremath{{}_{k}q_{x}}}
#+Latex_Header: \newcommand{\dxk}{\ensuremath{{}_{k}d_{x}}}
#+Latex_Header: \newcommand{\qxe}[1][x]{\ensuremath{{}_{1}q_{#1}}}
#+Latex_Header: \newcommand{\Dxk}[1][x]{\ensuremath{{}_{k}D_{#1}}}
#+Latex_Header: \renewcommand{\d}[2][x]{\ensuremath{{}_{#2}d_{#1}}}
#+Latex_Header: \newcommand{\qxf}[1][x]{\ensuremath{{}_{5}q_{#1}}}
#+Latex_Header: \newcommand{\Mxf}[1][x]{\ensuremath{{}_{5}M_{#1}}}
#+Latex_Header: \newcommand{\Mxk}[1][x]{\ensuremath{{}_{k}M_{#1}}}
#+Latex_Header: \newcommand{\Rxk}[1][x]{\ensuremath{{}_{k}R_{#1}}}
#+Latex_Header: \renewcommand{\a}[2][x]{\ensuremath{{}_{#2}a_{#1}}}
#+Latex_Header: \renewcommand{\L}[2][x]{\ensuremath{{}_{#2}L_{#1}}}
#+LATEX_HEADER:\newcommand{\mybox}[1]{\vspace{.5em}\begin{tcolorbox}[boxrule=0pt,colback=mygray] #1 \end{tcolorbox}}
