* Overlevelsestavle

** Generel matematisk model

Overlevelsestavlen repræsenterer en matematisk model, der
kvantificeres ved hjælp af konkrete demografiske data. Modellen
genererer derefter en omfattende beskrivelse af dødelighedsforholdene
i den specifikke befolkning. De forskellige mål for dødelighed
konstrueres på baggrund af overlevelsestavlen. Dette gælder også for
målene vedrørende forekomsten af vielser, skilsmisser, vandringer og i
vis grad forskellige fertilitets- og
reproduktionsmål. Overlevelsestavlen kunne derfor gennemgås på en
abstrakt måde og fortolkes forskelligt, afhængigt af om den skal
anvendes til at beskrive dødelighed, vielser, skilsmisser eller
fertilitet. I det følgende vil vi dog fokusere på at opbygge modellen
omkring målingen af befolkningens dødelighed for at gøre det lettere
at forstå modellens umiddelbare anvendelighed.

** Middellevetid

Hvor mange år kan en nyfødt i dag forvente at leve? Dette spørgsmål er
ret umuligt at besvare fordi svaret afhænger hvad der sker i
fremtiden. Alligevel er middellevetid et demografisk værktøj som
anvendes hyppigt til belysning af befolkningens
sundhedstilstand. Tallet angiver det gennemsnitlige antal år, som en
nyfødt kan forventes at leve under den forudsætning, at de nuværende
mortalitetsrater for alle grupperinger af køn og alderstrin holder sig
på det samme niveau i al fremtid. Med middellevetiden har man et
relativt simpelt begreb, som gør det muligt at sammenligne forskellige
befolkningers dødelighed. I praksis vil de nuværende dødshyppigheder
naturligvis ikke holde sig på et konstant niveau i al fremtid.

I gennem mange år har der været en tendens til faldende
mortalitetsrater, og der er meget, som tyder på, at det er en
udvikling, som fortsætter. Den konkrete fortolkning af middellevetiden
for 0-årige som det gennemsnitlige antal år, som en nyfødt kan
forventes at leve, vil derfor formentlig undervurdere den faktiske
middellevetid. Men formålet med middellevetiden er heller ikke at
forudsige præcist, hvor længe nyfødte vil leve. Formålet er at have et
simpelt begreb, der kan sammenlignes på tværs af befolkninger og tid.


** Andre dødelighedsmål

Middellevetiden er et mål som resulterer fra den såkaldte
overlevelsestavle. En basal overlevelsestavle beskriver også en række
andre dødelighedsmål, såsom den forventede restlevetid fra alder
\(x\), sandsynligheden for at dø inden alder \(x\) og sandsynligheden
for at være i live ved alder \(x\).

** Konstruktion

Overlevelsestavler beskriver hvordan en tænkt lukket fødselskohorte
reduceres med stigende alder alene på grund af dødsfald. Fordi
kohorten er lukket er død den eneste mulige afgang fra kohorten. Der
tages udgangspunkt i en fiktiv tabelbefolkning bestående af
\(\ell(0)\) personer, som antages at være født på nøjagtig samme
tidspunkt. Antal fiktive tabelpersoner \(\ell(0)\) kaldes for `radix'
og den sættes typisk til $\ell(0)=100.000$. Her er \(\ell(x)\) en
funktion af alder \(x\) som angiver hvor mange tabelpersoner er
stadigvæk i live ved alder \(x\). Dermed angiver \(\ell(0)\) hvor
mange tabelpersoner der er i tabelbefolkningen helt i begyndelsen hvor
alder er lige med \(0\). Efterfølgende beregner man \(\ell(x)\) for
alderstrin \(x=1, 2, 3, \dots, x_max\) hvor \(x_{max}\) er det
alderstrin hvor alle tabelpersoner dør. 


Sandsynligheden for at dø mellem to alderstrin (dødshyppighederne) er
det centrale element ved konstruktionen af dødelighedstavler. For både
mænd og kvinder skal der for alle enkelte alderstrin udregnes
dødshyppigheder for at man kan lave beregningen af middellevetid.

** Approximationsformler

Oplysningerne om dødedage bruges også til at beregne den
gennemsnitlige tid, som en person, der døde, var død mellem de to
fødselsdage. Her omregnes dødedage først til år ved at dividere med
365, hvorefter der divideres med antallet af døde. For de 0- årige
drenge svarer de 44.656 dødedage fx til 122,34 dødeår. Ved at dividere
de 122,34 dødeår med de 136 døde 0-årige drenge får man, at de 0-årige
drenge, der døde mellem deres fødselsdag i 2008 og 2009, i gennemsnit
var døde 0,90 år. At tallet er tæt på 1 indikerer, at de 0-årige, der
dør, meget ofte dør kort tid efter fødslen.  Falder dødsfaldene
ligeligt fordelt mellem to fødselsdage vil det give et gennemsnitligt
antal dødeår på 0,5. De 0-årige er et særtilfælde, og for de øvrige
alderstrin med et forholdsvis stort antal døde, vil det gennemsnitlige
antal dødeår ligge tæt på 0,5. For alderstrin med meget få døde kan
der være store fluktuationer i det gennemsnitlige antal dødeår,
hvilket dog netop pga. det lave antal døde stort set ikke har nogen
betydning for de beregnede middellevetider.  Dødelighedstavler
Oplysningerne om dødshyppigheder og det gennemsnitlige antal dødeår
for alle grupperinger af køn og alderstrin er de grundlæggende
informationer, der er brug for i forbindelse med konstruktionen af
dødelighedstavler. Målene for middellevetid er en del af
dødelighedstavlerne.  I dødelighedstavlerne tages der udgangspunkt i
en fiktiv befolkning på 100.000 personer, som alle antages at være
født på nøjagtig samme tidspunkt. Ud fra de alders- fordelte
dødshyppigheder kan de korresponderende overlevelseshyppigheder
beregnes, og man kan derved udregne, hvor mange af de 100.000 fra
startbefolkningen, der er tilbage ved begyndelsen af hvert
alderstrin. Det udregnes også hvor mange personår, som der i alt
gennemleves fra alderstrin til alderstrin. Der anvendes en række
forskellige bogstavbetegnelser i dødelighedstavlerne, som nedenfor er
defineret, hvor x angiver alderstrin. Alle beregninger laves separat
for både mænd og kvinder.  q x = sandsynlighed for at dø mellem
alderstrin x og alderstrin x+1 (dødshyppighed). Denne sandsynlighed er
beregnet uden for dødelighedstavlen som beskrevet ovenfor.


p x = 1 - q x = sandsynlighed for at overleve fra alderstrin x til
starten af alderstrin x+1 l x +1 = l x × p x = antal personer, som ved
begyndelsen af alderstrinnet x+1 er tilbage i befolkningen.  l0 =
100.000 l1 = 100.000 × p0 l2 = l1 × p1 og tilsvarende for alle øvrige
alderstrin.  d x = l x × q x = antallet af døde mellem alderstrin x og
x+1. Der er tale om et antal døde beregnet særligt til
dødelighedstavlen med startbefolkningen på 100.000 0-årige, og det har
derfor ikke noget med det faktiske antal døde i et givent år at gøre.
dyearx = det gennemsnitlige antal dødeår i tidsrummet mellem
alderstrinene x og x+1 for personer, der døde mellem alderstrin x og
x+1. Variablen er ligesom q x beregnet uden for
dødelighedstavlen. Metoden er beskrevet ovenfor i eksemplet med
0-årige drenge, der fik beregnet et gennemsnitligt antal dødeår på
0,90.  Lx = l x  - d x × dyearx = antallet af personår gennemlevet
mellem starten af alderstrin x og starten af alderstrin x+1. Der
tages her hensyn til både antallet af døde og

hvor længe de døde i gennemsnit var døde i året. Lx udregnes som
alderstrinets startbefolkning fratrukket den tid (målt i personår) som
personer, der døde på alderstrinet, var døde i året. Lx svarer også
til det antal personer på alderstrin x, der i gennemsnit var til stede
mellem alderstrinene x og x+1. Lx er mindre end l x , hvis der er
mindst ét dødsfald på alderstrin x. Lx er til gengæld større end l x+1
, hvis der er mindst ét dødsfald på alderstrin x, da den tid, som de
døde lever på alderstrin x, også tæller med i den gennemlevede tid,
mens de døde i sagens natur ikke er blandt næste alderstrins
overlevende. Hvis dødsfald på et alderstrin er jævnt fordelt over
året, er l +l Lx = x x+1 en god approximation, og det er den formel,
der tidligere har været 2 anvendt. Med den nye metode, der udregner
dødedage præcist, er approximationen ikke nødvendig.  

akkumulerede antal personår gennemlevet fra starten af t
=0 alderstrin x til og med sidste alderstrin i dødelighedstavlen. Når
x er 0, svarer T til alle de personår, som udgangspopulationen på
100.000 gennemlever, indtil den sidste af dem er død. Når x er 60,
svarer T tilsvarende til alle de personår, som de, der overlevede frem
til deres 60-års fødselsdag (dvs. l60 ), gennemlever fra de fyldte 60
år, til den sidste af dem er død.  ex = Tx = det gennemsnitlige antal
leveår fra starten af alderstrin x til og med sidste lx alderstrin i
dødelighedstavlen. Svarer til middellevetiden. Når x er 0, svarer e
til alle de personår, som udgangspopulationen på 100.000 gennemlever,
indtil den sidste af dem er død, divideret med udgangspopulation på
100.000. Det er især e0 svarende til forventede levetid for en nyfødt
0-årig, der hyppigt anvendes, men e beregnes også for alle øvrige
alderstrin. Af dødelighedstavlen for mænd, der er vist som eksempel,
fremgår det, at middellevetiden for 0-årige er 76,52 år, mens den for
60-årige er 20,4 år. Tallet for 60-årige angiver det gennemsnitlige
antal leveår, som en person, der er blevet 60 år, har tilbage at leve
i regnet fra den dag, personen fylder 60 år.  Fra alderstrinet 104 år
og opefter er dødshyppigheden sat til 0,5, da de observerede tal for
disse alderstrin er meget usikre pga. det meget lave antal personer på
alders- trinene. Det gennemsnitlige antal dødeår er også sat til 0,5
for alderstrin fra 104 år og efter. I praksis har dødshyppighederne
for personer over 100 år meget lille betydning for middellevetiden for
0-årige.

** Danmark statistik

Med etableringen af den personstatistiske database har Danmarks
Statistik fået nye muligheder for at beregne dødshyppighederne mere
korrekt, idet databasen for alle personer i Danmark indeholder eksakt
information om eventuel dødsdato og ind- og udvandringstidsdatoer. Der
kan således for hver enkelt person udregnes nøjagtigt, hvor mange dage
personen i en årsperiode har været i Danmark og hvor mange af dagene i
årsperioden, personen har været død.  Den søgte dødshyppighed skal
præcist angive sandsynligheden for at dø på et bestemt alderstrin –
dvs. mellem to fødselsdage. For at opnå denne hyppighed laves der en
særlig beregning for hver enkelt person fra fødselsdag til fødselsdag
i en periode, der omfatter to kalenderår. I offentliggørelsen af
middellevetid fra 19. marts 2010 er det kalenderårene 2008 og 2009,
der ligger til grund for beregningerne. For alle personer, der var i
den danske befolkning på et eller andet tidspunkt mellem deres
fødselsdag i 2008 og i 2009, er der lavet en beregning for antallet af
dage, personen var i Danmark og antallet af dage personen var død i
perioden mellem de to fødselsdage.  For personer, der ikke dør mellem
to fødselsdage, vil antallet af dage som død naturligvis være 0.
Efterfølgende laves der en sammenlægning for personer med samme køn og
alderstrin for at få det samlede antal levedage og
dødedage. Personer vil placeres på det alderstrin, som svarer til det
antal år, de fyldte i startåret, hvilket i eksemplet vil sige
2008. En person, som fyldte 60 år 1. januar 2008 vil fx tilhøre de 60-årige. Det samme
vil en person, der fyldte 60 år 31. december 2008. Der kan altså i
yderste konsekvens være næsten et års forskel mellem den periode, som
personer på samme alderstrin følges. I et Lexis skema svarer de
anvendte grupper til såkaldte C-grupper, som omfatter personer, der er
født samme år.

Til beregning af dødshyppigheden skal der kendes antallet af døde og
antallet af personer med dødsrisiko. Antallet af døde fås simpelt ved
at sammenlægge alle personer i en bestemt køns- og aldersgruppe, der
døde mellem de to fødselsdage i 2008 og
2009. For at få et mål for gruppen med dødsrisiko målt i personer lægges køns- og
aldersgruppens samlede antal levedage og dødedage sammen, hvorefter
tallet divideres med 365.


** Header :noexport:

#+TITLE: Life tables
#+AUTHOR: Anna-Vera Jørring Pallesen, Laust Hvas Mortensen and Thomas Alexander Gerds
#+DATE: 
#+LaTeX_CLASS: danish-article
#+OPTIONS: toc:nil
#+LaTeX_HEADER:\usepackage{authblk}
#+LaTeX_HEADER:\usepackage{natbib}
#+LaTeX_HEADER:\usepackage{listings}
#+LaTeX_HEADER:\usepackage{color}
#+LaTeX_HEADER:\usepackage[usenames,dvipsnames]{xcolor}
#+LaTeX_HEADER:\usepackage[utf8]{inputenc}
#+LaTeX_HEADER:\usepackage{hyperref}
#+LaTeX_HEADER:\usepackage{amssymb}
#+LaTeX_HEADER:\usepackage{latexsym}
#+OPTIONS:   H:3  num:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:t todo:t pri:nil tags:not-in-toc author:t
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://publicifsv.sund.ku.dk/~tag/styles/all-purpose.css" />
#+LATEX_HEADER: \RequirePackage{tcolorbox}
# #+LaTeX_HEADER:\usepackage[table,usenames,dvipsnames]{xcolor}
#+LaTeX_HEADER:\definecolor{lightGray}{gray}{0.98}
#+LaTeX_HEADER:\definecolor{medioGray}{gray}{0.83}
#+LATEX_HEADER:\definecolor{mygray}{rgb}{.95, 0.95, 0.95}
#+LATEX_HEADER:\newcommand{\mybox}[1]{\vspace{.5em}\begin{tcolorbox}[boxrule=0pt,colback=mygray] #1 \end{tcolorbox}}
