* Introduktion

Overlevelsestavlen repræsenterer en matematisk model, der
kvantificeres ved hjælp af konkrete demografiske data. Modellen
genererer derefter en omfattende beskrivelse af dødelighedsforholdene
i den specifikke befolkning. De forskellige mål for dødelighed
konstrueres på baggrund af overlevelsestavlen. Dette gælder også for
målene vedrørende forekomsten af vielser, skilsmisser, folkevandringer og i
vis grad forskellige fertilitets- og
reproduktionsmål. Overlevelsestavlen kunne derfor gennemgås på en ret
abstrakt måde og fortolkes forskelligt, afhængigt af om den skal
anvendes til at beskrive dødelighed, vielser, skilsmisser eller
fertilitet. I det følgende vil vi dog fokusere på at opbygge modellen
omkring målingen af befolkningens dødelighed for at gøre det lettere
at forstå modellens umiddelbare anvendelighed.

** Middellevetid

Hvor mange år kan en nyfødt i dag forvente at leve? Dette spørgsmål er
umuligt at besvare korrekt, fordi svaret umiddelbart afhænger af, hvad der
sker i fremtiden. Alligevel er middellevetid, altså den forventede
gennemsnitlige levetid af en nyfødt, et demografisk værktøj som
anvendes hyppigt til belysning af befolkningens nuværende
dødelighedsniveau. Middellevetid bruges også som
sammenligningsgrundlag på tværs af befolkninger og tid. Tallet angiver
det gennemsnitlige antal år, som en nyfødt kan forvente at leve
/under den forudsætning/, at de nuværende mortalitetsrater for alle
grupperinger af køn og alderstrin holder sig på samme niveau i fremtiden.
Med middellevetiden har man et relativt simpelt begreb, som
gør det muligt at sammenligne forskellige befolkningers dødelighed. I
praksis vil de nuværende dødshyppigheder formentlig ikke holde sig på
et samme niveau i fremtiden.

Igennem mange år har der været en tendens til faldende
mortalitetsrater, og der er meget, som tyder på, at det er en
udvikling som fortsætter. Den konkrete fortolkning af middellevetiden
for 0-årige som det gennemsnitlige antal år, som en nyfødt kan
forventes at leve, vil derfor formentlig undervurdere den faktiske
middellevetid. Men formålet med middellevetiden er heller ikke at
forudsige præcist, hvor længe en nyfødt vil leve. Formålet er at have et
simpelt begreb, der kan sammenlignes på tværs af befolkninger og tid.
Figur ref:fig:k3-middellevetid viser udviklingen af middellevetid for
0-årige i Danmark siden 1840.

#+BEGIN_SRC R :results file graphics :file ./kapitel3/K3-udvikling-middellevetid.pdf :exports none :session *R* :cache yes
m <- hent_data("HISB7",tid = "all",køn = "all")
m <- mutate(m,kalender = as.numeric(sapply(strsplit(TID,":"),"[",1)))
g <- ggplot(m,aes(kalender,INDHOLD,colour = KØN,group = KØN))+geom_line()
g <- g+theme_wsj()+ scale_colour_wsj("colors6") + theme(axis.text.x = element_text(angle = -45))
g <- g+theme(axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)))
g <- g + theme(axis.title.x = element_text(margin = margin(t = 20, r = 0, b = 0, l = 0)))
g <- g+scale_x_continuous(breaks = seq(1840,2023,10))
g + ylab("Middellevetid for 0-årige (år)")+xlab("")
#+END_SRC

#+RESULTS[(2024-03-01 09:48:59) 906f5d7a78cc606c22b3cb67dfb5c43fd4eafa0a]:
[[file:./kapitel3/K3-udvikling-middellevetid.pdf]]

#+name: fig:k3-middellevetid
#+ATTR_LATEX: :width 0.9\textwidth
#+CAPTION: Udviklingen i middellevetid for 0-årige. Kilde: statistikbankens HISB7.[[file:./K3-udvikling-middellevetid.pdf]]

** Andre dødelighedsmål

Middellevetiden er måske det vigtigste mål, som resulterer af
overlevelsestavlen. En overlevelsestavle beskriver også en række andre
dødelighedsmål, såsom den forventede restlevetid fra alder \(x\),
sandsynligheden for at dø inden alder \(x\) og sandsynligheden for at
være i live ved alder \(x\).
Figur ref:fig:k3-middellevetid viser middelrestlevetiden for
43-årige i Danmark siden 1981.


#+BEGIN_SRC R :results file graphics :file ./kapitel3/K3-udvikling-middelrestlevetid.pdf :exports none :session *R* :cache yes
m <- hent_data("HISB8",alder = 43,tavle = 3,tid = "all",køn = "all")
m <- mutate(m,kalender = as.numeric(sapply(strsplit(TID,":"),"[",1)))
g <- ggplot(m,aes(kalender,INDHOLD,colour = KØN,group = KØN))+geom_line()
g <- g+theme_economist()+ scale_colour_wsj("colors6") + theme(axis.text.x = element_text(angle = -45))
g <- g+theme(axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)))
g <- g + theme(axis.title.x = element_text(margin = margin(t = 20, r = 0, b = 0, l = 0)))
g <- g+scale_x_continuous(breaks = seq(1840,2023,10))
g + ylab("Middelrestlevetid for 43 årige (år)")+xlab("")
#+END_SRC

#+RESULTS[(2024-03-01 09:48:53) c9af3a242ea2c505b0f102edf2b3639b89c1af65]:
[[file:./kapitel3/K3-udvikling-middelrestlevetid.pdf]]

#+name: fig:k3-middelrestlevetid
#+ATTR_LATEX: :width 0.9\textwidth
#+CAPTION: Udviklingen i middelrestlevetid for 43-årige. Kilde: statistikbankens HISB8.
[[file:./K3-udvikling-middelrestlevetid.pdf]]

** Eksempel

Vi henter data fra statistikbankens register =FOLK1a= og =FOD207= og
beregner aldersspecifikke mortalitetsrater for kvinder i Danmark i 2019.
Vi inddeler i 12 aldersintervaller, hvor det første interval har
længde 1 år, det andet interval har længde 9 år, resten af intervallerne
har længde 10 år og det sidste aldersinterval er fra 90 til 125 år. 

#+ATTR_LATEX: :options otherkeywords={hent_mortalitetsrate_data,filter,mutate,overlevelsestavle}, deletekeywords={c,rep,print,seq,R}
#+BEGIN_SRC R  :results output :exports both  :session *R* :cache yes  
x <- hent_mortalitetsrate_data(tid = 2019,
                               breaks = c(0,1,10,seq(20,90,10),Inf),
                               køn = "kvinder",
                               right = FALSE,
                               alder = "all_no_total")
x <- mutate(x,M = Dod/R)
x
#+END_SRC

#+RESULTS[(2024-03-01 09:55:07) d2db9294abb52f41cc0c375dcce49f61db0a9cf1]:
#+begin_example
# A tibble: 11 × 6
   aldersinterval KØN       TID      R   Dod         M
   <fct>          <chr>   <dbl>  <dbl> <dbl>     <dbl>
 1 0              Kvinder  2019  29448    74 0.00251  
 2 1-9            Kvinder  2019 270111    24 0.0000889
 3 10-19          Kvinder  2019 332202    32 0.0000963
 4 20-29          Kvinder  2019 383578    73 0.000190 
 5 30-39          Kvinder  2019 336414   128 0.000380 
 6 40-49          Kvinder  2019 378914   342 0.000903 
 7 50-59          Kvinder  2019 397594  1160 0.00292  
 8 60-69          Kvinder  2019 336747  2855 0.00848  
 9 70-79          Kvinder  2019 293474  6016 0.0205   
10 80-89          Kvinder  2019 129929  8878 0.0683   
11 90+            Kvinder  2019  32094  6921 0.216
#+end_example

Med disse tal fra den rigtige befolkning konstruerer vi
overlevelsestavlen, som beskriver dødeligheden i en hypotetisk
befolkning, der bliver født i 2019 og lever hele deres ``liv'' igennem
alle alderstrin i 2019, hvor de bliver udsat for mortalitetsraterne
fra 2019.

#+ATTR_LATEX: :options otherkeywords={hent_mortalitetsrate_data,filter,mutate,overlevelsestavle}, deletekeywords={c,rep,print,seq,R}
#+BEGIN_SRC R  :results output :exports both  :session *R* :cache yes  
x <- mutate(x,a = c(0.1,4.5,rep(5,9)),n = c(1,9,rep(10,9)))
tavle_kvinder <- overlevelsestavle(x,
                                   mortalitet = "M",
                                   alder = "aldersinterval")
print(tavle_kvinder,digits = 2)
#+END_SRC

#+RESULTS[(2024-03-01 09:56:07) 05faec4af649b08c3f49cb5ab3d81b1e6fed6ab5]:
#+begin_example
# A tibble: 11 × 9
   Alder      l     d     p        q     o      L        T     e
   <fct>  <dbl> <dbl> <dbl>    <dbl> <dbl>  <dbl>    <dbl> <dbl>
 1 0     100000   251 0.997 0.00251  1      99774 8334430. 83.3 
 2 1-9    99749    80 0.999 0.000799 0.997 897385 8234656. 82.6 
 3 10-19  99670    96 0.999 0.000963 0.997 996216 7337271. 73.6 
 4 20-29  99574   189 0.998 0.00190  0.996 994789 6341056. 63.7 
 5 30-39  99384   377 0.996 0.00380  0.994 991955 5346266. 53.8 
 6 40-49  99007   890 0.991 0.00899  0.990 985620 4354311. 44.0 
 7 50-59  98117  2821 0.971 0.0288   0.981 967065 3368691. 34.3 
 8 60-69  95296  7751 0.919 0.0813   0.953 914204 2401626. 25.2 
 9 70-79  87545 16278 0.814 0.186    0.875 794062 1487422. 17.0 
10 80-89  71267 36296 0.491 0.509    0.713 531192  693360.  9.73
11 90+    34971 34971 0     1        0.350 162168  162168.  4.64
#+end_example


#+Label: tab:overlevelstavle-kolonner
#+CAPTION: Forklaring af kolonner i en overlevelsestavle
#+ATTR_LATEX: :align l|l
| Kolonne | Betydning                                                       |
|---------+-----------------------------------------------------------------|
| =Alder= | Aldersinterval                                                  |
| =l=     | Dekrementfunktion: Antal tabelpersoner i starten af intervallet |
| =d=     | Antal døde i intervallet                                        |
| =p=     | Sandsynlighed for at overleve i intervallet                     |
| =q=     | Dødshyppighed: sandsynlighed for at dø i intervallet            |
| =o=     | Sandsynlighed for at overleve indtil starten af intervallet     |
| =L=     | Samlet risikotid i intervallet                                  |
| =T=     | Samletlevetid fra starten af intervallet                       |
| =e=     | Middelrestlevetid (i første interval =  middellevetid)          |

Fra overlevelsestavlen aflæser vi af kolonne =e=: under antagelsen af, at
mortalitetsraterne i 2019 ikke ændrer sig i al fremtid vil man
forvente, at en nyfødt pige lever 88,3 år og at en kvinde som er 30 år
gammel kan forvente at leve 53,8 år.

* Konstruktion af overlevelsestavler

Overlevelsestavler beskriver, hvordan en tænkt lukket fødselskohorte
reduceres med stigende alder alene på grund af dødsfald. Fordi
kohorten er lukket, er død den eneste mulige afgang fra kohorten. Der
tages udgangspunkt i en fiktiv tabelbefolkning bestående af
\(\ell_0\) personer, som antages at være født på nøjagtig samme
tidspunkt. Antallet af fiktive tabelpersoner \(\ell_0\) kaldes for
`radix', og radix sættes typisk til $\ell_0=100.000$.

** Dekrementfunktionen

Funktionen \(\ell_x\) angiver hvor mange tabelpersoner stadigvæk er i
live ved alder \(x\) og beskriver hvordan tabelbefolkningen reduceres
på grund af dødsfald. Startværdien \(\ell_0\) angiver, hvor mange
tabelpersoner, der er i tabelbefolkningen helt i begyndelsen, hvor alder
er lig med \(0\), og \(\ell_{30}\) angiver hvor mange tabelpersoner
er i live ved alder \(30\). Fordi \(\ell_x\) er monotont faldende som
funktion af alder, det vil sige, at der gælder
\(\ell_x\ge\ell_{x+1}\), kalder man den for dekrementfunktionen. Af
tabellen kan man aflæse, hvor mange personer forventes at overleve til en 
bestemt alder. For eksempel betyder \(\ell_{30}=99.345\), at \(99.345\) personer ud af
\(\ell_0=100.000\) tabelpersoner stadigvæk er i
live ved alder \(30\). I dette eksempel er overlevelsessandsynligheden
i tabelbefolkningen ved alder \(30\) lig med
#+begin_export latex
\begin{equation*}
o(30)=\frac{\ell_{30}}{\ell_0} = \frac{99.345}{100.000} = 99,3\%,
\end{equation*}
#+end_export
eftersom overlevelsesfunktionen er defineret som
#+begin_export latex
\begin{equation*}
o_x=\frac{\ell_x}{\ell_0}. 
\end{equation*}
#+end_export
Under konstruktionen af overlevelsestavler er opgaven at beregne
dekrementfunktionens værdier \(\ell_x\) for alle alderstrin \(x=0,1,
\dots, x^{max}\) hvor \(x^{max}\) er det sidste alderstrin. Per
konstruktion dør alle resterende
tabelpersoner i det sidste alderstrin - det vil sige
\(\ell_{x^{max}+1}=0\) og dermed også \(o_{x^{max}+1}=0\). Vi vil forklare
hvorfor senere. 

** Dødshyppigheder

Dødshyppigheden \(\qxk\) beskriver for en person med eksakt alder
\(x\) sandsynligheden for at dø inden alderen
\(x+k\). Dødshyppigheder forbinder den ægte, åbne befolkning, som man
interesserer sig for, med den tænkte, lukkede tabelbefolkning, der
definerer overlevelsestavlen. Man beregner dødshyppigheder baseret på
aldersspecifikke mortalitetsrater, og den underliggende idé er, at
mortalitetsraterne er ens i den ægte befolkning og i tabelbefolkningen
for begge køn og alle alderstrin.

#+begin_export latex
\mybox{Bemærkning til notation:\\

Det er standardnotation i demografi at have index på begge
sidder af symbolet ligesom i \qxk. Her er index til højre 
starten af et aldersinterval og index til venstre er længden af
aldersintervallet. Det er lidt forvirrende, fordi
intervallet inkluderer startalder \(x\):
\begin{center}
\begin{tabular}{lm{4em}rrl}
Symbol & Start & Længden & Slut & Betydning\\[0pt]
\hline
\({}_{1}D_{0}\) & 0 & 1 & 1 & Antal døde i alder \(0\)\\[0pt]
\({}_{4}D_{1}\) & 1 & 4 & 4 & Antal døde i alder 1, 2, 3, 4\\[0pt]
\({}_{5}D_{5}\) & 5 & 5 & 9 & Antal døde i alder 5, 6, 7, 8, 9\\[0pt]
\end{tabular}
\end{center}
Vi ændrer nu også notationen for de aldersspecifikke
mortalitetsrater. I Kapitel 2 har vi brugt \(M_x\) for mortalitetsraten
i det \(x\)-te aldersinterval.
Fra nu af bruger vi den mere præcise betegnelse
\(\Mxk\) for mortalitetsraten i det aldersinterval, som starter i alderen \(x\)
og slutter i alderen \(x+k\).
}
#+end_export

# | Symbol          | Startalder | Længden | Slutalder | Betydning              |
# |-----------------+------------+---------+-----------+------------------------|
# | \({}_{1}D_{0}\) |          0 |       1 |         1 | Antal døde i \([0,1)\) |
# | \({}_{4}D_{1}\) |          1 |       4 |         4 | Antal døde i \([1,4)\) |
# | \({}_{5}D_{5}\) |          5 |       5 |         9 | Antal døde i \([5,9)\) |

*** Approksimationsformlen

For at beregne dødssandsynligheder i den ægte befolkning vil man gerne
dividere antal dødsfald i en kalenderperiode med antal personer i
starten af perioden. Problemet er, at den ægte befolkning er /åben/:
Dødsfald bliver ikke registreret for personer som udvandrer i
perioden, og både udvandrere og indvandrere i perioden bidrager ikke med
risikotid til hele perioden. Ideen er derfor at tilnærme
dødshyppighederne baseret på mortalitetsrater. Aldersspecifikke
mortalitetsrater kan beregnes på de registrerede data, ved at dividere
antal dødsfald i befolkningen med risikotiden, hvor indvandrere og
udvandrere kun bidrager med den tid de har været i befolkningen (se
Kapitel 1 og 2). Nøglen til en tilnærmelse af dødshyppighederne
baseret på mortalitetsrater er følgende centrale formel for
overlevelsestavlen:

#+begin_export latex 
\begin{equation}\label{k3-dhyppig}
\qxk= \frac{k\cdot \Mxk}{1+(k-\a{k})\cdot \Mxk} 
\end{equation}
#+end_export

Formlen afhænger aldersspecifikke mortalitetsrater \Mxk, længden af
aldersintervallet \(k\) og også en konstant \(\a{k}\), som kaldes
Chiang's a. Konstanten \(\a{k}\) beskriver den gennemsnitlige levetid
i aldersintervallet for personer, der døde mellem alderen \(x\) og aldeen
\(x+k\). Dermed beskriver \((k-\a{k})\) den gennemsnitlige tid som en
person der døde i aldersintervallet var død.  Hvis vi for eksempel ser
på et aldersinterval mellem 70 og 79 år og en person døde i alder 74,
så har den person været i live i 4 år (70, 71, 72, 73) og død i 6
år (74, 75, 76, 77, 78, 79). En person som døde i alder 78 har været i
live i 8 år og død i 2 år, og så videre. Værdien af \({}_{10}a_{70}\)
skal afspejle det gennemsnitlige antal år, som personer der døde i
denne aldersgruppe, var i live. For de fleste intervaller vil man
antage at gennemsnittet ligger i midten, altså i eksemplet vil man
vælge \({}_{10}a_{70} = 5\).

*** Chiang's a
:PROPERTIES:
:CUSTOM_ID: chiang
:END:
For at beregne dødshyppigheder med den centrale formel
eqref:k3-dhyppig har vi brug for at specificere Chiang's a for alle
aldersintervaller. Chiang's a skal tilnærme det forventede antal år
levet i intervallet af en person, som dør i intervallet. Hvis Chiang's
a opfylder dette, kan vi tilnærme den samlede dødstid, som alle
personer der døde i aldersintervallet har været døde:
#+begin_export latex
\begin{equation*}
\begin{split}
\text{Samlede dødstid i aldersintervallet}&=(k- \a{k})\cdot\Dxk,\\
 k &= \text{Antal år i aldersintervallet}\\
 \Dxk &= \text{Antal døde i aldersintervallet}\\
 \a{k} &= \text{Gennemsnitlige antal dødsår i intervallet}\\
 \{x,x+1,\dots,x+k\} &= \text{År i intervallet}.
\end{split}
\end{equation*}
#+end_export
Hvis vi antager at dødstider er
lige fordelt i aldersintervallet, altså at det er lige sandsynligt at
dø i starten som det er at dø i slutningen af aldersintervallet, er
det rimeligt at vælge
#+begin_export latex
\begin{equation*}
\a{k} = \frac k 2.
\end{equation*}
#+end_export
Det første og sidste aldersinterval vil dog altid kræve særlige
værdier af \a{k}. I det første leveår er dødstiderne meget skævt
fordelt over året - de fleste dødstider inden 1-års fødselsdagen ligger
kort efter fødslen. Derfor sætter vi \(\a[0]{1}=0,1\). For det sidste
interval \(x^{max}\) vælger vi
#+begin_export latex
\begin{equation}\label{eq:amax}
\a[x^{max}]{\infty} =
\frac{1}{{}_\infty M_{x^{max}}}, 
\end{equation}
#+end_export
så dødshyppigheden i det sidste interval bliver 1, og det betyder, at
alle tabelpersoner dør i det sidste aldersinterval, dvs. \({}_\infty q_{x^{max}} = 1\).
ved formel eqref:k3-dhyppig. 

#+Label: tab-K3.1
#+CAPTION: Tabellen viser hvordan vi vælger Chiang's a for 1-års, 5-års og 10-års aldersintervaller.
#+ATTR_LATEX: :align l|l|l 
|                        | 5-års aldersintervaller                         | 10-års aldersintervaller                        |
|------------------------+-------------------------------------------------+-------------------------------------------------|
| Første leveår          | \(\a[0]{1}=0,1\)                                | \(\a[0]{1}=0,1\)                                |
| Aldersinterval 1-5 år  | \(\a[1]{4}= 4\cdot 0,5=2\)                      | \(\a[1]{9}= 9\cdot 0,5=4,5\)                    |
| Alle andre intervaller | \(\a[5]{k}=5\cdot 0,5\)=2,5                     | \(\a[10]{k}=10\cdot 0,5=5\)                     |
| Sidste aldersinterval  | \(a_{x^{max}}=\frac{1}{{}_\infty M_{x^{max}}}\) | \(a_{x^{max}}=\frac{1}{{}_\infty M_{x^{max}}}\) |

*** Forklaring af den centrale formel

I det følgende skal vi på en uformel måde forklare formel
eqref:k3-dhyppig. Hvis den ægte befolkning var lukket, altså uden
forekomst af ind- og udvandring, ville man kunne beregne
dødshyppighederne simpelt som antal dødsfald i aldersintervallet
divideret med antal personer i starten af aldersintervallet:
#+begin_export latex
\begin{equation*}
\text{Dødshyppighed} = \frac{\text{Antal dødsfald i aldersintervallet}}{\text{Antal personer i starten}}.
\end{equation*}
#+end_export
Hvis aldersintervallet er over \(k\) år gælder
#+begin_export latex
\begin{equation*}
\text{Antal personer i starten} = \frac{\text{Risikotid} + \text{Dødstid}}{k}.
\end{equation*}
#+end_export
Her er risikotiden det samlede antal år, som befolkningens personer har
levet (i aldersintervallet), og dødstiden er tilsvarende det samlede
antal år, som befolkningens personer var døde. Med denne formel kan
dødshyppigheden skrives som
#+begin_export latex
\begin{equation}\label{eq:k3-uformel}
\text{Dødshyppighed} = \frac{k\cdot \text{Antal dødsfald i aldersinterval}}{\text{Risikotid}+\text{Dødstid}}.
\end{equation}
#+end_export
Vi sætter Chiang's a sådan at
#+begin_export latex
\begin{equation*}
\text{Dødstid i aldersinterval}=(k- \a{k})\cdot\Dxk,
\end{equation*}
#+end_export
er en god tilnærmelse af den samlede dødstid, som alle personer der
døde i aldersintervallet har været døde (c.f., afsnit ref:chiang). Hvis
vi nu anvender formlen for den aldersspecifikke mortalitetsrate
fra Kapitel 2, 
#+begin_export latex
\begin{equation*}
\Mxk = \frac{\Dxk}{\Rxk},
\end{equation*}
#+end_export
ser vi at den centrale formel
eqref:k3-dhyppig faktisk er lig med formel eqref:eq:k3-uformel:
#+begin_export latex
\begin{align*}
\frac{k\cdot\Mxk}{1+(k-\a{k})\cdot \Mxk} &=\frac{k\cdot\frac{\Dxk}{\Rxk}}{1+(k-\a{k})\cdot \frac{\Dxk}{\Rxk}}\\
&=\frac{k\cdot\Dxk}{\Rxk\cdot(1+(k-\a{k})\cdot \frac{\Dxk}{\Rxk})}\\
&=\frac{k\cdot \Dxk}{\Rxk+(k-\a{k})\cdot \Dxk}.
\end{align*}
#+end_export

*** Beregningen af antal dødsfald og overlevelser

Vi fortsætter nu konstruktionen af overlevelsestavlen. Vi starter med
en radix af \(\ell_0\) tabelpersoner. For at beregne antal
tabelpersoner som overlever indtil det første alderstrin, \(x=1\),
skal vi beregne hvor mange tabelpersoner dør mellem alder \(x=0\) og
alder \(x=1\). For at beregne hvor mange tabelpersoner der overlever alder
\(x+k\) skal vi beregne hvor mange af de resterende \(\ell_x\)
tabelpersoner der dør i aldersintervallet. Vi betegner med \(\d{k}\) antal
tabelpersoner som dør mellem alder \(x\) og alder \(x+k\). Dermed er
\(\d{1}\) antal tabelpersoner som dør mellem alder \(x\) og alder
\(x+1\). Sandsynligheden for at dø mellem to alderstrin
(dødshyppighederne) er det centrale element ved konstruktionen af
overlevelsestavlen. Vi beregner antal dødsfald i aldersintervallet ved
at gange antal tabelpersoner i starten af intervallet med
dødshyppigheden:
#+begin_export latex
\begin{equation}\label{antaltabeldod}
\d{k} = \qxk\cdot\ell_x.
\end{equation}
#+end_export
Det er vigtig at skelne mellem antal døde \(\Dxk\) i den ægte
befolkning og antal døde \(\d{k}\) i tabelbefolkningen. Med formel
eqref:antaltabeldod er det en let sag at beregne, hvor mange
tabelpersoner er i live i starten af det næste aldersinterval:
#+begin_export latex
\begin{equation*}
\ell_{x+k}=\ell_{x} - \d{k}.
\end{equation*}
#+end_export
Alternativt kan vi starte med at beregne dekrementfunktionen baseret
på dødshyppigheden
#+begin_export latex
\begin{equation*}
\ell_{x+k}=\ell_{x}\cdot (1-q_x).
\end{equation*}
#+end_export
Bagefter er det simpelt at beregne antal dødsfald som
#+begin_export latex
\begin{equation*}
\d{k} = l_{x} - l_{x+k}.
\end{equation*}
#+end_export
Med disse formler kan vi konstruere overlevelsestavlen vigtigste
kolonner (\(\ell_0\) og \(\d{k}\)). Vi beskriver nu de vigtigste
dødelighedsmål som overlevelsestavlen viser.

*** Beregning af middelrestlevetid og middellevetid 

Vi betegner med \(\L{k}\) den samlede gennemlevede tid i
tabelbefolkningen i alderen mellem \(x\) og \(x+k\). Da dødsfald er
eneste afgangsårsag i tabelbefolkningen har vi
#+begin_export latex
\begin{align*}
\L{k} &= \text{bidrag fra overlevende + bidrag fra døde}\\
    &= k\cdot \ell_{x+k} + \a{k}\cdot \d{k}\\
    &= \a{k}\cdot\ell_x + (k- \a{k})\cdot \ell_{x+k}.
\end{align*}
#+end_export

Vi skal nu beregne den /forventede restlevetid/ for en \(x\)-årig
tabelperson. For en nyfødt er \(x=0\) og dermed bliver den forventede
middelrestlevetid til den forventede levetid, som betegnes med
/middellevetid/. Lad \(T_x\) angive den samlede levetid i
tabelbefolkningen efter \(x\)-års fødselsdagen, specielt er \(T_0\)
den samlede levetid i tabelbefolkningen. Vi beregner
#+begin_export latex
\begin{align*}
T_x &= \L{k} + \cdots + \L[x^{max}]{k}\\
    &= \a{k}\cdot\ell_x + (k- \a{k})\cdot \ell_{x+k} + \cdots + \a[x^{max}]{\infty}\cdot\ell_{x^{max}}.
\end{align*}
#+end_export
I tabelbefolkningen overlever \(\ell_x\) personer til deres \(x\)-års
fødselsdag, så den gennemsnitlige levetid efter \(x\)-års fødselsdagen
bliver
#+begin_export latex
\begin{equation}\label{eq:restlevetid}
e_x=\frac{T_x}{\ell_x} = \text{gennemsnitlige restlevetid}.
\end{equation}
#+end_export
Denne kvotient kaldes den forventede restlevetid eller
middelrestlevetid for en \(x\)-årig tabelperson. På tilsvarende vis
bliver middellevetid beregnet som
#+begin_export latex
\begin{equation}\label{eq:middellevetid}
e_0=\frac{T_0}{\ell_0} = \text{middellevetid}.
\end{equation}
#+end_export

*** Fortolkning

Når man fortolker middellevetid og middelrestlevetid er det vigtigt at huske
og fremhæve at beregningen bygger på en hypotetisk tabelbefolkning som
lever hele deres liv i en kort kalenderperiode. Danmarks Statistik
forklarer middelrestlevetiden sådan[fn:1]:

#+begin_export latex
\mybox{ Middelrestlevetiden er det gennemsnitlige antal år, som personer på en given
fødselsdag har tilbage at leve i, {\it hvis deres dødelighed fremover
(alder for alder) svarer til det niveau, som er konstateret i den
aktuelle periode}.}
#+end_export

[fn:1] https://www.dst.dk/da/Statistik/emner/borgere/befolkning/middellevetid

** Overlevelsestavle med 1-års intervaller




** Danmark statistik

Med etableringen af den personstatistiske database har Danmarks
Statistik fået nye muligheder for at beregne dødshyppighederne mere
korrekt, idet databasen for alle personer i Danmark indeholder eksakt
information om eventuel dødsdato og ind- og udvandringsdatoer. Der
kan således for hver enkelt person udregnes nøjagtigt, hvor mange dage
personen i en årsperiode har været i Danmark og hvor mange af dagene i
årsperioden, personen har været død. Den søgte dødshyppighed skal
præcist angive sandsynligheden for at dø i et bestemt alderstrin, 
dvs. mellem to fødselsdage. For at opnå denne hyppighed laves
der en særlig beregning for hver enkelt person fra fødselsdag til
fødselsdag i en periode, der omfatter to kalenderår. I
offentliggørelsen af middellevetid fra 19. marts 2010 er det
kalenderårene 2008 og 2009, der ligger til grund for
beregningerne. For alle personer, der var i den danske befolkning på
et eller andet tidspunkt mellem deres fødselsdag i 2008 og i 2009, er
der lavet en beregning for antallet af dage, personen var i Danmark og
antallet af dage personen var død i perioden mellem de to
fødselsdage. For personer, der ikke dør mellem to fødselsdage, vil
antallet af dage som død naturligvis være 0.  Efterfølgende laves der
en sammenlægning for personer med samme køn og alderstrin for at få
det samlede antal levedage og dødsdage. Personer vil placeres på det
alderstrin, som svarer til det antal år, de fyldte i startåret,
hvilket i eksemplet vil sige 2008. En person, som fyldte 60 år 1. januar 2008 vil f.eks. tilhøre de
60-årige. Det samme vil en person, der fyldte 60 år 31. december 2008.
Der kan altså i yderste konsekvens være næsten et års forskel mellem
den periode, som personer på samme alderstrin følges.

Man kan se de nyeste beregninger fra Danmark Statistik her:
[[https://www.dst.dk/da/Statistik/emner/borgere/befolkning/middellevetid][Middelevetid]], og finde dokumentation for beregningerne her: 
[[https://www.dst.dk/ext/36380110073/0/befolkning/Hvordan-beregner-vi-middellevetid?--pdf][Dokumentation]].

** Header :noexport:

#+TITLE: Overlevelsestavler
#+AUTHOR: Anna-Vera Jørring Pallesen, Johan Sebastian Ohlendorff, Laust Hvas Mortensen and Thomas Alexander Gerds
#+DATE: 
#+LaTeX_CLASS: danish-article
#+OPTIONS: toc:nil
#+LaTeX_HEADER:\usepackage{authblk}
#+LaTeX_HEADER:\usepackage{natbib}
#+LaTeX_HEADER:\usepackage{listings}
#+LaTeX_HEADER:\usepackage{color}
#+LaTeX_HEADER:\usepackage[usenames,dvipsnames]{xcolor}
#+LaTeX_HEADER:\usepackage[utf8]{inputenc}
#+LaTeX_HEADER:\usepackage{hyperref}
#+LaTeX_HEADER:\usepackage{amssymb}
#+LaTeX_HEADER:\usepackage{latexsym}
#+LaTeX_HEADER:\usepackage{fancyhdr}
#+LaTeX_HEADER:\usepackage[danish]{babel}
#+LaTeX_HEADER:\pagestyle{fancy}
#+LaTeX_HEADER:\lhead{Folkesundhedsvidenskab 2. semester, K{\o}benhavns Universitet}
#+LaTeX_HEADER:\rhead{Demografi}
#+LaTeX_HEADER:\renewcommand\theequation{K3.\arabic{equation}}
#+OPTIONS:   H:3  num:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:t todo:t pri:nil tags:not-in-toc author:t
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://publicifsv.sund.ku.dk/~tag/styles/all-purpose.css" />
#+LATEX_HEADER: \RequirePackage{tcolorbox}
#+LATEX_HEADER: \hyphenation{alders-speci-fik-ke}
#+LATEX_HEADER: \hyphenation{be-folk-ning}
#+LATEX_HEADER: \hyphenation{ta-bel-be-folk-ning}
#+LATEX_HEADER: \hyphenation{re-gist-re-ret}
# #+LaTeX_HEADER:\usepackage[table,usenames,dvipsnames]{xcolor}
#+LaTeX_HEADER:\definecolor{lightGray}{gray}{0.98}
#+LaTeX_HEADER:\definecolor{medioGray}{gray}{0.83}
#+LATEX_HEADER:\definecolor{mygray}{rgb}{.95, 0.95, 0.95}
#+Latex_Header: \newcommand{\qxk}{\ensuremath{{}_{k}q_{x}}}
#+Latex_Header: \newcommand{\dxk}{\ensuremath{{}_{k}d_{x}}}
#+Latex_Header: \newcommand{\qxe}[1][x]{\ensuremath{{}_{1}q_{#1}}}
#+Latex_Header: \newcommand{\Dxk}[1][x]{\ensuremath{{}_{k}D_{#1}}}
#+Latex_Header: \renewcommand{\d}[2][x]{\ensuremath{{}_{#2}d_{#1}}}
#+Latex_Header: \newcommand{\qxf}[1][x]{\ensuremath{{}_{5}q_{#1}}}
#+Latex_Header: \newcommand{\Mxf}[1][x]{\ensuremath{{}_{5}M_{#1}}}
#+Latex_Header: \newcommand{\Mxk}[1][x]{\ensuremath{{}_{k}M_{#1}}}
#+Latex_Header: \newcommand{\Rxk}[1][x]{\ensuremath{{}_{k}R_{#1}}}
#+Latex_Header: \renewcommand{\a}[2][x]{\ensuremath{{}_{#2}a_{#1}}}
#+Latex_Header: \renewcommand{\L}[2][x]{\ensuremath{{}_{#2}L_{#1}}}
#+LATEX_HEADER:\newcommand{\mybox}[1]{\vspace{.5em}\begin{tcolorbox}[boxrule=0pt,colback=mygray] #1 \end{tcolorbox}}
