* Introduktion

Overlevelsestavlen repræsenterer en matematisk model, der
kvantificeres ved hjælp af konkrete demografiske data. Modellen
genererer derefter en omfattende beskrivelse af dødelighedsforholdene
i den specifikke befolkning. De forskellige mål for dødelighed
konstrueres på baggrund af overlevelsestavlen. Dette gælder også for
målene vedrørende forekomsten af vielser, skilsmisser, vandringer og i
vis grad forskellige fertilitets- og
reproduktionsmål. Overlevelsestavlen kunne derfor gennemgås på en ret
abstrakt måde og fortolkes forskelligt, afhængigt af om den skal
anvendes til at beskrive dødelighed, vielser, skilsmisser eller
fertilitet. I det følgende vil vi dog fokusere på at opbygge modellen
omkring målingen af befolkningens dødelighed for at gøre det lettere
at forstå modellens umiddelbare anvendelighed.

** Middellevetid

Hvor mange år kan en nyfødt i dag forvente at leve? Dette spørgsmål er
ret umuligt at besvare fordi svaret umiddelbart afhænger hvad der sker
i fremtiden. Alligevel er middellevetid et demografisk værktøj som
anvendes hyppigt til belysning af befolkningens nuværende
dødelighedsniveau. Middellevetid bruges også som
sammenligningsgrundlag på tværs af befolkninger og tid. Tallet angiver
det gennemsnitlige antal år, som en nyfødt kan forventes at leve under
den forudsætning, at de nuværende mortalitetsrater for alle
grupperinger af køn og alderstrin holder sig på det samme niveau i al
fremtid. Med middellevetiden har man et relativt simpelt begreb, som
gør det muligt at sammenligne forskellige befolkningers dødelighed. I
praksis vil de nuværende dødshyppigheder formentlig ikke holde sig på
et konstant niveau i al fremtid.

I gennem mange år har der været en tendens til faldende
mortalitetsrater, og der er meget, som tyder på, at det er en
udvikling som fortsætter. Den konkrete fortolkning af middellevetiden
for 0-årige som det gennemsnitlige antal år, som en nyfødt kan
forventes at leve, vil derfor formentlig undervurdere den faktiske
middellevetid. Men formålet med middellevetiden er heller ikke at
forudsige præcist, hvor længe nyfødte vil leve. Formålet er at have et
simpelt begreb, der kan sammenlignes på tværs af befolkninger og tid.


** Andre dødelighedsmål

Middellevetiden er et mål som resulterer fra den såkaldte
overlevelsestavle. En klassisk overlevelsestavle beskriver også en
række andre dødelighedsmål, såsom den forventede restlevetid fra alder
\(x\), sandsynligheden for at dø inden alder \(x\) og sandsynligheden
for at være i live ved alder \(x\).

* Konstruktion af overlevelsestavle

Overlevelsestavler beskriver hvordan en tænkt lukket fødselskohorte
reduceres med stigende alder alene på grund af dødsfald. Fordi
kohorten er lukket, er død den eneste mulige afgang fra kohorten. Der
tages udgangspunkt i en fiktiv tabelbefolkning bestående af
\(\ell_0\) personer, som antages at være født på nøjagtig samme
tidspunkt. Antallet af fiktive tabelpersoner \(\ell_0\) kaldes for
`radix' og radix sættes typisk til $\ell_0=100.000$.

** Dekrementfunktion

Funktionen \(\ell\) angiver hvor mange tabelpersoner er stadigvæk i
live ved alder \(x\) og beskriver hvordan tabelbefolkningen reduceres
på grund af dødsfald. Startværdien \(\ell_0\) angiver hvor mange
tabelpersoner der er i tabelbefolkningen helt i begyndelsen hvor alder
er lige med \(0\), og \(\ell_30)\) angiver hvor mange tabelpersoner er
i livet ved alder \(30\). Fordi \(\ell\) er monoton faldende som
funktion af alder, altså \(\ell_x\ge\ell_{x+1}\), kalder man den for
dekrementfunktion. For eksempel, \(\ell_30=91.047\) betyder at ud
af \(\ell_0=100.000\) tabelpersoner \(91.047\) personer er stadigvæk
i live ved alder \(30\). I dette eksempel er
overlevelsessandsynligheden i tabelbefolkningen ved alder \(30\) lige
med
#+begin_export latex
\begin{equation*}
o(30)=\frac{\ell_30}{\ell_0} = \frac{91.047}{100.000} = 91,1\%.
\end{equation*}
#+end_export
Overlevelsesfunktionen er defineret som
#+begin_export latex
\begin{equation*}
o(x)=\frac{\ell_x}{\ell_0}. 
\end{equation*}
#+end_export
Under konstruktionen af overlevelsestavler er opgaven at beregne
dekrementfunktionens værdier \(\ell_x\) for alle alderstrin \(x=0,1,
\dots, x^{max}\) hvor \(x^{max}\) er det sidste alderstrin. Per
konstruktion, der bliver forklaret i detaljer nedenfor, dør alle
resterende tabelpersoner i det sidste alderstrin, det vil sige
\(\ell_{x^{max}+1}=0\), og dermed har vi også \(o(x^{max}+1)=0\).

** Dødshyppigheder

Dødshyppigheder \(\qxk\) beskriver sandsynligheden for at dø i
aldersintervallet \((x,x+k]\) given overlevelse indtil alder
\(x\). Dødshyppigheder forbinder den ægte, åbne befolkning, som man
interesserer sig for, med den tænkte, lukkede tabelbefolkning der
definerer overlevelsestavlen. Den underliggende idé er at
mortalitetsraterne er det samme i disse to befolkninger for begge køn
og alle alderstrin.

*** Approksimationsformel

For at beregne dødshyppighederne \(\qxk\) bruger vi data fra den ægte
befolkning, typisk fra en kort kalenderperiode. Problemet er at den
ægte befolkning er /åben/. Dødsfald bliver ikke bliver registreret for
personer som udvandrer i perioden og både udvandrer og indvandrer i
perioden bidrager ikke med risikotid til hele perioden. Derfor er det
uklar hvor mange personer der er i aldersintervallet. Aldersspecifikke
summariske mortalitetsrater løser problemet ved at dividere antal
dødsfald med antal risikotid hvor indvandrer og udvandrer bidrager med
den tid de nu har været i befolkningen. Nøglen til en approksimation
af dødshyppigheder baseret på mortalitetsrater er følgende centrale
formel:

#+begin_export latex 
\begin{equation}\label{k3-dhyppig}
\qxk= \frac{k\cdot \Mxk}{1+(k-\a{k})\cdot \Mxk} 
\end{equation}
#+end_export

Formlen afhænger aldersspecifikke mortalitetsrater \Mxk, længden af
aldersintervallet \(k\), og også en konstant \(\a{k}\), som kaldes
Chiang's a. Konstanten \(\a{k}\) beskriver den gennemsnitlige levetid
i aldersintervallet \((x,x+k]\) for personer, der døde mellem alder
\(x\) og alder \(x+k\). Dermed beskriver \((k-\a{k})\) den
gennemsnitlige tid som en person der døde i aldersintervallet var død.

*** Chiang's a
:PROPERTIES:
:CUSTOM_ID: chiang
:END:
For at beregne dødshyppigheder med den centrale formel
eqref:k3-dhyppig har vi brug for at specificere Chiang's a for alle
aldersintervaller. Chiang's a skal approksimere det forventede antal
år levet i intervallet af en person, som dør i intervallet. Hvis
Chiang's a opfylder dette, bliver
#+begin_export latex
\begin{equation*}
\text{Dødstid i aldersinterval}=(k- \a{k})\cdot\Dxk,
\end{equation*}
#+end_export
en god approksimation af antal dødstid som alle personer der døde i
aldersintervallet har været død.

Hvis vi antager at dødtider er jævnt fordelt i aldersintervallet,
altså at det er lige sandsynligt at dø i starten som det er i
slutningen af aldersintervallet, er det rimeligt at vælge
#+begin_export latex
\begin{equation*}
\a{k} = \frac k 2.
\end{equation*}
#+end_export
Det første og sidste aldersinterval vil dog altid kræve særlige
værdier af \a{k}. I det første leveår er dødstiderne meget skævt
fordelt over året, de fleste dødstider inden 1-års fødselsdagen ligger
kort efter fødslen. Derfor sætter vi \(\a[0]{1}=0,1\). For det sidste
interval \(x^{max}\) vil man typisk vælge \(\a[x^{max}]{\infty}\), så
dødshyppigheden bliver 1. Det svarer til at vælge
\(\a[x^{max}]{\infty} = \frac{1}{{}_\infty M_{x^{max}}}\).


|               | 5-års aldersintervaller | 10-års aldersintervaller |
|---------------+-------------------------+--------------------------|
| første leveår | \(\a[0]{1}=0,1\)        | \(\a[0]{1}=0,1\)         |
| aldersinterval 1-5 år | \(\a[1]{4}= 4\cdot 0,5=2\) |\(\a[1]{9}= 9\cdot 0,5=4,5\)
| alle andre intervaller|  \(\a[5]{k}=5\cdot 0,5\)=2,5 | \(\a[10]{k}=10\cdot 0,5=5\)
| sidste aldersinterval|   \(a_{x^{max}}=\frac{1}{{}_\infty M_{x^{max}}}\) | \(a_{x^{max}}=\frac{1}{{}_\infty M_{x^{max}}}\)|


*** Forklaring af den centrale formel

I det følgende skal vi på en uformelt måde forklare formel
eqref:k3-dhyppig. Hvis den ægte befolkning var lukket, altså uden
forekomst af ind- og udvandring, ville man kunne beregne
dødshyppighederne simpelt som antal dødsfald i aldersintervallet
divideret med antal personer i starten af aldersintervallet:
#+begin_export latex
\begin{equation*}
\text{Dødshyppighed} = \frac{\text{Antal dødsfald i aldersinterval}}{\text{Antal personer i starten}}.
\end{equation*}
#+end_export
Fordi aldersintervallet er \(k\) år lang gælder
#+begin_export latex
\begin{equation*}
\text{Antal personer i starten} = \frac{\text{Risikotid} + \text{Dødstid}}{k}.
\end{equation*}
#+end_export
Her er risikotid antal år som befolkningens personer har livet (i
aldersintervallet) og dødstid antal år som befolkningens personer var
døde. Med denne formel kan dødshyppigheden skrives som
#+begin_export latex
\begin{equation}\label{eq:k3-uformel}
\text{Dødshyppighed} = \frac{k\cdot \text{Antal dødsfald i aldersinterval}}{\text{Risikotid}+\text{Dødstid}}.
\end{equation}
#+end_export
Vi sætter Chiang's a sådan at
#+begin_export latex
\begin{equation*}
\text{Dødstid i aldersinterval}=(k- \a{k})\cdot\Dxk,
\end{equation*}
#+end_export
er en god approksimation af antal dødstid som alle personer der døde i
aldersintervallet har været død (c.f., afsnit ref:chiang). Hvis vi nu
anvender formlen for den aldersspecifikke mortalitetsrate
#+begin_export latex
\begin{equation*}
\Mxk = \frac{\Dxk}{\Rxk} 
\end{equation*}
#+end_export
ser vi at den centrale formel
eqref:k3-dhyppig er faktisk lige med formel eqref:eq:k3-uformel:
#+begin_export latex
\begin{align*}
\frac{k\cdot\Mxk}{1+(k-\a{k})\cdot \Mxk} &=\frac{k\cdot\frac{\Dxk}{\Rxk}}{1+(k-\a{k})\cdot \frac{\Dxk}{\Rxk}}\\
&=\frac{k\cdot\Dxk}{\Rxk\cdot(1+(k-\a{k})\cdot \frac{\Dxk}{\Rxk})}\\
&=\frac{k\cdot \Dxk}{\Rxk+(k-\a{k})\cdot \Dxk}.
\end{align*}
#+end_export


*** Beregning af antal dødsfald og overlever

For at beregne antal tabelpersoner som overlever indtil det første
alderstrin, \(x=1\), skal vi beregne hvor mange tabelpersoner dør
mellem alder \(x=0\) og alder \(x=1\). For at beregne hvor mange
tabelpersoner overlever alder \(x+k\) skal vi beregne hvor mange af de
resterende \(\ell_x\) tabelpersoner dør i aldersintervallet
\((x,x+k]\). Vi betegner med \(\d{k}\) antal tabelpersoner som dør
mellem alder \(x\) og alder \(x+k\). Dermed er \(\d{1}\) antal
tabelpersoner som dør mellem alder \(x\) og alder
\(x+1\). Sandsynligheden for at dø mellem to alderstrin
(dødshyppighederne) er som sagt det centrale element ved
konstruktionen af overlevelsestavlen. Vi beregner antal dødsfald i
aldersintervallet \((x,x+k]\) ved at multiplicere antal tabelpersoner
i starten af intervallet med dødshyppigheden:
#+begin_export latex
\begin{equation}\label{antaltabeldod}
\d{k} = \qxk\cdot\ell_x.
\end{equation}
#+end_export
Det er vigtig at skelne mellem antal døde \(\Dxk\) i den ægte
befolkning og antal døde \(\d{k}\) i tabelbefolkningen. Baseret på
formel eqref:antaltabeldod kan vi beregne hvor mange tabelpersoner er
i livet i starten af det næste aldersinterval:
#+begin_export latex
\begin{equation*}
\ell_{x+k}=\ell_{x} - \d{k}.
\end{equation*}
#+end_export
Alternativt kan vi starte med at beregne dekrementfunktionen baseret
på dødshyppigheden 
#+begin_export latex
\begin{equation*}
\ell_{x+k}=\ell_{x}\cdot (1-q_x),
\end{equation*}
#+end_export
og bagefter beregne antal dødsfald som
#+begin_export latex
\begin{equation*}
\d{k} = l_{x} - l_{x+k}.
\end{equation*}
#+end_export

*** Beregning af restlevetid og middellevetid 

Vi betegner med \(\L{k}\) den samlede gennemlevede tid i
tabelbefolkningen i en alder mellem \(x\) og \(x+k\). Da dødsfald er
eneste afgangsårsag i tabelbefolkningen har vi
#+begin_export latex
\begin{align*}
\L{k} &= \text{bidrag fra overlevende + bidrag fra døde}\\
    &= k\cdot \ell_{x+k} + \a{k}\cdot \d{k}\\
    &= \a{k}\cdot\ell_x + (k- \a{k})\cdot \ell_{x+k}.
\end{align*}
#+end_export

Vi skal nu beregne den forventede restlevetid for en \(x\)-årig
tabelperson. For en nyfødt er \(x=0\) og dermed bliver den forventede
restlevetid til den forventede levetid, som betegnes med
middellevetid. Lad \(T_x\) angive den samlede levetid i
tabelbefolkningen efter \(x\)-års fødselsdagen, specielt er \(T_0\)
den samlede levetid i tabelbefolkningen. Vi beregner
#+begin_export latex
\begin{align*}
T_x &= \L{k} + \cdots + \L[x^{max}]{k}\\
    &= \a{k}\cdot\ell_x + (k- \a{k})\cdot \ell_{x+k} + \cdots + \a[x^{max}]{\infty}\cdot\ell_{x^{max}}.
\end{align*}
#+end_export
I tabelbefolkning oplever \(\ell_x\) personer deres \(x\)-års
fødselsdag, så den gennemsnitlige levetid efter \(x\)-års fødselsdagen
bliver
#+begin_export latex
\begin{equation*}
e_x=\frac{T_x}{\ell_x} = \text{gennemsnitlige restlevetid}.
\end{equation*}
#+end_export
Dette gennemsnit kaldes den forventede restlevetid for en \(x\)-årig
tabelperson. På tilsvarende vis bliver middellevetid beregnet som
#+begin_export latex
\begin{equation*}
e_0=\frac{T_0}{\ell_0} = \text{middellevetid}.
\end{equation*}
#+end_export


** Danmark statistik

Med etableringen af den personstatistiske database har Danmarks
Statistik fået nye muligheder for at beregne dødshyppighederne mere
korrekt, idet databasen for alle personer i Danmark indeholder eksakt
information om eventuel dødsdato og ind- og udvandringstidsdatoer. Der
kan således for hver enkelt person udregnes nøjagtigt, hvor mange dage
personen i en årsperiode har været i Danmark og hvor mange af dagene i
årsperioden, personen har været død. Den søgte dødshyppighed skal
præcist angive sandsynligheden for at dø på et bestemt alderstrin --
det vil sige mellem to fødselsdage. For at opnå denne hyppighed laves
der en særlig beregning for hver enkelt person fra fødselsdag til
fødselsdag i en periode, der omfatter to kalenderår. I
offentliggørelsen af middellevetid fra 19. marts 2010 er det
kalenderårene 2008 og 2009, der ligger til grund for
beregningerne. For alle personer, der var i den danske befolkning på
et eller andet tidspunkt mellem deres fødselsdag i 2008 og i 2009, er
der lavet en beregning for antallet af dage, personen var i Danmark og
antallet af dage personen var død i perioden mellem de to
fødselsdage. For personer, der ikke dør mellem to fødselsdage, vil
antallet af dage som død naturligvis være 0.  Efterfølgende laves der
en sammenlægning for personer med samme køn og alderstrin for at få
det samlede antal levedage og dødedage. Personer vil placeres på det
alderstrin, som svarer til det antal år, de fyldte i startåret,
hvilket i eksemplet vil sige 2008. En person, som fyldte 60 år 1. januar 2008 vil fx tilhøre de
60-årige. Det samme vil en person, der fyldte 60 år 31. december 2008.
Der kan altså i yderste konsekvens være næsten et års forskel mellem
den periode, som personer på samme alderstrin følges. 


** Header :noexport:

#+TITLE: Overlevelsestavler
#+AUTHOR: Anna-Vera Jørring Pallesen, Johan Sebastian Ohlendorff, Laust Hvas Mortensen and Thomas Alexander Gerds
#+DATE: 
#+LaTeX_CLASS: danish-article
#+OPTIONS: toc:nil
#+LaTeX_HEADER:\usepackage{authblk}
#+LaTeX_HEADER:\usepackage{natbib}
#+LaTeX_HEADER:\usepackage{listings}
#+LaTeX_HEADER:\usepackage{color}
#+LaTeX_HEADER:\usepackage[usenames,dvipsnames]{xcolor}
#+LaTeX_HEADER:\usepackage[utf8]{inputenc}
#+LaTeX_HEADER:\usepackage{hyperref}
#+LaTeX_HEADER:\usepackage{amssymb}
#+LaTeX_HEADER:\usepackage{latexsym}
#+OPTIONS:   H:3  num:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:t todo:t pri:nil tags:not-in-toc author:t
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://publicifsv.sund.ku.dk/~tag/styles/all-purpose.css" />
#+LATEX_HEADER: \RequirePackage{tcolorbox}
# #+LaTeX_HEADER:\usepackage[table,usenames,dvipsnames]{xcolor}
#+LaTeX_HEADER:\definecolor{lightGray}{gray}{0.98}
#+LaTeX_HEADER:\definecolor{medioGray}{gray}{0.83}
#+LATEX_HEADER:\definecolor{mygray}{rgb}{.95, 0.95, 0.95}
#+Latex_Header: \newcommand{\qxk}{\ensuremath{{}_{k}q_{x}}}
#+Latex_Header: \newcommand{\qxe}[1][x]{\ensuremath{{}_{1}q_{#1}}}
#+Latex_Header: \newcommand{\Dxk}[1][x]{\ensuremath{{}_{k}D_{#1}}}
#+Latex_Header: \renewcommand{\d}[2][x]{\ensuremath{{}_{#2}d_{#1}}}
#+Latex_Header: \newcommand{\qxf}[1][x]{\ensuremath{{}_{5}q_{#1}}}
#+Latex_Header: \newcommand{\Mxf}[1][x]{\ensuremath{{}_{5}M_{#1}}}
#+Latex_Header: \newcommand{\Mxk}[1][x]{\ensuremath{{}_{k}M_{#1}}}
#+Latex_Header: \newcommand{\Rxk}[1][x]{\ensuremath{{}_{k}R_{#1}}}
#+Latex_Header: \renewcommand{\a}[2][x]{\ensuremath{{}_{#2}a_{#1}}}
#+Latex_Header: \renewcommand{\L}[2][x]{\ensuremath{{}_{#2}L_{#1}}}
#+LATEX_HEADER:\newcommand{\mybox}[1]{\vspace{.5em}\begin{tcolorbox}[boxrule=0pt,colback=mygray] #1 \end{tcolorbox}}
