#+TITLE: Demografi: opgaver kursusuge 5
#+AUTHOR: Folkesundhedsvidenskab 2. semester
#+DATE:
#+LaTeX_HEADER:\usepackage{listings}
#+LaTeX_HEADER:\usepackage{color}
#+LaTeX_HEADER:\usepackage[usenames,dvipsnames]{xcolor}
#+LaTeX_HEADER:\usepackage[utf8]{inputenc}
#+LaTeX_HEADER:\usepackage{graphicx}
#+LaTeX_HEADER:\usepackage{hyperref}
#+LaTeX_HEADER:\usepackage{amssymb}
#+LaTeX_HEADER:\usepackage{latexsym}
#+LaTeX_HEADER:\renewcommand\theequation{K1.\arabic{equation}}
#+LaTeX_HEADER: \renewcommand{\figurename}{Figur}
#+LaTeX_HEADER:\usepackage{tcolorbox}
#+LaTeX_HEADER:\pagestyle{fancy}
#+LaTeX_HEADER:\definecolor{lightGray}{gray}{0.98}
#+LaTeX_HEADER:\definecolor{medioGray}{gray}{0.83}
#+LATEX_HEADER:\definecolor{mygray}{rgb}{.95, 0.95, 0.95}
#+LATEX_HEADER:\newcommand{\mybox}[1]{\vspace{.5em}\begin{tcolorbox}[boxrule=0pt,colback=mygray] #1 \end{tcolorbox}}
#+setupfile:~/emacs-genome/snps/org-templates/setup-demografi.org
#+superman-export-target: opgave
#+OPTIONS: :rmd_yaml:nil
#+LaTeX_CLASS: danish-article

#+begin_export html
---
title: 'Demografi: opgaver kursusuge5'
output: word_document
---
```{r setup}
knitr::opts_knit$set(root.dir = "..")
source("https://raw.githubusercontent.com/tagteam/demogRafi/main/R-scripts/demofunk.R")
```
#+end_export

* Opgave 1

1. [@1] Angiv mindst en årsag til, at de aldersspecifikke
   mortalitetsrater ikke var konstante de sidste 100 år i Danmark,
   og hvordan kan bæredygtighed og miljøpåvirkninger spille en rolle heri?
2. [@2] Angiv mindst en grund til, at de aldersspecifikke 
   mortalitetsrater ikke er konstante de næste 100 år i Danmark.
3. [@3] Hvad angiver Kapitel 3 som middelrestlevetiden for en
   7-årige pige under forudsætningen, at mortalitetsraterne
   fra 2019 holder sig på samme niveau i al fremtid for alle alderstrin? 
4. [@4] Under antagelsen at mortalitetsraterne ville følge samme kalendertidstrends 
   som de sidste 40 år (se Kapitel 2 Figur 2) i de næste 
   100 år, ville den forventede restlevetid for en 7-årige pige i 2019
   være mindre eller højere end 76,7 år?
5. [@5] Hvorfor er det forkert at fortolke 21,0 år (se Kapitel 3 afsnit 2.4) som den 
   restlevetid, som en 65-årig kvinde i 2019 kan forvente at leve?  

** Løsning                                                  :solution:ignore:
*** Besvarelse

1. Faldet i dødelige af smitsomme sygdomme pga. bedre hygiejne og
   antibiotika. Faldet i dødsfald fra ullykker på grund af bedre
   arbejdsmiljø. Fald i dødelighed fra kroniske sygdomme som fx
   hjertekarsygdomme som en konsekvens af ændrede levekår og bedre
   behandlingsmuligheder.  Miljøpåvirkninger kan påvirke
   mortalitetsraterne negativt gennem fx luft- og vandforurening,
   klimaforandringer og ekstreme vejrforhold, der kan føre til øget
   mortalitet. Samtidigt kan bæredygtighedsinitiativer påvirke
   mortalitetsraterne positivt gennem fx en kost med flere planter og
   mindre animalsk fedt, flere grønne områder der fremmer aktivitet og
   mindre miljøbelastende transport
2. Pandemier af nye sygdomme som fx HIV, COVID-19 eller fugleinfluenza. Krig og naturkatastrofer. Øget forekomsten af fedme og andre "livsstilssygdomme".    
3. 76,7 år. Middelrestlevetiden for en 7-årige pige bliver vist i afsnit 2.4 af Kapitel 3.
4. Middelrestlevetiden ville være højere, hvis mortalitetsraterne fortsætter med at falde.
5. Fordi mortalitetsraterne ikke kan antages at være konstante!

* Opgave 2
Se på formlerne for overlevelsestavler i kompendiets Kapitel 3 og besvar følgende spørgsmål:
1. [@1] Hvad er forskellen mellem \({}_1d_8\) og \({}_1D_8\)?
2. [@2] Hvilke enheder har henholdsvis \(l_x\) og \(L_x\)?
3. [@3] Hvis \(l_x\) er 273 og \({}_1d_x\) er 17, hvad er så \(l_{x+1}\)?
4. [@6] Hvorfor sætter vi Chiang's a til 0,1 i det første aldersinterval og til 0,5 (for 1-års overlevelsestavlen) i de andre aldersintervaller?
5. [@5] Indsæt formlen for Chiang's a i det sidste aldersinterval (Kapitel 3, Formel K3.2) i 
        den centrale approksimationsformel (Kapitel 3, Formel K3.1) og simplificer 
        bagefter udtrykket for dødshyppigheden i tabellens sidste aldersinterval $q_{x^{max}}$.
6. [@6] Det antages ofte, at stigningen i middellevetid over de sidste 200 år særligt skyldes faldet i spædbarnsdødeligheden. Hvorfor det en rimelig forklaring? Og hvornår kan faldet have konsekvenser for valget af værdien af Chiang's a i denne aldersgruppe?   
 
   
** Løsning                                                  :solution:ignore:
*** Besvarelse                                                     

1. [@1] \({}_1D_8\) er antal døde blandt 8-årige i den rigtige befolkning i den givne kalenderperiode, \(_{}1d_8\) er antal døde blandt 8-årige i den hypotetiske tabelbefolkning.
2. [@2] Begge størrelser hører til den hypotetiske tabelbefolkning: \(l_x\) er antal personer (enhed: personer) i starten af alderstrin \(x\), og \(L_x\) er samlet antal gennemlevet tid (enhed: personår) i aldersintervallet fra alderstrin \(x\) til næste alderstrin.
3. [@3] I starten af alderstrinnet er der 273 personer. Der dør 17 personer i aldersintervallet. Dermed er der 256 tilbage i starten af det næste aldersinterval.
4. [@6] Det gør vi fordi dødeligheden i det første leveår ikke er ligefordelt i aldersintervallet, da de fleste dødsfæld sker indenfor den første måned efter fødslen. I de andre aldersintervaller er dødeligheden omtrent ligefordelt og dermed er ``midten af aldersintervallet'' en god tilnærmelse af det gennemsnitlige antal år en person som døde i aldersintervallet var død i aldersintervallet.
5. [@5] Resultatet er \(q_x^{max} = 1\) uanset værdien af \(M_x\). Dødshyppigheden i det sidste aldersinterval er 100\%. Det betyder, at den resterende del af tabelbefolkningen dør i det sidste aldersinterval.
6. [@6] Middellevetiden er særligt påvirket af faldet i spødbarnsdødeligheden fordi dødsfald i denne aldergruppe medfører et større tab i leveår end fx et dødsfald ved alder 50. En del af forklaringen er også, at dødeligheden er lav efter første leveår og frem til midtlivet. Faldet i spædbarnsdødelighed har alene  konsekvenser for valget af værdien af Chiang's a hvis den gennemsnitlige levetid for dem, der dør i første leveår ændrer sig samtidig med, at spædbarnsdødeligheden falder.  

* Opgave 3

1. [@1] Find aldersspecifikke mortalitetsrater for mænd i 2009 i Danmark i 1-års aldersintervaller.
2. Rapporter mortalitetsraten for 0-årige og 5-årige drenge.
3. Beregn overlevelsestavlen baseret på de aldersspecifikke mortalitetsrater fra 2009 i Danmark for en radix af 100.000
   personer med Chiang's a fra Kapitel 3 (Tabel 2).
4. Rapporterer tabellens værdi i kolonne =e= for alderstrinnene 0 og 84 år.

** Instruks                                                 :instruks:ignore:
*** Instruks

Find R-koder for mortalitetsrater og overlevelsestavlen med 1-års
alderstrin i Kapitel 3 og indsæt dem her med copy-og-paste
metoden. Tilpas koderne sådan at de besvarer opgaven.

** Løsningen :solution:ignore:

#+BEGIN_SRC R  :results output raw drawer :exports (exercise-with-solutions) :session *R* :cache yes :eval (never-plain-export)
## 
x1 <- hent_mortalitetsrate_data(tid = 2009,
                               breaks = c(0:99,Inf),
                               køn = "mænd",
                               right = FALSE, 
                               alder = "all_no_total")
x1 <- mutate(x1,M = Dod/R)
x1
#+END_SRC

#+RESULTS[(2024-03-05 18:00:17) 0c0f23bef448d4c51fda3848ac3327cc0127dbcb]:
:results:
# A tibble: 100 × 6
   aldersinterval KØN     TID     R   Dod         M
   <fct>          <chr> <dbl> <dbl> <dbl>     <dbl>
 1 0              Mænd   2009 33373   103 0.00309  
 2 1-1            Mænd   2009 33573     9 0.000268 
 3 2-2            Mænd   2009 33499     2 0.0000597
 4 3-3            Mænd   2009 33557     1 0.0000298
 5 4-4            Mænd   2009 33462     4 0.000120 
 6 5-5            Mænd   2009 33735     1 0.0000296
 7 6-6            Mænd   2009 33090     3 0.0000907
 8 7-7            Mænd   2009 33168     3 0.0000904
 9 8-8            Mænd   2009 34420     2 0.0000581
10 9-9            Mænd   2009 34360     1 0.0000291
# ℹ 90 more rows
# ℹ Use `print(n = ...)` to see more rows
:end:

#+BEGIN_SRC R  :results output raw drawer :exports (exercise-with-solutions) :session *R* :cache yes :eval (never-plain-export)
x1 <- mutate(x1,a = c(0.1,rep(0.5,99)),k = rep(1,100))
tavle_mænd_1 <- overlevelsestavle(x1,
                                     mortalitet = "M",
                                     alder = "aldersinterval")
print(tavle_mænd_1,digits = 2,n = 100)
#+END_SRC

#+RESULTS[(2024-03-05 18:02:39) eeb55df96145f63060683696901430a01c39523c]:
:results:
# A tibble: 100 × 9
    Alder      l     d     p         q       o     L        T     e
    <fct>  <dbl> <dbl> <dbl>     <dbl>   <dbl> <dbl>    <dbl> <dbl>
  1 0     100000   308 0.997 0.00308   1       99723 7684031. 76.8 
  2 1-1    99692    27 1.00  0.000268  0.997   99679 7584308. 76.1 
  3 2-2    99666     6 1.00  0.0000597 0.997   99663 7484629. 75.1 
  4 3-3    99660     3 1.00  0.0000298 0.997   99658 7384967. 74.1 
  5 4-4    99657    12 1.00  0.000120  0.997   99651 7285309. 73.1 
  6 5-5    99645     3 1.00  0.0000296 0.996   99643 7185658. 72.1 
  7 6-6    99642     9 1.00  0.0000907 0.996   99637 7086015. 71.1 
  8 7-7    99633     9 1.00  0.0000904 0.996   99628 6986378. 70.1 
  9 8-8    99624     6 1.00  0.0000581 0.996   99621 6886749. 69.1 
 10 9-9    99618     3 1.00  0.0000291 0.996   99616 6787129. 68.1 
 11 10-10  99615     3 1.00  0.0000288 0.996   99614 6687512. 67.1 
 12 11-11  99612     9 1.00  0.0000869 0.996   99608 6587899. 66.1 
 13 12-12  99603    17 1.00  0.000168  0.996   99595 6488291. 65.1 
 14 13-13  99587     8 1.00  0.0000824 0.996   99583 6388696. 64.2 
 15 14-14  99579    11 1.00  0.000108  0.996   99573 6289113. 63.2 
 16 15-15  99568    14 1.00  0.000138  0.996   99561 6189540. 62.2 
 17 16-16  99554    38 1.00  0.000386  0.996   99535 6089979. 61.2 
 18 17-17  99516    39 1.00  0.000394  0.995   99496 5990444. 60.2 
 19 18-18  99477    57 0.999 0.000571  0.995   99448 5890948. 59.2 
 20 19-19  99420    44 1.00  0.000439  0.994   99398 5791500. 58.3 
 21 20-20  99376    44 1.00  0.000444  0.994   99354 5692102. 57.3 
 22 21-21  99332    39 1.00  0.000396  0.993   99312 5592748. 56.3 
 23 22-22  99293    79 0.999 0.000795  0.993   99253 5493436. 55.3 
 24 23-23  99214    64 0.999 0.000649  0.992   99182 5394182. 54.4 
 25 24-24  99149    57 0.999 0.000576  0.991   99121 5295001. 53.4 
 26 25-25  99092    88 0.999 0.000884  0.991   99048 5195880. 52.4 
 27 26-26  99005    74 0.999 0.000750  0.990   98967 5096832. 51.5 
 28 27-27  98930    80 0.999 0.000806  0.989   98890 4997864. 50.5 
 29 28-28  98851    69 0.999 0.000702  0.989   98816 4898974. 49.6 
 30 29-29  98781    63 0.999 0.000636  0.988   98750 4800158. 48.6 
 31 30-30  98718    78 0.999 0.000795  0.987   98679 4701408. 47.6 
 32 31-31  98640    68 0.999 0.000691  0.986   98606 4602729. 46.7 
 33 32-32  98572    77 0.999 0.000778  0.986   98533 4504123. 45.7 
 34 33-33  98495    81 0.999 0.000824  0.985   98455 4405589. 44.7 
 35 34-34  98414   102 0.999 0.00104   0.984   98363 4307135. 43.8 
 36 35-35  98312    80 0.999 0.000813  0.983   98272 4208772. 42.8 
 37 36-36  98232   104 0.999 0.00105   0.982   98180 4110500. 41.8 
 38 37-37  98128   108 0.999 0.00110   0.981   98074 4012320. 40.9 
 39 38-38  98020   157 0.998 0.00160   0.980   97941 3914246. 39.9 
 40 39-39  97862   147 0.998 0.00151   0.979   97789 3816305. 39.0 
 41 40-40  97715   131 0.999 0.00134   0.977   97650 3718517. 38.1 
 42 41-41  97584   155 0.998 0.00159   0.976   97507 3620867. 37.1 
 43 42-42  97430   199 0.998 0.00204   0.974   97330 3523360. 36.2 
 44 43-43  97231   218 0.998 0.00224   0.972   97122 3426030. 35.2 
 45 44-44  97013   182 0.998 0.00188   0.970   96921 3328908. 34.3 
 46 45-45  96830   203 0.998 0.00210   0.968   96729 3231987. 33.4 
 47 46-46  96627   241 0.998 0.00249   0.966   96507 3135258. 32.4 
 48 47-47  96386   290 0.997 0.00301   0.964   96241 3038752. 31.5 
 49 48-48  96096   331 0.997 0.00345   0.961   95931 2942510. 30.6 
 50 49-49  95765   346 0.996 0.00362   0.958   95592 2846580. 29.7 
 51 50-50  95419   390 0.996 0.00408   0.954   95224 2750988. 28.8 
 52 51-51  95029   459 0.995 0.00483   0.950   94800 2655764. 27.9 
 53 52-52  94570   536 0.994 0.00567   0.946   94302 2560964. 27.1 
 54 53-53  94034   587 0.994 0.00624   0.940   93741 2466662. 26.2 
 55 54-54  93448   592 0.994 0.00634   0.934   93151 2372921. 25.4 
 56 55-55  92855   744 0.992 0.00801   0.929   92483 2279769. 24.6 
 57 56-56  92111   733 0.992 0.00796   0.921   91745 2187286. 23.7 
 58 57-57  91378   718 0.992 0.00785   0.914   91019 2095542. 22.9 
 59 58-58  90660   836 0.991 0.00923   0.907   90242 2004523. 22.1 
 60 59-59  89824   879 0.990 0.00979   0.898   89384 1914281. 21.3 
 61 60-60  88944   976 0.989 0.0110    0.889   88456 1824897. 20.5 
 62 61-61  87969  1065 0.988 0.0121    0.880   87436 1736440. 19.7 
 63 62-62  86903  1084 0.988 0.0125    0.869   86361 1649005. 19.0 
 64 63-63  85819  1132 0.987 0.0132    0.858   85253 1562643. 18.2 
 65 64-64  84687  1359 0.984 0.0161    0.847   84007 1477390. 17.4 
 66 65-65  83328  1351 0.984 0.0162    0.833   82652 1393383. 16.7 
 67 66-66  81977  1366 0.983 0.0167    0.820   81293 1310731. 16.0 
 68 67-67  80610  1581 0.980 0.0196    0.806   79820 1229437. 15.3 
 69 68-68  79029  1605 0.980 0.0203    0.790   78226 1149618. 14.5 
 70 69-69  77424  1727 0.978 0.0223    0.774   76560 1071392. 13.8 
 71 70-70  75696  2000 0.974 0.0264    0.757   74696  994832. 13.1 
 72 71-71  73696  1902 0.974 0.0258    0.737   72745  920136. 12.5 
 73 72-72  71794  2175 0.970 0.0303    0.718   70707  847390. 11.8 
 74 73-73  69619  2352 0.966 0.0338    0.696   68443  776684. 11.2 
 75 74-74  67268  2623 0.961 0.0390    0.673   65956  708241. 10.5 
 76 75-75  64645  2848 0.956 0.0441    0.646   63221  642284.  9.94
 77 76-76  61797  2893 0.953 0.0468    0.618   60351  579063.  9.37
 78 77-77  58904  3104 0.947 0.0527    0.589   57352  518713.  8.81
 79 78-78  55800  3391 0.939 0.0608    0.558   54104  461361.  8.27
 80 79-79  52409  3425 0.935 0.0654    0.524   50696  407257.  7.77
 81 80-80  48984  3462 0.929 0.0707    0.490   47253  356560.  7.28
 82 81-81  45522  3608 0.921 0.0793    0.455   43718  309307.  6.79
 83 82-82  41914  3790 0.910 0.0904    0.419   40019  265589.  6.34
 84 83-83  38123  3810 0.900 0.0999    0.381   36218  225571.  5.92
 85 84-84  34313  3854 0.888 0.112     0.343   32386  189352.  5.52
 86 85-85  30459  3569 0.883 0.117     0.305   28674  156966.  5.15
 87 86-86  26890  3624 0.865 0.135     0.269   25078  128292.  4.77
 88 87-87  23266  3431 0.853 0.147     0.233   21551  103214.  4.44
 89 88-88  19836  3282 0.835 0.165     0.198   18195   81663.  4.12
 90 89-89  16554  2783 0.832 0.168     0.166   15162   63468.  3.83
 91 90-90  13771  2807 0.796 0.204     0.138   12367   48306.  3.51
 92 91-91  10964  2642 0.759 0.241     0.110    9643   35939.  3.28
 93 92-92   8322  1951 0.766 0.234     0.0832   7347   26296.  3.16
 94 93-93   6371  1694 0.734 0.266     0.0637   5524   18950.  2.97
 95 94-94   4678  1258 0.731 0.269     0.0468   4049   13425.  2.87
 96 95-95   3420   909 0.734 0.266     0.0342   2965    9377.  2.74
 97 96-96   2510   766 0.695 0.305     0.0251   2127    6411.  2.55
 98 97-97   1744   618 0.645 0.355     0.0174   1435    4284.  2.46
 99 98-98   1126   341 0.698 0.302     0.0113    956    2849.  2.53
100 99+      785   785 0     1         0.00785  1893    1893.  2.41
:end:

2. [@2] Rapporter mortalitetsraten for 0-årige og 5-årige drenge.

Mortalitetsraten for 0-årige drenge var 3,1 døde/1000 personår og for 5-årige drenge 0,03 døde/1000 personår i 2009.

4. [@4] Rapporterer tabellens værdi i kolonne =e= for alderstrinnene 0 og 84 år:
   
Middellevetiden for mænd i 2009 i Danmark er 76,8 år under antagelsen,
at de aldersspecifikke mortalitetsrater fra 2009 ikke ændrer sig i
fremtiden.  Den forventede middelrestlevetid af 84-årige mænd i 2009 i
Danmark er 5,9 år under antagelsen, at de aldersspecifikke
mortalitetsrater fra 2009 ikke ændrer sig i fremtiden.
