#+TITLE: Demografi: opgaver 5
#+AUTHOR: Folkesundhedsvidenskab 2. semester
#+DATE:
#+LaTeX_HEADER:\usepackage{listings}
#+LaTeX_HEADER:\usepackage{color}
#+LaTeX_HEADER:\usepackage[usenames,dvipsnames]{xcolor}
#+LaTeX_HEADER:\usepackage[utf8]{inputenc}
#+LaTeX_HEADER:\usepackage{graphicx}
#+LaTeX_HEADER:\usepackage{hyperref}
#+LaTeX_HEADER:\usepackage{amssymb}
#+LaTeX_HEADER:\usepackage{latexsym}
#+LaTeX_HEADER:\renewcommand\theequation{K1.\arabic{equation}}
#+LaTeX_HEADER: \renewcommand{\figurename}{Figur}
#+LaTeX_HEADER:\usepackage{tcolorbox}
#+LaTeX_HEADER:\pagestyle{fancy}
#+LaTeX_HEADER:\definecolor{lightGray}{gray}{0.98}
#+LaTeX_HEADER:\definecolor{medioGray}{gray}{0.83}
#+LATEX_HEADER:\definecolor{mygray}{rgb}{.95, 0.95, 0.95}
#+LATEX_HEADER:\newcommand{\mybox}[1]{\vspace{.5em}\begin{tcolorbox}[boxrule=0pt,colback=mygray] #1 \end{tcolorbox}}
#+setupfile:~/emacs-genome/snps/org-templates/setup-demografi.org
#+superman-export-target: opgave
#+OPTIONS: :rmd_yaml:nil
#+LaTeX_CLASS: danish-article

#+begin_export html
---
title: 'Demografi: opgaver 5'
output: word_document
---
```{r setup}
knitr::opts_knit$set(root.dir = "..")
source("https://raw.githubusercontent.com/tagteam/demogRafi/main/R-scripts/demofunk.R")
```
#+end_export

* Opgave 1

1. [@1] Angiv mindst en årsag til, hvorfor de aldersspecifikke
   mortalitetsrater ikke var konstant de sidste 100 år i Danmark.
2. [@2] Beskriv mindst en grund til, hvorfor de aldersspecifikke 
   mortalitetsrater ikke ville være konstant de næste 100 år i Danmark.
3. [@3] Hvilket tal i kompendiets Kapitel 3 angiver middelrestlevetid for en
   7-årige pige under forudsætningen at mortalitetsraterne
   fra 2019 holder sig på samme niveau i al fremtid  for alle alderstrin? 
4. [@4] Under antagelsen at mortalitetsraterne ville følge samme kalendertidstrends 
   som de sidste 40 år (se Kapitel 2 Figur 2) også de næste 
   100 år, ville den forventede restlevetid for en 7-årige pige i 2019
   være mindre eller højere end 76,9 år?
5. [@5] Hvorfor er det forkert at fortolke 21,2 år (se Kapitel 3 afsnit 2.4) som den 
   middelrestlevetid, som en 65-årige kvinde i 2019 kan forvente at leve?  

** Løsning                                                  :solution:ignore:
*** Besvarelse

1. Penicillin
2. Pandemi
3. 76,9 år. Middelrestlevetid for en 7-årige pige bliver vist i Kapitel 3 afsnit 2.4.
4. Middelrestlevetiden ville være højere, hvis mortalitetsrater fortsætter med at falde.
5. Fordi mortalitetsraterne kommer til at ændre sig! Den rigtige fortolkning er: 21,2 år er den forventede restlevetid for en 11 årige dreng, hvis mortalitetsraterne fra 2008/2009 ville holde sig konstant i al fremtid.

* Opgave 2
Se på formlerne for overlevelsestavler i kompendiets Kapitel 3 og besvar følgende spørgsmål:
1. [@1] Hvad er forskellen mellem \({}_1d_8\) og \({}_1D_8\)?
2. [@2] Hvilke endheder har henholdsvis \(l_x\) og \(L_x\)?
3. [@3] Hvis \(l_x\) er 273 og \({}_1d_x\) er 17, hvad er så \(l_{x+1}\)?
4. [@6] Hvorfor sætter vi Chiang's a til 0,1 i det første aldersinterval og til 0,5 (for 1-års overlevelsestavlen) i de andre intervaller?
5. [@5] Indsæt formlen for Chiang's a i det sidste aldersinterval (Kapitel 3, Formel K3.2) i 
        den centrale approksimationsformel (Kapitel 3, Formel K3.1) og simplificer 
        bagefter udtrykket for dødshyppigheden i tabellens sidste aldersinterval $q_{x^{max}}$.
 
   
** Løsning                                                  :solution:ignore:
*** Besvarelse                                                     

1. [@1] \({}_1D_81\) er antal døde blandt 81-årige i den rigtige befolkningen i den givne kalenderperiode, \(_{}1d_81\) er antal døde blandt 81-årige i den hypotetiske tabelbefolkning.
2. [@2] Begge størrelser hører til den hypotetiske tabelbefolkning: \(l_x\) er antal personer (enhed: personer) i starten af alderstrin \(x\), og \(L_x\) er antal gennemlevede tid (enhed: personår) i intervallet fra alderstrin \(x\) til næste alderstrin.
3. [@3] I starten af alderstrin er der 273 personer. Der dør 17 personer i intervallet. Dermed er der 256 tilbage i starten af det næste aldersinterval.
4. [@6] Det gør vi fordi dødeligheden i det første leveår ikke er ligfordelt på intervallet, da de fleste dødsfæld sker indenfor den første måned efter fødslen. I de andre aldersintervaller er dødeligheden omtrent ligfordelt og dermed er ``midten af intervallet'' en god tilnærmelse af det gennemsnitlige antal år en person som døde i intervallet var døde i intervallet.
5. [@5] Resultatet er \(q_x^{max} = 1\) uanset værdien af \(M_x\). Dødshyppigheden i det sidste aldersinterval er 100\%. Det betyder at den resterende del af tabelbefolkningen dør i det sidste aldersinterval.

* Opgave 3

1. [@1] Find aldersspecifikke mortalitetsrater for mænd i 2009 i Danmark i 1-års aldersintervaller.
2. Rapporter mortalitetsraten for 0-årige og 5-årige drenge.
3. Beregn overlevelsestavlen baseret på de aldersspecifikke mortalitetsrater fra 2009 i Danmark, og for en radix af 100.000
   personer, Chiang's a fra Kapitel 3 (Tabel 2).
4. Rapporterer tabellens værdi i kolonne =e= for alderstrin 0 år og for 84 år.

** Instruks                                                 :instruks:ignore:
*** Instruks

Find R-koder for mortalitetsrater og overlevelsestavlen med 1-års
alderstrin i Kapitel 3 og indsæt dem her med copy-og-paste
metoden. Tilpas koderne sådan at de besvarer opgaven.

** Løsningen :solution:ignore:

#+BEGIN_SRC R  :results output raw drawer :exports (exercise-with-solutions) :session *R* :cache yes :eval (never-plain-export)
## 
x1 <- hent_mortalitetsrate_data(tid = 2009,
                               breaks = c(0:99,Inf),
                               køn = "mænd",
                               right = FALSE,
                               alder = "all_no_total")
x1 <- mutate(x1,M = Dod/R)
x1
#+END_SRC

#+RESULTS[(2024-03-05 18:00:17) 0c0f23bef448d4c51fda3848ac3327cc0127dbcb]:
:results:
# A tibble: 100 × 6
   aldersinterval KØN     TID     R   Dod         M
   <fct>          <chr> <dbl> <dbl> <dbl>     <dbl>
 1 0              Mænd   2009 33373   103 0.00309  
 2 1-1            Mænd   2009 33573     9 0.000268 
 3 2-2            Mænd   2009 33499     2 0.0000597
 4 3-3            Mænd   2009 33557     1 0.0000298
 5 4-4            Mænd   2009 33462     4 0.000120 
 6 5-5            Mænd   2009 33735     1 0.0000296
 7 6-6            Mænd   2009 33090     3 0.0000907
 8 7-7            Mænd   2009 33168     3 0.0000904
 9 8-8            Mænd   2009 34420     2 0.0000581
10 9-9            Mænd   2009 34360     1 0.0000291
# ℹ 90 more rows
# ℹ Use `print(n = ...)` to see more rows
:end:

#+BEGIN_SRC R  :results output raw drawer :exports (exercise-with-solutions) :session *R* :cache yes :eval (never-plain-export)
x1 <- mutate(x1,a = c(0.1,rep(1,99)),k = rep(1,100))
tavle_mænd_1 <- overlevelsestavle(x1,
                                     mortalitet = "M",
                                     alder = "aldersinterval")
print(tavle_mænd_1,digits = 2,n = 100)
#+END_SRC

#+RESULTS[(2024-03-05 18:02:39) eeb55df96145f63060683696901430a01c39523c]:
:results:
# A tibble: 100 × 9
    Alder      l     d     p         q       o     L        T     e
    <fct>  <dbl> <dbl> <dbl>     <dbl>   <dbl> <dbl>    <dbl> <dbl>
  1 0     100000   308 0.997 0.00308   1       99723 7709132. 77.1 
  2 1-1    99692    27 1.00  0.000268  0.997   99692 7609409. 76.3 
  3 2-2    99665     6 1.00  0.0000597 0.997   99665 7509717. 75.3 
  4 3-3    99660     3 1.00  0.0000298 0.997   99660 7410051. 74.4 
  5 4-4    99657    12 1.00  0.000120  0.997   99657 7310392. 73.4 
  6 5-5    99645     3 1.00  0.0000296 0.996   99645 7210735. 72.4 
  7 6-6    99642     9 1.00  0.0000907 0.996   99642 7111091. 71.4 
  8 7-7    99633     9 1.00  0.0000904 0.996   99633 7011449. 70.4 
  9 8-8    99624     6 1.00  0.0000581 0.996   99624 6911816. 69.4 
 10 9-9    99618     3 1.00  0.0000291 0.996   99618 6812192. 68.4 
 11 10-10  99615     3 1.00  0.0000288 0.996   99615 6712575. 67.4 
 12 11-11  99612     9 1.00  0.0000869 0.996   99612 6612960. 66.4 
 13 12-12  99603    17 1.00  0.000168  0.996   99603 6513348. 65.4 
 14 13-13  99587     8 1.00  0.0000824 0.996   99587 6413744. 64.4 
 15 14-14  99579    11 1.00  0.000108  0.996   99579 6314157. 63.4 
 16 15-15  99568    14 1.00  0.000138  0.996   99568 6214579. 62.4 
 17 16-16  99554    38 1.00  0.000386  0.996   99554 6115011. 61.4 
 18 17-17  99516    39 1.00  0.000394  0.995   99516 6015457. 60.4 
 19 18-18  99476    57 0.999 0.000571  0.995   99476 5915941. 59.5 
 20 19-19  99420    44 1.00  0.000439  0.994   99420 5816465. 58.5 
 21 20-20  99376    44 1.00  0.000444  0.994   99376 5717045. 57.5 
 22 21-21  99332    39 1.00  0.000396  0.993   99332 5617669. 56.6 
 23 22-22  99293    79 0.999 0.000795  0.993   99293 5518337. 55.6 
 24 23-23  99214    64 0.999 0.000650  0.992   99214 5419045. 54.6 
 25 24-24  99149    57 0.999 0.000576  0.991   99149 5319831. 53.7 
 26 25-25  99092    88 0.999 0.000884  0.991   99092 5220682. 52.7 
 27 26-26  99004    74 0.999 0.000750  0.990   99004 5121590. 51.7 
 28 27-27  98930    80 0.999 0.000806  0.989   98930 5022585. 50.8 
 29 28-28  98850    69 0.999 0.000702  0.988   98850 4923655. 49.8 
 30 29-29  98781    63 0.999 0.000636  0.988   98781 4824805. 48.8 
 31 30-30  98718    79 0.999 0.000795  0.987   98718 4726024. 47.9 
 32 31-31  98640    68 0.999 0.000691  0.986   98640 4627305. 46.9 
 33 32-32  98571    77 0.999 0.000778  0.986   98571 4528666. 45.9 
 34 33-33  98495    81 0.999 0.000824  0.985   98495 4430094. 45.0 
 35 34-34  98414   102 0.999 0.00104   0.984   98414 4331600. 44.0 
 36 35-35  98311    80 0.999 0.000813  0.983   98311 4233186. 43.1 
 37 36-36  98231   104 0.999 0.00105   0.982   98231 4134875. 42.1 
 38 37-37  98128   108 0.999 0.00111   0.981   98128 4036644. 41.1 
 39 38-38  98019   157 0.998 0.00161   0.980   98019 3938516. 40.2 
 40 39-39  97862   147 0.998 0.00151   0.979   97862 3840497. 39.2 
 41 40-40  97714   131 0.999 0.00134   0.977   97714 3742635. 38.3 
 42 41-41  97583   155 0.998 0.00159   0.976   97583 3644921. 37.4 
 43 42-42  97429   199 0.998 0.00204   0.974   97429 3547337. 36.4 
 44 43-43  97229   218 0.998 0.00224   0.972   97229 3449909. 35.5 
 45 44-44  97011   182 0.998 0.00188   0.970   97011 3352680. 34.6 
 46 45-45  96829   204 0.998 0.00210   0.968   96829 3255668. 33.6 
 47 46-46  96625   241 0.998 0.00250   0.966   96625 3158840. 32.7 
 48 47-47  96384   290 0.997 0.00301   0.964   96384 3062215. 31.8 
 49 48-48  96094   332 0.997 0.00345   0.961   96094 2965831. 30.9 
 50 49-49  95762   347 0.996 0.00362   0.958   95762 2869737. 30.0 
 51 50-50  95415   390 0.996 0.00409   0.954   95415 2773975. 29.1 
 52 51-51  95025   460 0.995 0.00484   0.950   95025 2678560. 28.2 
 53 52-52  94565   537 0.994 0.00568   0.946   94565 2583536. 27.3 
 54 53-53  94027   589 0.994 0.00626   0.940   94027 2488971. 26.5 
 55 54-54  93439   594 0.994 0.00636   0.934   93439 2394944. 25.6 
 56 55-55  92845   747 0.992 0.00805   0.928   92845 2301505. 24.8 
 57 56-56  92098   736 0.992 0.00799   0.921   92098 2208660. 24.0 
 58 57-57  91361   720 0.992 0.00789   0.914   91361 2116563. 23.2 
 59 58-58  90641   840 0.991 0.00927   0.906   90641 2025201. 22.3 
 60 59-59  89801   883 0.990 0.00984   0.898   89801 1934561. 21.5 
 61 60-60  88917   981 0.989 0.0110    0.889   88917 1844760. 20.7 
 62 61-61  87937  1072 0.988 0.0122    0.879   87937 1755842. 20.0 
 63 62-62  86865  1090 0.987 0.0126    0.869   86865 1667906. 19.2 
 64 63-63  85775  1139 0.987 0.0133    0.858   85775 1581041. 18.4 
 65 64-64  84635  1369 0.984 0.0162    0.846   84635 1495266. 17.7 
 66 65-65  83266  1361 0.984 0.0163    0.833   83266 1410631. 16.9 
 67 66-66  81905  1377 0.983 0.0168    0.819   81905 1327365. 16.2 
 68 67-67  80528  1595 0.980 0.0198    0.805   80528 1245460. 15.5 
 69 68-68  78933  1620 0.979 0.0205    0.789   78933 1164931. 14.8 
 70 69-69  77313  1744 0.977 0.0226    0.773   77313 1085998. 14.0 
 71 70-70  75569  2024 0.973 0.0268    0.756   75569 1008685. 13.3 
 72 71-71  73545  1923 0.974 0.0261    0.735   73545  933116. 12.7 
 73 72-72  71622  2203 0.969 0.0308    0.716   71622  859571. 12.0 
 74 73-73  69419  2385 0.966 0.0344    0.694   69419  787949. 11.4 
 75 74-74  67034  2666 0.960 0.0398    0.670   67034  718529. 10.7 
 76 75-75  64369  2900 0.955 0.0450    0.644   64369  651495. 10.1 
 77 76-76  61469  2946 0.952 0.0479    0.615   61469  587127.  9.55
 78 77-77  58523  3168 0.946 0.0541    0.585   58523  525658.  8.98
 79 78-78  55355  3469 0.937 0.0627    0.554   55355  467135.  8.44
 80 79-79  51886  3505 0.932 0.0676    0.519   51886  411780.  7.94
 81 80-80  48380  3544 0.927 0.0733    0.484   48380  359895.  7.44
 82 81-81  44836  3701 0.917 0.0825    0.448   44836  311515.  6.95
 83 82-82  41135  3896 0.905 0.0947    0.411   41135  266679.  6.48
 84 83-83  37239  3918 0.895 0.105     0.372   37239  225544.  6.06
 85 84-84  33322  3966 0.881 0.119     0.333   33322  188304.  5.65
 86 85-85  29356  3653 0.876 0.124     0.294   29356  154983.  5.28
 87 86-86  25702  3714 0.856 0.144     0.257   25702  125627.  4.89
 88 87-87  21988  3500 0.841 0.159     0.220   21988   99925.  4.54
 89 88-88  18488  3335 0.820 0.180     0.185   18488   77936.  4.22
 90 89-89  15153  2781 0.816 0.184     0.152   15153   59449.  3.92
 91 90-90  12372  2808 0.773 0.227     0.124   12372   44296.  3.58
 92 91-91   9564  2620 0.726 0.274     0.0956   9564   31924.  3.34
 93 92-92   6944  1844 0.734 0.266     0.0694   6944   22360.  3.22
 94 93-93   5100  1564 0.693 0.307     0.051    5100   15416.  3.02
 95 94-94   3536  1099 0.689 0.311     0.0354   3536   10316.  2.92
 96 95-95   2438   748 0.693 0.307     0.0244   2438    6780.  2.78
 97 96-96   1690   609 0.640 0.360     0.0169   1690    4342.  2.57
 98 97-97   1082   466 0.569 0.431     0.0108   1082    2652.  2.45
 99 98-98    615   219 0.644 0.356     0.00615   615    1570.  2.55
100 99+      396   396 0     1         0.00396   955     955.  2.41
:end:

2. [@2] Rapporter mortalitetsraten for 0-årige og 5-årige drenge.
4. [@4] Rapporterer tabellens værdi i kolonne =e= for alderstrin 0 år og for 84 år:
        Middellevetiden for mænd i 2009 i Danmark er 77,1 år, under antagelsen
        at de aldersspecifikke mortalitetsrater fra 2009 ikke ændrer sig i al fremtid.
        Den forvente middelrestlevetid af 84 årige mænd i 2009 i Danmark er 5,6 år, under antagelsen
        at de aldersspecifikke mortalitetsrater fra 2009 ikke ændrer sig i al fremtid.
