#+TITLE: Demografi: opgaver kursusuge 7
#+AUTHOR: Folkesundhedsvidenskab 2. semester
#+DATE:
#+LaTeX_HEADER:\usepackage{listings}
#+LaTeX_HEADER:\usepackage{color}
#+LaTeX_HEADER:\usepackage[usenames,dvipsnames]{xcolor}
#+LaTeX_HEADER:\usepackage[utf8]{inputenc}
#+LaTeX_HEADER:\usepackage{graphicx}
#+LaTeX_HEADER:\usepackage{hyperref}
#+LaTeX_HEADER:\usepackage{amssymb}
#+LaTeX_HEADER:\usepackage{latexsym}
#+LaTeX_HEADER:\renewcommand\theequation{K1.\arabic{equation}}
#+LaTeX_HEADER: \renewcommand{\figurename}{Figur}
#+LaTeX_HEADER:\usepackage{tcolorbox}
#+LaTeX_HEADER:\pagestyle{fancy}
#+LaTeX_HEADER:\definecolor{lightGray}{gray}{0.98}
#+LaTeX_HEADER:\definecolor{medioGray}{gray}{0.83}
#+LATEX_HEADER:\definecolor{mygray}{rgb}{.95, 0.95, 0.95}
#+LATEX_HEADER:\newcommand{\mybox}[1]{\vspace{.5em}\begin{tcolorbox}[boxrule=0pt,colback=mygray] #1 \end{tcolorbox}}
#+setupfile:~/emacs-genome/snps/org-templates/setup-demografi.org
#+superman-export-target: opgave
#+OPTIONS: :rmd_yaml:nil
#+LaTeX_CLASS: danish-article

#+begin_export html
---
title: 'Demografi: opgaver kursusuge 7'
output: word_document
---
```{r setup}
knitr::opts_knit$set(root.dir = "..")
source("https://raw.githubusercontent.com/tagteam/demogRafi/main/R-scripts/demofunk.R")
```
#+end_export

* Opgave 1

1. Find register =DODA1= i browseren: https://www.statistikbanken.dk/.
   Hvorfor angiver man alderstrin 0-1 separat fra alderstrin 1-4?
2. [@2] Find antal mænd og kvinder, som døde på grund af
   psykiske lidelser i 2018. Beregn de summariske årsagsspecifikke 
   mortalitetsrater separat for mænd og kvinder (årsag = psykiske lidelser). 
3. [@3] Hvorfor er det ikke helt fair at sammenligne mænd og kvinder
   med hensyn til de summariske rater af dødsfald på grund af psykiske
   lidelse?
4. [@4] Brug tal fra statistikbanken til at beregne
   aldersstandardiserede rater af dødsfald på grund af psykiske lidelser,
   via direkte standardisering, separat for kvinder og
   mænd. Standardiser begge rater med hensyn til aldersfordelingen af
   alle danskere i 2018. Rapporter resultaterne og diskuter forskellene
   mellem de summariske og de standardiserede rater.

** Instruks :ignore:rmd:

2. [@2] Beregningen kræver 4 tal fra statistikbanken (2 for mænd og 2 for kvinder).
   Det er nemt at skrive de 4 tal ind i en R-chunk. Alternativt kan I bruge funktionen =hent_data=.
4. [@4] Først henter I de aldersspecifikke antal døde på grund af psykiske
   lidelser separat for hver køn fra statistikbankens DODA1. Bagefter
   henter I aldersfordelingen af risikotiden (via middelfolketal og
   metode 1) for alle danskere i 2018 fra FOLK1a:

#+BEGIN_SRC R  :results output raw drawer :exports  (exercise-with-code) :session *R* :cache yes :eval (never-plain-export)  
# antal dod pga psykiske lidelser
dpl <- hent_data("doda1",årsag = "A06",tid = 2018,køn = 1:2,alder = "all_no_total")
# rename
dpl <- rename(dpl,antal_dod_psyk = INDHOLD,aldersinterval = alder)
# begræns til variable som skal bruges
dpl <- select(dpl,aldersinterval,antal_dod_psyk,KØN)
# middelfolketal begge køn og også total
N <- hent_data("folk1a",tid = "2018K3",køn = c(1:2,"TOT"),alder = "all_no_total")
# metode 1 giver riskotid
N <- rename(N,R = INDHOLD)
# kategorisere i samme intervaller som data dpl
R <- intervAlder(N,breaks = c(0,1,seq(5,85,5),Inf),right = FALSE,by = "KØN",vars = "R",label_last = "85")
# beregn aldersfordeling af risikotid blandt alle dansker
V <- filter(R,KØN == "I alt") %>% mutate(V=R/sum(R)) %>% select(aldersinterval,V)
# join vægte med køn-specifik risikotid
dat <- left_join(filter(R,KØN != "I alt"),V,by = "aldersinterval")
# 
dat <- left_join(dpl,dat,by = c("aldersinterval","KØN"))
# 
# Direkte standardisering
#
# 1. beregn aldersspecifikke rater
dat <- mutate(dat,rate_dod_psyk =  # dine koder her
# 2. beregn alderstandardiserede rater
dat <- dat %>% group_by(KØN) %>% summarise( # dine koder her
#+END_SRC

** Løsning                                                  :solution:ignore:
*** Besvarelse

1. Fordi det forventede antal år levet i intervallet af en, som dør i intervallet, er meget lavt på grund af perinatal, neonatal, post-neonatal og spædbarnsdødelighed. 
2. [@2] Risikotid i 2018 for kvinder og mænd var hhv., 2908 og 2882 tusind
   personår. De summariske mortalitetsrater for dødsfald på grund af
   psykiske lidelser er:
 - Kvinder: 2313/2908337 = 0,80 per 1000 personår
 - Mænd: 1556/2881620 =0,54 per 1000 personår
3. [@3] Fordi kvinder bliver ældre end mænd, og dødsfald på grund af en psykiske lidelse,
   forekommer hyppigt blandt ældre mennesker. 
4. [@4] De aldersstandardiserede rater af dødsfald på grund af psykiske
   lidelser i 2018 med hele den danske befolkning som
   standardbefolkning var 0,659 per 1000 personår for mænd og 0,651
   per 1000 personår for kvinder. Her er koderne:

#+BEGIN_SRC R  :results output raw drawer :exports   (exercise-with-solutions) :session *R* :cache yes :eval (never-plain-export)  
# antal døde pga psykiske lidelser
dpl <- hent_data("doda1",årsag = "A06",tid = 2018,køn = 1:2,alder = "all_no_total")
# omdoeb INDHOLD og alder til antal_dod_psyk og aldersinterval
dpl <- rename(dpl,antal_dod_psyk = INDHOLD,aldersinterval = alder)
# begræns til variable som skal bruges
dpl <- select(dpl,aldersinterval,antal_dod_psyk,KØN)
# middelfolketal begge køn og også total
N <- hent_data("folk1a",tid = "2018K3",køn = c(1:2,"TOT"),alder = "all_no_total")
# metode 1 giver riskotid
N <- rename(N,R = INDHOLD)
# kategorisere i samme intervaller som data dpl
R <- intervAlder(N,breaks = c(0,1,seq(5,85,5),Inf),right = FALSE,by = "KØN",vars = "R",label_last = "85")
# beregn aldersfordeling af risikotid blandt alle dansker
V <- filter(R,KØN == "I alt") %>% mutate(V=R/sum(R)) %>% select(aldersinterval,V)
# join vægte med køn-specifik risikotid
dat <- filter(R,KØN != "I alt") %>% left_join(V,by = "aldersinterval")
# 
dat <- left_join(dpl,dat,by = c("aldersinterval","KØN"))
# 
# Direkte standardisering
#
# 1. beregn aldersspecifikke rater
dat <- mutate(dat,rate_dod_psyk =  1000*antal_dod_psyk/R)
# 2. beregn alderstandardiserede rater
dat %>% group_by(KØN) %>% summarise(sum(rate_dod_psyk*V))
#+END_SRC

#+RESULTS[(2024-03-21 17:38:45) e11f53489c4f440c34364f7a826b807bd1dca240]:
:results:
# A tibble: 2 × 2
  KØN     `sum(rate_dod_psyk * V)`
  <chr>                      <dbl>
1 Kvinder                    0.651
2 Mænd                       0.659
:end:

* Opgave 2

** rdm version uden figur/tabel :ignore:rmd:

1. Hvordan giver følgende udsagn mening?
 
 /Tabelbefolkningen bliver født og lever hele deres liv i et år/. 

2. [@2] I figuren nedenfor, er antal personer som dør af kræft højere
   i aldersintervallet 5-9 end i aldersintervallet 45-49?

3. [@3] Fortolk alle tal i rækken for aldersintervallet 70-74 år i den
   årsagsspecifikke dødelighedstavle, hvor mænd i Danmark i 2018 nedenfor
   (dødsårsagen er kræft, se forelæsningsnoterne).

** Instruks :ignore:opgave:

1. Hvordan giver følgende udsagn mening?
 
 /Tabelbefolkningen bliver født og liver helt deres liv i et år/. 

2. [@2] I figuren nedenfor, er antal personer som dør af kræft højere
   i aldersintervallet 5-9 end i aldersintervallet 45-49?

[[file:./kraeftdoedshyppighed.pdf]]

3. [@3] Fortolk alle tal i rækken for aldersintervallet 70-74 år i en
   årsagsspecifikke dødelighedstavle med årsag død på grund af kræft
   for mænd i Danmark i 2018.

** Instruks :ignore:rmd:   
#+BEGIN_SRC R  :results output drawer :exports both :session *R* :cache yes :eval (never-plain-export)
x <- hent_dodsaarsag_data(tid = 2018, årsag =c("A02"), køn = "Mænd")
# mortalitetsrater
x <- mutate(x,M = Dod/R)
# andel kræftdødsfald
x <- mutate(x,hQ = QDod/Dod)
# Chiang's \(a\) 
x <- mutate(x,a = c(0.1,2,rep(2.5,17)),k = c(1,4,rep(5,17)))
kraeftdodtavle_maend <- dodsaarsagtavle(data = x,
                                        mortalitet = "M",
                                        hQ = "hQ",
                                        alder = "aldersinterval",
                                        radix = 100000)
select(kraeftdodtavle_maend,-c(L,T,e))
#+END_SRC

#+RESULTS[(2025-04-01 11:01:17) 8a64cb708f219757dbd8ee08b2b8b0c54e939134]:
:results:
# A tibble: 19 × 11
   Alder      l     d    dQ     hQ     p        q        qQ     o LTR_Q risiko_Q
   <fct>  <dbl> <dbl> <dbl>  <dbl> <dbl>    <dbl>     <dbl> <dbl> <dbl>    <dbl>
 1 0     100000   406     0 0      0.996 0.00406  0         1     0.274 0       
 2 1-4    99594    55     0 0      0.999 0.000551 0         0.996 0.275 0       
 3 5-9    99539    37    12 0.333  1.00  0.000367 0.000122  0.995 0.275 0.000122
 4 10-14  99503    37     9 0.231  1.00  0.000375 0.0000866 0.995 0.275 0.000208
 5 15-19  99465   161    11 0.0702 0.998 0.00162  0.000113  0.995 0.275 0.000321
 6 20-24  99304   150    18 0.117  0.998 0.00151  0.000177  0.993 0.276 0.000496
 7 25-29  99154   238    17 0.0729 0.998 0.00240  0.000175  0.992 0.276 0.000670
 8 30-34  98916   321    45 0.140  0.997 0.00325  0.000456  0.989 0.276 0.00112 
 9 35-39  98594   396    55 0.140  0.996 0.00401  0.000561  0.986 0.277 0.00167 
10 40-44  98199   630   120 0.190  0.994 0.00641  0.00122   0.982 0.277 0.00287 
11 45-49  97569  1001   205 0.205  0.990 0.0103   0.00210   0.976 0.278 0.00492 
12 50-54  96568  1766   548 0.310  0.982 0.0183   0.00567   0.966 0.279 0.0104  
13 55-59  94802  3059   956 0.313  0.968 0.0323   0.0101    0.948 0.278 0.0200  
14 60-64  91743  4738  1797 0.379  0.948 0.0516   0.0196    0.917 0.277 0.0379  
15 65-69  87005  6933  2846 0.411  0.920 0.0797   0.0327    0.870 0.271 0.0664  
16 70-74  80072  9391  3817 0.406  0.883 0.117    0.0477    0.801 0.259 0.105   
17 75-79  70681 13345  4610 0.345  0.811 0.189    0.0652    0.707 0.240 0.151   
18 80-84  57336 18271  5404 0.296  0.681 0.319    0.0943    0.573 0.215 0.205   
19 85     39065 39065  6939 0.178  0     1        0.178     0.391 0.178 0.274
:end:


** Løsning                                                  :solution:ignore:
*** Besvarelse

1. [@1] Det giver mening, hvis man har beregnet dødelighedstavlen
   baseret på aldersspecifikke mortalitetsrater som gælder i dag.  En
   'person' fra tabelbefolkningen bliver 'udsat' for alle
   dødshyppigheder på tværs af alle aldersintervaller.
2. [@2] Det kan man ikke se i figuren, da figuren kun viser det relative antal kræftdødsfald blandt dem som døde. 
   Statistikbanken DODA1 viser at der er flere i aldersintervallet 45-49 som døde af kræft i 2008 end i aldersintervallet 5-9.
3. [@3] Fortolkning af hele tabellen er for en tabelbefolkning som
   bliver født i 2018 og lever helt deres liv i 2018.  I starten af
   aldersintervallet 70-74, er 80072 'personer' fra
   tabelbefolkningen i live. I intervallet dør 9391, hvoraf 3817 (40,6%) dør
   af kræft. For at en 'tabelperson' som er blevet 70 år, er sandsynligheden for at overleve inden alder 74 88,3% og dermed sandsynligheden for at dø inden alder 74 11,7%.
   For at en 'tabelperson' som er blevet 70 år, er sandsynligheden for at dø af kræft inden alder 74 4,8%. Sandsynligheden for at en
   tabelperson overlever indtil alder 70 år er 80,1%.
   For at en 'tabelperson' som er blevet 70 år, er risikoen
   for at dø af kræft i resten af livet 25.9% (livstidsrisiko for en
   70 årige tabelperson). Risiko for kræftdød inden 70-års alderen er 10,5%.

* Opgave 3

1. [@1] Beregn aldersspecifikke mortalitetsrater på grund af kræft i
   2010 og 2020 baseret på data fra statistikbanken for mænd og plot resultatet.
2. [@2] Beregn andel kræftdødsfald blandt døde og bagefter årsagsspecifikke dødelighedstavler for mænd 
   i 2010 og 2020 i Danmark.
3. [@3] Rapporter livstidsrisiko for dødsfald med kræft som dødsårsag i 2010 og i 2020 (danske mænd).
4. [@4] Sammenlign 2010 og 2020 med hensyn til de aldersspecifikke rater af kræftdødsfald og risiko for at dø af kræft (danske mænd). 
   
** Instruks :ignore:rmd:

1. [@1]
#+BEGIN_SRC R  :results output raw drawer :exports both :session *R* :cache yes :eval (never-plain-export)
x <- hent_dodsaarsag_data(tid = c(2010,2020), årsag =c("A02"), køn = "Mænd")
# mortalitetsrater
x <- mutate(x,M = Dod/R)
# kræftdødsrate
x <- mutate(x,Q_rate = 1000*QDod/R)
# andel kræftdødsfald
x <- mutate(x,hQ = QDod/Dod)
# TID skal væer factor
x <- mutate(x,TID = factor(TID))
# plot 
g = ggplot(x,aes(x = aldersinterval,y = Q_rate,group = TID,color = TID))+geom_line(linewidth = 1.3)
g <- g + theme_gray()+scale_colour_wsj("colors6")
g <- g+theme(axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)))
g <- g+theme(axis.title.x = element_text(margin = margin(t = 20, r = 0, b = 0, l = 0)))
g <- g+theme(text = element_text(size=15))
g+ylab("Kræftdødsfaldsrate per 1000 personår")+xlab("Alder")
#+END_SRC


2. [@2]

#+BEGIN_SRC R  :results output raw drawer :exports both :session *R* :cache yes :eval (never-plain-export)
# Chiang's a 
x <- x %>% group_by(TID) %>% mutate(a = c(0.1,2,rep(2.5,17)),k = c(1,4,rep(5,17)))
# andel kræftdødsfald
x <- mutate(x,hQ = QDod/Dod)
#+END_SRC

#+BEGIN_SRC R  :results output raw drawer :exports both :session *R* :cache yes :eval (never-plain-export)
tavle_2010 = filter(x,TID == 2010) %>% dodsaarsagtavle(mortalitet = "M", hQ = "hQ", alder = "aldersinterval", radix = 100000)
tavle_2010
#+END_SRC


#+BEGIN_SRC R  :results output raw drawer :exports both :session *R* :cache yes :eval (never-plain-export)
tavle_2020 = filter(x,TID == 2020) %>% dodsaarsagtavle(mortalitet = "M", hQ = "hQ", alder = "aldersinterval", radix = 100000)
tavle_2020
#+END_SRC


** Løsning                                                  :solution:ignore:
*** Besvarelse

 
Livstidsrisiko for at dø af kræft er 28,0% baseret på de
årsagsspecifikke mortalitetsrater for mænd i Danmark fra 2010 og også
28,0% baseret på årsagsspecifikke mortalitetsrater for mænd i Danmark
fra 2020. Det er lidt interessant at risikoen ikke er højre i 2010
selv om næsten alle aldersspecifikke mortalitetsrater på grund af
kræft er højre i 2010. Det skyldes at mortalitetsraterne for at dø på
grund af andet end kræft også er mindre i 2020:

#+BEGIN_SRC R  :results output raw drawer :exports (exercise-with-solutions) :session *R* :cache yes :eval (never-plain-export)
x <- hent_dodsaarsag_data(tid = c(2010,2020), årsag =c("A02"), køn = "Mænd")
# mortalitetsrater
x <- mutate(x,M = Dod/R)
# dødsrate pga kræft og alt andet end kræft
x <- x%>%mutate(Q_rate = 1000*QDod/R,
                barQDod = Dod-QDod,
                barQ_rate = 1000*barQDod/R)
# TID skal væer factor
x <- mutate(x,TID = factor(TID))
# plot 
g = ggplot(x,aes(x = aldersinterval,y = barQ_rate,group = TID,color = TID))+geom_line(linewidth = 1.3)
g <- g + theme_gray()+scale_colour_wsj("colors6")
g <- g+theme(axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)))
g <- g+theme(axis.title.x = element_text(margin = margin(t = 20, r = 0, b = 0, l = 0)))
g <- g+theme(text = element_text(size=15))
g+ylab("Dødsfaldsrate pga andet end kræft per 1000 personår")+xlab("Alder")
#+END_SRC
