* 1 Migration

Migration er ligesom mortalitet og fertilitet et vigtigt tema for demografien. Ind- og udvandringer spiller nemlig en betydelig rolle for befolkningens størrelse og udvikling. Dertil kommer, at migration påvirker befolkningssammensætningen væsentligt ift. fordelingen af køn, alder og etnicitet. For demografiske undersøgelser er det altså vigtigt at beskrive de personer, der indvandrer til en befolkningen og hvem der udvandrer fra den. Det skyldes, at migranters karakteristika kan forklare ændringer i eksempelvis fertiliteten, arbejdsstyrkens størrelse og forsørgerbyrden. Desuden kan sygdomsmønstre være forskellige på tværs af etniciteter og, indvandres sygdomsmønstre kan derfor variere fra den øvrige befolkning. Det er således ikke uvæsentligt at undersøge migration, når man ønsker at forstå dynamikker i befolkningen. 

Migration kan beskrives som geografisk mobilitet. Det forudsætter, at en person eller familie/husstand skifter bopæl enten til et andet sted i landet eller til et andet land. Når en flytning sker på tværs af landegrænser, er der tale om ekstern migration. Men flytninger kan også ske over kortere afstande fx inden for en kommune, region eller land. Når en flytning sker inden for et defineret område, er der tale om intern migration. Begge former for migration er interessante i demografisk forstand. Indenlandske flytninger (intern migration) har betydning for befolkningssammensætningen i oprindelsesområdet samt tilflytterområdet. Det såkaldte udkantsdanmark er et eksempel på områder med få tilflyttere og mange fraflyttere. Det resulterer i en skæv befolkningssammensætning i forhold til resten af landet – for eksempel ift. køn, alder og uddannelsesniveau. International migration har mindre betydning for befolkningssammensætningen for mindre områder, men stor betydningen for landets befolkning. 


** 1.1 Beregninger ved ekstern migration
Sammenlignet med mortalitet og fertilitet er der markant færre mål for ind- og udvandringer. Det skyldes en række udfordringer i definitioner og datatilgængelighed, som vil blive berørt løbende i dette afsnit. Der er dog en række muligheder for at undersøge vandringer i demografiske analyser. Det inkluderer undersøgelser af bestanden indvandrede personer, som indebærer beskrivelser af indvandrerbefolkningens karakteristika, og undersøgelser af vandringer, hvilket kan belyse udviklingen i ind- og udvandringer over tid. 

Ved undersøgelser af ekstern migration er det væsentligt først at være bekendt med de data, som vi har til rådighed. For at undersøge ind- og udvandringer af Danmark bruges data fra Danmarks Statistik. I deres årlige opgørelser over vandringer indgår samtlige ind- og udvandringer. Dvs. både vandringer af længere og kortere varighed. Ophold af kortere varighed har ikke stor betydning for befolkningssammensætningen og dens udvikling på længere sigt, så derfor er vi oftest interesseret i varige vandringer. En /varig/ indvandring er defineret ved, at den indvandrede person ikke udvandrer igen inden for et år efter indvandringen. På samme vis, defineres en varig udvandring ved, at den udvandrede person ikke flytter tilbage til Danmark inden for et år. Denne definition kan variere fra land til land, og det er derfor vigtigt at have dette for øje, hvis man ønsker at sammenligne vandringer på tværs af lande. I Danmark har vi meget detaljeret data, da det indsamles løbende gennem administrative registre, mens for andre lande indsamles information med nogle års mellemrum gennem såkaldte census (folketællinger). Dette kan have betydning for, hvilken definition af varige vandringer, et land kan bruge. 

Vandringer kan ligesom fertilitet og mortalitet beskrives som summariske rater. Disse rater beregnes ofte for et år ad gangen og angives pr. 1,000 indbyggere i landet. Fortolkningen af /den summariske udvandringsrate/ er lige til. Her divideres antallet af udvandringer med middelfolketallet i befolkningen. Således afspejler raten, hvor stor en andel af befolkningen som udvandrer i det pågældende år. Formlen ser således ud. 

$Summarisk udvandringsrate =  U(t,t+1)/M$

/U/ er antal udvandringer i tidsintervallet t-(t+1) og /M/ er middelfolketallet i samme tidsinterval.

/Den summariske indvandringsrate/ beregnes på samme vis ved at dividere antallet af indvandrede personer med middelfolketallet i befolkningen. For denne rate er det vigtigt at pointere, at man for alle andre rater vil dividere antallet af indvandrede personer med middelfolketallet for den befolkningen, som er i risiko for at indvandre. Det er tilfældet for den summariske fertilitetsrate, hvor antallet af fødsler divideres med antallet af kvinder i den fertile alder. Ligesom det er tilfældet for den summariske mortalitetsrate, hvor antal dødsfald divideres med middelfolketallet i befolkningen, hvor alle er i risiko for at dø. Vi kender i imidlertid ikke middelfolketallet for hele den befolkning, der er i risiko for at indvandre til Danmark. Samtidig vil en sådan rate ikke nødvendigvis være interessant, når man ønsker at forstå indvandring til Danmark. Derfor er det normalt accepteret, at middelfolketallet varierer i definition for den summariske indvandringsrate. Antallet af indvandrede personer divideres således med middelfolketallet i modtagerlandet. Formlen ser således ud: 

$Summarisk indvandringsrate=  I(t,t+1)/M$

/I/ er antal indvandringer i tidsintervallet t-(t+1) og /M/ er middelfolketallet i samme tidsinterval. 

I Figur 1 vises udviklingen i de summariske indvandrings- og udvandringsrater for årene 1980-2022. Der ses en jævn stigning over alle årene med en summarisk indvandringsrate, der ligger højere end den summariske udvandringsrate fra 1983. Den stigende indvandring over årene skyldes forskellige strømninger. Først og fremmest er indvandringen drevet af arbejdsmuligheder i Danmark. Disse migranter omtales arbejdsmigranter. Over de seneste årtier er personer fra Holland eksempelvis flyttet til Danmark for at drive landbrug. Samtidig er indvandring også drevet af forholdene i udlandet. Eksempelvis ses et peak i den summariske indvandringsrate i 2015, hvilket er det år, hvorfra mange måske husker billeder af det store antal flygtninge, der gik på motorvejene. Der var tale om en stor flygtningestrøm fra krigsramte Syrien. Der ses ligeledes en stor stigning i 2022, hvilket blandt andet skyldes krigen i Ukraine. Ligeledes ses et falde både i indvandring og udvandring i de år, hvor COVID-19 begrænsede mulighederne for at rejse (2020-2021). 

./kapitel5/Figur1.pdf

I den demografiske ligevægtsligning, som blev beskrevet i Kapitel 1, informerer differencen mellem mortalitet og fertilitet om den naturlige vækst af befolkningen, mens differencen mellem indvandring (immigration) og udvandring (emigration) informere om /nettoindvandring/. Helt konkret beregnes denne ved at trække antallet af udvandringer fra antallet af indvandringer. Nettoindvandringen kan være positiv og dermed afspejle befolkningstilvækst eller omvendt. Formlen beskrives således:

$Nettoindvandring = I(t,t+1)-U(t,t+1)$

/I/ er antal indvandringer, /t/ er tidsintervallets start og /U/ er antal udvandringer.


** 1.2 Beregninger ved intern migration
Intern migration henviser som nævnt til flytninger, der sker inden for et lands grænser – eller inden for et andet specificeret område som eksempelvis kommuner eller regioner. 

Ved interne flytninger i Danmark anvender vi igen data fra Danmark Statistik til at undersøge intern migration. Helt specifikt anvendes flytteanmeldelser til de kommunale folkeregistre (CPR-registret), som er lovpligtige i forbindelse med en flytning. Flytninger monitoreres altså ud fra konkrete bopælsskift, som er anmeldt af borgerne selv. Flytninger kan desuden opgøres for enkeltpersoner eller for familier/husstande. 

Beregningsmuligheder ifm. Intern migration er de samme som ved ekstern migration. Vi kan således beregne /nettotilflytning/ og /summariske til- og fraflytningsrater/ ud fra samme formler, som blev angivet tidligere i kapitlet. For intern migration er det desuden også muligt at udregne tilflytning til et område fra et bestemt område, da vi kender befolkningerne – og således også middelfolketallet – for begge områder. Vi kan eksempelvis udregne raten for tilflytninger til Region Sjælland fra Region Hovedstaden. I dette tilfælde vil vi bruge formlen for den summariske indvandringsrate, hvor tælleren vil være antallet af tilflytninger til Region Sjælland i den givne periode og nævneren vil være middelfolketallet i Region Hovedstaden i den givne periode. 

Flytninger opgøres ofte også ved hjælp af /aldersspecifikke flytterater/. Disse kan også udregnes for ekstern migration, men anvendes oftest ifm. Intern migration, hvorfor vi gennemgår beregningerne her. De aldersspecifikke flytterater udregnes per aldersgruppe i en given periode fx. for et enkelt kalenderår. 

$flytning_{x,x+n}=  FLYTNING_{x,x+n}/M_{x,x+n} $

/flytning/ angiver flytteraten, /x/ er aldersintervallets startalder (fx 30 år), /n/ er intervallets længde (fx 5 år), /FLYTNING/ er antal flytninger, og /M/ er middelfolketallet for den pågældende aldersgruppe. 

Vi kan også vælge at udregne rater specifik for køn eller for fødselskohorter. Fremgangsmåden er den samme som for de aldersspecifikke rater. I Figur 2 ses en beregning af alders- og kønsspecifikke flytterater i 2022 i Danmark. Det er således en opgørelse over interne flytninger uanset til- og fraflytningsområde. Her fremgår det, at langt de fleste flytninger for både mænd og kvinder sker omkring 20-årsalderen. Det er meget normalt at flytte hjemmefra i årene efter endt gymnasium og i forbindelse med opstart af studie. Ligesom at nogle flytter fra deres hjemby til et område med flere uddannelsesmuligheder. Det fremgår også, at en del små børn flytter. Det skyldes ofte, at familier flytter ud af byerne og til større boliger ifm. Familieforøgelse. Og endeligt ses en stigning i antal flytninger pr. 1000 indbyggere blandt de 75+ årige. Det afspejler eksempelvis flytninger til beskyttede boliger og plejehjem. 

./kapitel5/Figur2.pdf



