* Mortalitet

Mortalitet er et synonym til dødelighed og refererer til hændelsen død.
I demografi betragtes dødsfald som en måde, hvorpå personer kan
forlade en befolkning og mortalitet beskriver således en vigtig del af
en befolknings dynamik og udvikling.  I forrige kapitel blev I
præsenteret for den demografiske ligevægtsligning, som beskriver
befolkningstilvæksten ud fra fire demografiske komponenter: fødsler,
dødsfald, indvandringer og udvandringer. Mortalitet er altså en
af de grundlæggende emner inden for demografi.

Fra et samfundsperspektiv spiller demografiske undersøgelser af
befolkningens mortalitet en vigtig rolle i at forstå forandringer i
befolkningssammensætningen og befolkningens sundhedstilstand. Et
eksempel er den faldende dødelighed på tværs af alle aldersgrupper,
som har resulteret i, at vi lever længere. Dette medfører en stigende
andel af ældre i befolkningen. Desuden giver analyser af mortalitet
indblik i befolkningens generelle sundhedstilstand, og de kan
informere om ulighed i sundhed/dødelighed på tværs af
befolkningsgrupper. Disse informationer er væsentlige for det
politiske arbejde, som former sundhedspolitikker og påvirker
ressourceallokering i sundhedsvæsenet.


** Den demografiske transition

Den demografiske transition beskriver et historisk skift i
befolkningsmønstre fra et traditionelt samfund med høj fertilitet og
høj dødelighed til et samfund præget af lav fertilitet og lav
dødelighed. Den faldende tendens i dødelighed er det element af transitionen, der
kommer først, hvorefter et fald i fertiliteten følger. Dette skift er
ofte drevet af økonomisk vækst, forbedret sundhed og sociale
forandringer, som påvirker beslutninger om familiedannelse.  Som
konsekvens af den demografiske transition ændres
befolkningssammensætningen.


** Mål for mortalitet

Feltet demografi anvender forskellige mål til at kvantificere og opgøre
mortalitet.  En summarisk mortalitetsrate angiver antallet af dødsfald
per personår i en given periode. Beregningen af summariske
mortalitetsrater bliver forklaret i Kapitel 1. Den summariske
mortalitetsrate er for eksempel nyttig, når formålet er at beskrive
dødeligheden i en befolkning i en given periode.  Summariske
mortalitetsrater kan udregnes per år i en given periode og således
informere om ændringer i dødeligheden over tid. Et eksempel på dette
kan ses i Figur ref:fig:k2-sum-mort.

#+ATTR_LATEX: :options otherkeywords={ggplot,hent_data}, deletekeywords={list,dt,data,scale,D,R}
#+BEGIN_SRC R :results file graphics :file ./kapitel2/k2-summa-mortalitetsrater.pdf :exports none :session *R* :cache yes
# R-koder der producerer figur 1
dod=hent_data(register = "dod",køn = c("M","K"),tid = "all") %>% rename(D = "INDHOLD")
N=hent_data(register = "befolk2",køn = c("1","2"),tid = 1974:2022) %>% rename(R = "INDHOLD")
dat <- left_join(dod,N,by = c("KØN","TID"))
dat <- mutate(dat,M = 1000*D/R)
ggplot(dat,aes(TID,M,color = KØN))+geom_line()+geom_point()+
  theme_economist()+ scale_colour_wsj("colors6")+ylim(c(5,15))+
  xlab("")+ylab("Dødsfald per 1000 personår")
#+END_SRC

#+RESULTS[(2024-02-10 15:47:11) 257224338dec5045ec53db8a0d931436fc8a760f]:
[[file:./kapitel2/k2-summa-mortalitetsrater.pdf]]

#+name: fig:k2-sum-mort
#+ATTR_LATEX: :width 1.0\textwidth
#+CAPTION: Udvikling i den summariske mortalitetsrate i perioden 1974-2022. Kilde: statistikbankens register DOD, BEFOLK2
[[file:./k2-summa-mortalitetsrater.pdf]]

# R-koder som producerer Figur ref:fig:k2-sum-mort findes her:
Mortalitet kan også beskrives ud fra /aldersspecifikke
mortalitetsrater/. Disse beregnes på samme vis som den summariske
mortalitetsrate, men separat for hver aldersgruppe. Det bliver således
muligt at undersøge forskelle i dødeligheden på tværs af
aldersgrupper. Ligeledes kan alderspecifikke mortalitetsrater
udregnes per år over en given periode og derved give information om
ændringer i aldersspecifik dødelighed over tid. Altså oplever nogle
aldersgrupper et fald i mortaliteten, hvor andre oplever en stigning?
Det kan vi se i nedenstående Figur 2, som viser køns- og
aldersspecifikke mortalitetsrater. Her ser vi, at dødeligheden er
faldet i samtlige aldersgrupper og for begge køn i løbet af årene
1974--2022.

#+ATTR_LATEX: :options otherkeywords={ggplot,hent_data}, deletekeywords={list,dt,data,scale,D,R}
#+BEGIN_SRC R :results file graphics :file ./kapitel2/k2-aldersspecifik-mortalitet.pdf :exports none :session *R* :cache yes
# R-koder der producerer figur 1
dod <- hent_data(register = "dod",language = "da",køn = c("M","K"),tid = "all",alder = "all_no_total") %>% rename(D = "INDHOLD")
dod <- intervAlder(dod,breaks=c(-Inf,seq(5,85,5),Inf),right=FALSE,var="D",alder="ALDER",by=c("KØN","TID"),label_one = "0-4",label_last = "85")
N=hent_data(register = "befolk2",language = "da",køn = c("1","2"),tid = 1974:2022,alder = "all_no_total") %>% rename(R = "INDHOLD")
N <- rename(N,aldersinterval = alder)
N$ALDER <- NULL
dat <- left_join(N,dod,by = c("KØN","TID","aldersinterval"))
dat <- mutate(dat,M = 1000*D/R)
dat <- mutate(dat,KØN = factor(KØN))
dat <- rename(dat, Alder = aldersinterval)
g <- ggplot(dat,aes(TID,M,color = Alder))+geom_line()+
  theme_economist()+ 
  xlab("")+ylab("Dødsfald per 1000 personår")+facet_grid(~KØN)+xlab("Kalendertid")
g <- g + theme(axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)))
g <- g + theme(axis.title.x = element_text(margin = margin(t = 20, r = 0, b = 0, l = 0)))
g = g+theme(legend.position="bottom") 
g
#+END_SRC

#+RESULTS[(2024-02-13 15:59:52) 21edeb10f6d92a8166a7d194ef8c23c6e6e5252c]:
[[file:./kapitel2/k2-aldersspecifik-mortalitet.pdf]]

#+name: fig:k2-sum-mort
#+ATTR_LATEX: :width 1.0\textwidth
#+CAPTION: Udvikling i den summariske mortalitetsrate i perioden 1974-2022. Kilde: statistikbankens register DOD, BEFOLK2.
[[file:./k2-aldersspecifik-mortalitet.pdf]]


Aldersspecifikke mortalitetsrater kan også angives for et enkelt år,
hvilket giver et indtryk af forskelle i dødeligheden over
livsforløbet. Køns- og aldersspecifikke mortalitetsrater for 2022 kan
ses i Figur ref:fig:k2-ammk-2022. Her ser vi, at mortaliteten er lav og
forbliver sådan frem til efter 60-årsalderen, hvorefter mortaliteten
stiger - først en lille stigning og senere en mere markant
stigning. Det er også tydeligt, at mortaliteten stiger hurtigere for
mænd end for kvinder. Endeligt beregner man ofte middellevetid inden
for demografi. Dette er et mål for, hvor længe en nyfødt kan forvente
at leve givet de aldersspecifikke mortalitetsrater, der er gældende
det år, barnet er født i. Middellevetid er et komplekst mål, og dets
udregning bygger på konstruktionen af livstabeller/life tables. Denne
udregning kræver en detaljeret beskrivelse, og vi har derfor dedikeret
Kapitel 3 til netop dette. I dette kapitel vil vi fokusere på, hvordan
summariske og aldersspecifikke rater kan standardiseres for at gøre
det muligt at sammenligne rater - herunder mortalitetsrater - på tværs
af befolkninger.

#+ATTR_LATEX: :options otherkeywords={hent_data,mutate,summarise,pull,ggplot}, deletekeywords={c,&,title,legend,de,scale,by}
#+BEGIN_SRC R :results file graphics :file ./kapitel2/k2-aldersspecifikke-mortalitet-maend-kvinder-2022.pdf :exports none :session *R* :cache yes :width 8 :height 5
# hent folketal fra 2011
folk <- hent_data("FOLK1a",alder=0:125,køn=c(2,1),tid="2022K3")
# ændre variable navn
folk <- folk %>% rename("risikotid"="INDHOLD")
# samle antal personer over 99 (fordi register DOD gør det samme)
folk <- samle_alder(folk,variable = "risikotid",value = "99plus",by = "køn")
# hent dødstal fra 2011
dd <- hent_data(register="dod",alder=0:99,køn=c("K","M"),tid="2022")
# ændre variable navn
dd <- dd %>% rename("antal_døde"="INDHOLD")
# join folketal og antal dødsfald
x <- left_join(folk,dd,by=c("alder","KØN"))
# aldersspecifikke mortalitetsrater
x <- x %>% group_by(KØN) %>% mutate(mrate=1000*antal_døde/risikotid) 
# grafik
g <- ggplot(x,aes(x=alder,y=mrate,color= KØN))+geom_line()+geom_point()
g <- g+theme_economist()+scale_colour_wsj("colors6") +theme(legend.title=element_blank())
g <- g+ylab("Mortalitetsrate per 1000 personår")+xlab("Alder (år)")+ggtitle("Danmark 2022")
g <- g + theme(axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)))
g = g + theme(axis.title.x = element_text(margin = margin(t = 20, r = 0, b = 0, l = 0)))
g = g + theme(plot.background = element_rect(fill = "gray88", colour = NA))
g = g+theme(legend.title=element_blank())+theme(legend.position="bottom")
g
#+END_SRC

#+RESULTS[(2024-02-16 14:11:52) a9a1e047b2659d06d3a2d85dec221df5dc81b89d]:
[[file:./kapitel2/k2-aldersspecifikke-mortalitet-maend-kvinder-2022.pdf]]

#+name: fig:k2-ammk-2022
#+ATTR_LATEX: :width 1.0\textwidth
#+CAPTION: Aldersspecifikke mortalitetsrater fra hele den danske befolkning i 2022. Vi ser at
#+CAPTION: dødeligheden var højre for mænd for alle aldre.
[[file:./k2-aldersspecifikke-mortalitet-maend-kvinder-2022.pdf]]

* Standardiserede rater

Vi vil nu gå i dybden med begreberne /aldersspecifikke rater/ og
/standardiserede rater/. Disse skal ikke forveksles med de summariske
rater som Kapitel 1 har indført. I det følgende betegner vi derfor
alle rater som Kapitel 1 har indført som /summariske
rater/. /Summarisk/ betyder at raterne tæller hændelser og risikotid i
hele befolkningen, altså uanset alder og uden standardisering. For at
motivere standardiserede rater starter vi med at forklare
begrænsningerne med de summariske rater når det kommer til
sammenligning af forskelige befolkninger.

** Sammenligning af summariske rater
:PROPERTIES:
:CUSTOM_ID: samesumma
:END:

Som udgangspunkt har det begrænset interesse at sammenligne forskelige
befolkningers summariske rater. Det er især problematisk når
befolkningerne, som man ønsker at sammenligne, har forskelige
aldersfordelinger. Afhængig af formålet med undersøgelsen kan det
alligevel godt være, at man vil sammenligne summariske rater, men det
er vigtigt, at man er klar over at de afhænger af
aldersfordelingen. Problemet som opstår ved sammenligning af
summariske rater er ret nemt at indse ved følgende eksempel. En
matematisk forklaring (Kitagawas dekomposition) følger i afsnit
ref:k2-kitagawa.

*** Eksempel
:PROPERTIES:
:CUSTOM_ID: k2-summariske-rater-2011
:END:
Vi beregner de summariske mortalitetsrater for året 2011 i den
kvindelige danske befolkning og også i den mandlige danske befolkning.

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={library,list}
#+BEGIN_SRC R  :results output example :exports both  :session *R* :cache yes  
library(danstat)
library(tidyverse)
# Risikotid i 2011 baseret på middelfolketal metode 1
# ganget med 1 år 
x <- hent_data("FOLK1a",tid = "2011K3",køn = c(2,1))
# fjern TID fordi den er konstant
x$TID <- NULL
# ændre variable navn
x <- rename(x,"risiko_tid"="INDHOLD")
# number of doedsfald i 2011
d <- hent_data("DOD",tid="2011","køn" = c("K","M"))
# fjern TID fordi den er konstant
d$TID <- NULL
# ændre variable navn
d <- rename(d,"antal_dod"="INDHOLD")
# join
dat <- left_join(x,d,by="KØN")
# summariske mortalitetsrater per 1000 personaar
dat <- mutate(dat,"Summariske mortalitetsrate"=1000*antal_dod/risiko_tid)
dat
#+END_SRC

#+RESULTS[(2024-01-27 08:11:12) 4ab3593bba3bd26b0d15dbe4ba9bdfd3d432957e]:
: # A tibble: 2 × 4
:   KØN   risiko_tid antal_dod `Summariske mortalitetsrate`
:   <chr>      <dbl>     <dbl>                        <dbl>
: 1 Women    2806716     26577                         9.47
: 2 Men      2760140     25939                         9.40


Vi ser at den summariske mortalitetsrate i året 2011 var 9,47 døde per
1000 personår for danske kvinder og 9,40 døde per 1000 personår for
danske mænd. Ved første øjekast strider dette resultat imod den gængse
viden, at danske kvinder lever længere end danske mænd.
Fordi dødeligheden stiger med
alderen og fordi der er flere kvinder med en høj alder end mænd med en høj
alder, er den summariske mortalitetsrate højere for kvinder
end for mænd. Den summariske mortalitetsrate afspejler nemlig ikke kun
dødeligheden men også aldersfordelingen i befolkningen. Da kvinder
lever længere end mænd, er der flere ældre kvinder end ældre mænd, og
det forøger kvindernes summariske mortalitetsrate. Resultatet er dog
helt korrekt; kvinderne havde en højere summarisk mortalitetsrate end
mænd i 2011. Den skyldes ikke deres køn men deres alder.

Hvordan skal disse rater fortolkes? En rate er jo ikke en
sandsynlighed, og det ville ikke være helt korrekt at konkludere, at der
døde 9,47 kvinder blandt 1000 kvinder, som man følger igennem 2011,
fordi de kvinder, som dør midt i eller i starten af 2011, jo ikke
bidrager med et helt personår til risikotiden. En bedre fortolkning
opstår, når man sammenligner mortalitetsraten med hastigheden af en
cykel. Hastigheden er raten cyklen bevæger sig med og kan for
eksempel være 20 kilometer per time. Mortalitetsraten betegner hastigheden
hvormed befolkningen dør; den kan for eksempel være 9,40 døde per 1000
personår. Denne hastighed, altså mortalitetsraten, betegner vi også
med /dødelighed/. Det vil sige, at resultatet kan fortolkes på følgende
måde: Danske kvinder har haft en lidt højere dødelighed i 2011 end
danske mænd (fordi de var ældre).

* Aldersfordeling

** Alderspyramide

For at sammenligne aldersfordelinger af kvinder og mænd, kan man tegne
en alderspyramide. Figur ref:fig:alderspyramide viser alderspyramiden
for den danske befolkning baseret på data fra 1. juli 2023. I toppen
af pyramiden, kan man tydeligt se forskellen mellem mænd og kvinder:
Der er flere ældre kvinder end ældre mænd. Pyramiden afspejler også
historiske begivenheder som anden verdenskrig og den faldende tendens
i dødeligheden og fertiliteten som følge af den demografiske
transition. En mere sofistikeret og dynamisk version af den danske
alderspyramide findes her
https://extranet.dst.dk/pyramide/pyramide.htm.

#+ATTR_LATEX: :options otherkeywords={group,mutate,ggplot,hent_data}, deletekeywords={list,dt,stat,library,data,legend,title,as.numeric,c}
#+BEGIN_SRC R :results file graphics :file ./kapitel2/k2-alderspyramide.pdf :exports code :session *R* :cache yes
## begge køn
folk <- hent_data("FOLK1a","alder"=0:125,"køn"=1:2,tid="2023K3")
# fjern tomme aldre
folk <- subset(folk,alder<106)
# mænd skal vises på venstre siden, derfor bliver INDHOLD negativt 
folk_m <- subset(folk,KØN=="Men") %>% mutate(INDHOLD=-INDHOLD)
# for kvinder på højre siden er INDHOLD  positivt
folk_k <- subset(folk,KØN=="Women")
# plot
g <- ggplot(folk, aes(x = alder, y = INDHOLD, fill = KØN)) +
  geom_bar(data=folk_m, stat = "identity") +
  geom_bar(data=folk_k, stat = "identity") +
  coord_flip() + theme_economist() +
  ylab("Folketal N(t)")+xlab("Alder (år)") +
  theme(legend.title=element_blank())
g <- g+ggtitle("Alderspyramide Danmark 1 juli 2023")
g
#+END_SRC

#+RESULTS[(2024-02-10 15:30:35) fac98c2a078d12736394a306ca3488761f982a85]:
[[file:./kapitel2/k2-alderspyramide.pdf]]

#+name: fig:alderspyramide
#+ATTR_LATEX: :width 1.0\textwidth
#+CAPTION: Data fra statistikbankens FOLK1a
[[file:./k2-alderspyramide.pdf]]

** Folketal i aldersgrupper

Aldersfordelingen i folketallet angiver hvor mange personer i en
befolkning har en bestemt alder for alle aldre. Det kan den enten gøre
i det absolutte antal eller som procent i forhold til antal personer i
hele befolkningen. For at beskrive aldersfordelinger, vil man typisk
vælge et passende antal aldersintervaller (passende til opgaven man
sidder med) og fordele befolkningen på intervallerne. Intervallerne
behøver ikke at være lige store. Da alle personers aldre ændrer sig hele
tiden, skal man angive den dato, som aldersfordelingen refererer
til. For eksempel kan vi tale om aldersfordelingen af kvinder i Danmark
den 8. marts 1910 og om aldersfordelingen af Fyns befolkning den 1.
juli 1989.

*** Eksempel
:PROPERTIES:
:CUSTOM_ID: eksempel_aldersgrupper
:END:

Vi finder aldersfordelingen af folketallet for hele den danske befolkning 1. januar 2023
og inddeler den i 4 intervaller: \([0,25], (25,50],(50,75], (75,125]\). 
Bemærk at vores notation for intervaller betyder,
at intervalgrænsen er ekskluderet hvis parentesen er rund og
inkluderet hvis parentesen er firkantet. Det vil sige at personer, som
er præcis 25 år gamle falder i intervallet \([0,25]\) og personer som
er 50 falder ikke i intervallet \((50,75]\) men i intervallet
\((25,50]\). Vi beregner nu andelen, som de enkelte aldersgrupper
udgør og angiver den i procent (per hundrede). De fire procenttal er
netop aldersfordelingen med hensyn til de fire intervaller.

#+ATTR_LATEX: :options otherkeywords={group,mutate,hent_data}, deletekeywords={dt,list,c}
#+BEGIN_SRC R  :results output :exports both  :session *R* :cache yes  
folk <- hent_data("FOLK1a","alder"=0:125,tid="2023K3")
# Aldersintervaller
folk <- mutate(folk,Aldersinterval=cut(alder,
                                   breaks=c(0,25,50,75,125),
                                   include.lowest = TRUE))
# antal person i de 4 aldersintervaller
af <- folk %>% group_by(Aldersinterval) %>%
      summarise(Antal=sum(INDHOLD))
# beregne procenter 
af <- af %>% mutate(Procent=100*Antal/sum(Antal))
af
#+END_SRC

#+RESULTS[(2023-12-27 12:58:11) f2b5e614ae8b58ae251e099c1093bc3de19f8c2b]:
: # A tibble: 4 × 3
:   Aldersinterval   Antal Procent
:   <fct>            <dbl>   <dbl>
: 1 [0,25]         1742979   29.3 
: 2 (25,50]        1882860   31.7 
: 3 (50,75]        1778084   29.9 
: 4 (75,125]        540222    9.09

*** Aldersfordeling i formler

Enhver definition af aldersintervaller opdeler en befolkning i
aldersgrupper. For \(x=1,\dots,m\) aldersgrupper betegner vi med
\(N_x(t)\) folketal i aldersgruppen \(x\) til kalendertid \(t\). Vi
betegner fortsat med \(N(t)\) folketal i hele befolkningen til
kalendertid \(t\) og udtrykker det som summen af folketal i
aldersgrupperne:
#+begin_export latex
\begin{equation*}
N(t)=N_1(t)+\dots+N_m(t)=\sum_{x=1}^m N_x(t).
\end{equation*}
#+end_export

I eksemplet fra afsnit ref:eksempel_aldersgrupper er der \(m=4\)
aldersgrupper og når vi indsætter tal i formlen finder vi folketal som
sum af de aldersspecifikke folketal:
#+begin_export latex
\begin{equation*}
N(\texttt{1 jan 2023})= 1742979 + 1882860 + 1778084 + 540222 = 5944145.
\end{equation*}
#+end_export

Vi beregner andelen af befolkningen i aldersgruppe \(x\) ved at
dividere folketal i aldersgruppen med folketal i hele befolkningen til
tid \(t\):

#+begin_export latex
\begin{equation*}
 \frac{N_x(t)}{N(t)}=\{\text{Andel af befolkningen i aldersgruppe }x \text{ til tid } t\}.
\end{equation*}
#+end_export

Aldersfordelingen er lig med de aldersspecifikke andele af folketal,
altså for en given opdeling i aldersintervaller givet ved vektoren:

#+begin_export latex
\begin{equation}\label{eq:aldersfordeling}
\text{Aldersfordeling}=\left(\frac{N_1(t)}{N(t)},\dots, \frac{N_m(t)}{N(t)}\right).
\end{equation}
#+end_export

I eksemplet fra afsnit ref:eksempel_aldersgrupper har vi allerede
beregnet aldersfordeling den 1. januar 2023 og angivet den som
procent.

*** Sammenligning af aldersfordelinger

Vi sammenligner aldersfordelingen i hovedstadsområdet med
aldersfordelingen i landdistrikter i Danmark i 2023.  For at gøre det
enkelt bruger vi inddelingen af befolkningen i de 4 aldersgrupper fra
afsnit ref:eksempel_aldersgrupper. Vi henter folketalsdata fra
statistikbankens register BY2, hvor man kan angive bystørrelse.

#+ATTR_LATEX: :options otherkeywords={group,hent_data,mutate,summarise}, deletekeywords={list,c}
#+BEGIN_SRC R  :results output verbatim :exports both  :cache yes
## meta <- get_table_metadata("BY2")
b2 <- hent_data(register = "BY2",alder=0:125,
                BYST=c("HOVEDS","LAND"),tid="2023")
# aldersintervaller
b2 <- mutate(b2,Aldersinterval=cut(alder,
                                   breaks=c(0,25,50,75,125),
                                   include.lowest = TRUE))
# antal person i de 4 aldersintervaller
af <- b2 %>% group_by(BYST,Aldersinterval) %>%
                                summarise(Antal=sum(INDHOLD))
# procent 
af <- af %>% mutate(Procent=100*Antal/sum(Antal))
af
#+END_SRC

#+RESULTS[(2023-12-29 10:19:54) 287c609a03f2509a3b60ba667e40e511f073958c]:
#+begin_example
# A tibble: 8 x 4
# Groups:   BYST [2]
  BYST                      Aldersinterval  Antal Procent
  <chr>                     <fct>           <dbl>   <dbl>
1 Greater Copenhagen Region [0,25]         424524   31.1 
2 Greater Copenhagen Region (25,50]        520217   38.2 
3 Greater Copenhagen Region (50,75]        329994   24.2 
4 Greater Copenhagen Region (75,125]        88561    6.50
5 Rural areas               [0,25]         184556   26.8 
6 Rural areas               (25,50]        198151   28.8 
7 Rural areas               (50,75]        258161   37.5 
8 Rural areas               (75,125]        46720    6.79
#+end_example




En sammenligning af de to aldersfordelinger viser, at andelen af
mennesker, der er over 75 år gamle, er cirka det samme, men at andelen
af mennesker under 50 år er højest i hovedstadsområdet og andelen af
mennesker mellem 50 og 75 år er højest i landdistrikterne.

** Risikotid i aldersgrupper
:PROPERTIES:
:CUSTOM_ID: risikotid_aldersgrupper
:END:

Med hensyn til mortalitetsrater har vi brug for aldersfordelingen af
risikotiden i en bestemt kalenderperiode. Vi betegner med
\(R_x[t_1,t_2]\) den samlede gennemlevede tid i perioden \([t_1,t_2]\)
af alle personer i aldersgruppe \(x\). Vi bemærker at en person, som
har levet i befolkningen i perioden \([t_1,t_2]\) kan bidrage med
risikotid til et eller flere aldersintervaller. Det sker for personer
som har fødselsdag mellem dato \(t_1\) og dato \(t_2\), da de den
dag skifter fra aldersgruppe \(x\) til aldersgruppe \(x+1\). Vi
betegner fortsæt med \(R[t_1,t_2]\) risikotiden for hele befolkningen
og kan nu udtrykke den som en sum af de aldersspecifikke risikotider:

#+begin_export latex
\begin{equation}\label{eq:sum_risikotid}
R[t_1,t_2]=R_1[t_1,t_2]+\dots+R_m[t_1,t_2]=\sum_{x=1}^m R_x[t_1,t_2].
\end{equation}
#+end_export

Vi beregner andelen af risikotid i aldersgruppe \(x\) ved at dividere
risikotiden i aldersgruppen med risikotiden i hele befolkningen i perioden
\([t_1,t_2]\) og betegner den med \(V_x\):

#+begin_export latex
\begin{equation*}
V_x[t_1,t_2]= \frac{R_x[t_1,t_2]}{R[t_1,t_2]}=\{\text{Andel af risikotid i aldersgruppe }x \text{ i perioden } [t_1,t_2]\}.
\end{equation*}
#+end_export

Risikotid beregnes ofte ved at gange middelfolketal med periodens
længde. I den særlige situation, hvor perioden er 1 år langt, altså når
\(t_2-t_1=1\) år, har middelfolketallet (antal) og risikotiden (personår)
den samme værdi men forskelige enheder. Vi vil senere bruge \(V_x\) som
vægte i definitionen af aldersstandardiserede rater (afsnit
ref:Aldersstandardisering).

*** Eksempel
:PROPERTIES:
:CUSTOM_ID: k2_personaar_4_aldersgrupper
:END:

Vi finder aldersfordelingen af risikotiden for hele den danske befolkning
i perioden mellem 1. januar 2022 og 1. januar 2023 og inddeler
den i fire aldersintervaller: \([0,25], (25,50], (50,75], (75,125]\).

#+ATTR_LATEX: :options otherkeywords={group,mutate,summarise,hent_data}, deletekeywords={dt,list,c}
#+BEGIN_SRC R  :results output :exports both  :session *R* :cache yes  
folk <- hent_data("FOLK1a", alder=0:125), tid=c("2022K1","2023K1")
# Risikotid= 1* Middelfolketal metode 2
folk <- folk %>% group_by(alder) %>%
                            summarise(Risikotid=1*mean(INDHOLD))
# Aldersintervaller
folk <- mutate(folk,Aldersinterval=cut(alder,
                                           breaks=c(0,25,50,75,125),
                                           include.lowest = TRUE))
# antal personår i de 4 aldersintervaller
af <- folk %>% group_by(Aldersinterval) %>%
                                 summarise(Personår=sum(Risikotid))
# aldersfordeling i procent 
af <- af %>% mutate(Procent=100*Personår/sum(Personår))
af
#+END_SRC

#+RESULTS[(2023-12-27 12:59:07) c65ea9c84aad67ede14f61db770054574440687f]:
: # A tibble: 4 × 3
:   Aldersinterval Personår Procent
:   <fct>             <dbl>   <dbl>
: 1 [0,25]         1747687    29.6 
: 2 (25,50]        1867838.   31.6 
: 3 (50,75]        1773568    30.0 
: 4 (75,125]        513944.    8.71

** Lexisdiagram

Et Lexisdiagram visualiserer sammenhængen mellem kalendertid (vertikal)
og alder (horisontal). Hver person er repræsenteret af sin
livslinje (Figur ref:fig:k2-lexis-liv). I en /lukket befolkning/ (hvor ind- og udvandring ikke
forekommer) starter alle livslinjer på fødselsdagen, hvor personen er 0
år gamle og ender i dødsdatoen - den alder personen har livet til. I en
åben befolkning, starter livslinjer for immigranter den dag de
immigrerer og slutter for emigranter den dag, de emigrerer.

#+BEGIN_SRC R :results file graphics :file ./kapitel2/k2-lexis-liv.pdf :exports none :session *R* :cache yes :width 8 :height 5
library(LexisPlotR)
# Plot a Lexis grid from year 1997 to year 2023, representing the ages from 0 to 25
l <- lexis_grid(year_start = 2015, year_end = 2023, age_start = 0, age_end = 5,lwd=0.01)
l <- l+theme(text = element_text(face="bold",size=13))
l <- l+xlab("Kalendertid (år)")+ylab("Alder (år)")
l <- lexis_lifeline(l,birth=as.Date("2015-04-08"),lwd=2,exit=as.Date("2023-12-31"),colour="#0072B2")
l <- lexis_lifeline(l,birth=as.Date("2015-09-29"),lwd=2,exit=as.Date("2019-10-15"),colour="#009E73")
l <- lexis_lifeline(l,birth=as.Date("2017-05-17"),lwd=2,exit=as.Date("2019-12-03"),colour="#56B4E9")
l <- lexis_lifeline(l,birth=as.Date("2018-06-08"),entry=as.Date("2020-08-08"),lwd=2,exit=as.Date("2021-10-10"),colour= "#E69F00")
l <- lexis_lifeline(l,birth=as.Date("2020-02-02"),entry=as.Date("2021-06-19"),lwd=2,exit=as.Date("2023-05-10"),colour= "#CC79A7")
l+ggtitle("Lexis diagram: livslinjer")
#+END_SRC

#+RESULTS[(2023-12-27 12:58:14) f2ebbce19b3ef8274ae9a84988527a90453576b1]:
[[file:./kapitel2/k2-lexis-liv.pdf]]

#+name: fig:k2-lexis-liv
#+ATTR_LATEX: :width 1.0\textwidth
#+CAPTION: Figuren viser 5 personers livslinjer i (den nederste del af) et Lexis diagram. Livslinjer der ikke starter i alder '0'
#+CAPTION: representerer immigranter og livslinjer som stopper representerer enten dødsfald eller emigranter.
[[file:./k2-lexis-liv.pdf]]

Figur ref:fig:k2-lexis-liv viser 5 personers livslinjer fra en åben
befolkning. Den mørkeblå linje repræsenterer en person, som bliver født
i foråret 2015 og forbliver i befolkningen indtil foråret 2020 hvor
Lexisdiagrammet slutter. Lexisdiagrammet kan også bruges til at
forklare forskellen mellem kohorteprincippet (man følger en
fødselskohorte i en relativt lang periode) og kalenderårsprincippet
(man studerer en befolkning i en kort periode). Figur ref:fig:k2-lexis
viser et Lexisdiagram med skematisk forklaring til hvordan man kan
studere en befolkning i en kort kalenderperiode, følge en aldersgruppe
igennem kalendertid, og en fødselskohorte igennem både kalendertid og
alder.

#+BEGIN_SRC R :results file graphics :file ./kapitel2/k2-lexis.pdf :exports none :session *R* :cache yes :width 8 :height 5
library(LexisPlotR)
# Plot a Lexis grid from year 1997 to year 2023, representing the ages from 0 to 25
l <- lexis_grid(year_start = 2015, year_end = 2023, age_start = 0, age_end = 5,lwd=0.1)
l <- l+theme(text = element_text(face="bold",size=13))
l <- l+xlab("Kalendertid (år)")+ylab("Alder (år)")
l <- lexis_age(l,age=3,fill="#E69F00",alpha=0.3)
l <- lexis_year(l,year=2021,fill="#009E73",alpha=0.3)
l <- lexis_year(l,year=2020,fill="#009E73",alpha=0.3)
lexis_cohort(l,cohort=2016,fill="#56B4E9",alpha=0.3)+ggtitle("Lexis diagram: skema")
#+END_SRC

#+RESULTS[(2023-11-17 09:12:27) 696dd5a5832d83077ea7d1d000cb67124340c0cb]:
[[file:./kapitel2/k2-lexis.pdf]]

#+name: fig:k2-lexis
#+ATTR_LATEX: :width 1.0\textwidth
#+CAPTION: I et Lexis diagram kan man følge en aldersgruppe igennem kalendertid (gul) eller
#+CAPTION: en fødselskohorte igennem både alder og kalendertid (blå). Det grønne område viser 
#+CAPTION: en kort kalenderperiode.
[[file:./k2-lexis.pdf]]

* Aldersspecifikke mortalitetsrater

Vi ser på en befolkning i en kalenderperiode \([t_1,t_2]\) og inddeler
den i  \(\{x=1,\dots,m\}\) aldersgrupper. Vi betegner med
\(D_x[t_1,t_2]\) antal dødsfald i perioden hvor personens alder ved
dødsdatoen falder i aldersgruppe \(x\).  For at lette notationsbyrden
dropper vi kalenderperioden og forkorter \(D_x[t_1,t_2]\) til \(D_x\)
og ligeledes skriver vi \(R_x\) for den aldersspecifikke risikotid
\(R_x[t_1,t_2]\) i samme periode. De aldersspecifikke mortalitetsrater
er defineret som kvotienten mellem antal dødsfald og risikotid.
#+begin_export latex
\begin{equation}\label{eq:aldersspecifikke_mortalitetsrate}
\text{Aldersspecifikke mortalitetsrate:}\qquad M_x=\frac{D_x}{R_x}, \qquad x=1,...,m. 
\end{equation}
#+end_export

Bemærk at den aldersspecifikke mortalitetsrate \(M_x\) afhænger også
kalenderperioden, så vi bruger også notationen \(M_x[t_1,t_2]\) for at angive kalenderperioden.

*** Eksempel

Vi finder antal dødsfald for hele den danske befolkning i perioden
mellem 1. januar 2022 og 1. januar 2023 og beregner det
samlede antal døde i samme 4 aldersintervaller (\([0,25], (25,50],
(50,75], (75,125]\)) som vi har brugt i eksemlet i afsnit
ref:k2_personaar_4_aldersgrupper. Vi finder tal i statistikbankens DOD
og bemærker at det sidste aldersinterval hedder ``99 år og derover''.

#+ATTR_LATEX: :options otherkeywords={hent_data,summarise,mutate}, deletekeywords={list,de,by,c}
#+BEGIN_SRC R :results value verbatim :exports both  :session *R* :cache yes  
dd <- get_data("dod",alder=agevals,tid="2022")
# Aldersintervaller
dd <- mutate(dd,Aldersinterval=cut(alder,
                                   breaks=c(0,25,50,75,125),
                                   include.lowest = TRUE))
# antal døde i de 4 aldersintervaller
group_dd <-dd %>% group_by(Aldersinterval) %>%
                             summarise(antal_døde=sum(INDHOLD))
group_dd
#+END_SRC

#+RESULTS[(2023-12-27 12:44:30) 7b80dd92ef5fc0219d959e80b48efec1cde2f8e2]:
: # A tibble: 4 × 2
:   Aldersinterval antal_døde
:   <fct>               <dbl>
: 1 [0,25]                461
: 2 (25,50]              1621
: 3 (50,75]             18194
: 4 (75,125]            39159


For at beregne de aldersspecifikke mortalitetsrater skal vi samle
personår (afnit ref:k2_personaar_4_aldersgrupper) og antal døde i
aldersgrupper. Det gør vi med **left\under{}join** i R:

#+ATTR_LATEX: :options otherkeywords={mutate,left_join}, deletekeywords={dt,list,group,by,de}
#+BEGIN_SRC R  :results output :exports both  :session *R* :cache yes
x <- left_join(af,group_dd,by="Aldersinterval")
# aldersspecifikke mortalitetsrater
x <- x %>% mutate(mrate=1000*antal_døde/Personår)
x
#+END_SRC

#+RESULTS[(2023-12-27 13:00:25) 02fbd7ca47f27f9351649b7410377eb7ebbc90e4]:
: # A tibble: 4 × 5
:   Aldersinterval Personår Procent antal_døde  mrate
:   <fct>             <dbl>   <dbl>      <dbl>  <dbl>
: 1 [0,25]         1747687    29.6         461  0.264
: 2 (25,50]        1867838.   31.6        1621  0.868
: 3 (50,75]        1773568    30.0       18194 10.3  
: 4 (75,125]        513944.    8.71      39159 76.2


** Sammenligning af aldersspecifikke mortalitetsrater

For at sammenligne mortalitet i to befolkninger (studiebefolkning
\(A\) mod studiebefolkning \(B)\) kan man sammenligne de
aldersspecifikke mortalitetsrater mellem de to befolkninger (\(M_x^A
\text{ versus } M_x^B\)). Det giver lige så mange resultater, som der
er aldersintervaller, altså et resultat for hver aldersgruppe. Figur
ref:fig:k2-ammk-2011 viser raterne for 100 aldersgrupper hvor den
sidste samler personer som er 99 år og derover. Hvis der er blot 4 aldersgrupper kan
man på en overskulig måde vise resultater i en tabel. Men med mange
aldersgrupper er det nemmere at se forskellen i en figur, som viser de
aldersspecifikke mortalitetsrater af de to befolkninger ved siden af
hinanden.

*** Eksempel

Vi beregner aldersspecifikke mortalitetsrater for mænd og kvinder i
2011 og visualiserer forskellen.

#+ATTR_LATEX: :options otherkeywords={hent_data,mutate,summarise,pull,ggplot}, deletekeywords={c,&,title,legend,de,scale,by,axis,plot,margin,t,text,rect,list,factor}
#+BEGIN_SRC R :results file graphics :file ./kapitel2/k2-aldersspecifikke-mortalitet-maend-kvinder-2011.pdf :exports code :session *R* :cache yes :width 8 :height 5
# hent folketal fra 2011
folk <- hent_data("FOLK1a",alder=0:125,køn=c(2,1),tid="2011K3")
# ændre variable navn
folk <- folk %>% rename("risikotid"="INDHOLD")
# samle antal personer over 99 (fordi register DOD gør det samme)
folk <- samle_alder(folk,variable = "risikotid",value = "99plus",by = "køn")
# hent dødstal fra 2011
dd <- hent_data(register="dod",alder=0:99,køn=c("K","M"),tid="2011")
# ændre variable navn
dd <- dd %>% rename("antal_døde"="INDHOLD")
# join folketal og antal dødsfald
x <- left_join(folk,dd,by=c("alder","KØN"))
# aldersspecifikke mortalitetsrater
x <- x %>% group_by(KØN) %>% mutate(mrate=1000*antal_døde/risikotid) 
# grafik
g <- ggplot(x,aes(x=alder,y=mrate,color= KØN))+geom_line()+geom_point()
g <- g+theme_economist()+scale_colour_wsj("colors6") +theme(legend.title=element_blank())
g <- g+ylab("Mortalitetsrate per 1000 personår")+xlab("Alder (år)")+ggtitle("Danmark 2011")
g <- g + theme(axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)))
g <- g + theme(axis.title.x = element_text(margin = margin(t = 20, r = 0, b = 0, l = 0)))
g <- g + theme(plot.background = element_rect(fill = "gray88", colour = NA))
g <- g+theme(legend.title=element_blank())+theme(legend.position="bottom")
g
#+END_SRC

#+RESULTS[(2024-02-16 14:10:49) 0f8a83d01c7e3071e73356962a3c2df8b63159e7]:
[[file:./kapitel2/k2-aldersspecifikke-mortalitet-maend-kvinder-2011.pdf]]

#+name: fig:k2-ammk-2011
#+ATTR_LATEX: :width 1.0\textwidth
#+CAPTION: Aldersspecifikke mortalitetsrater for hele den danske befolkning i 2011. Vi ser at
#+CAPTION: dødeligheden var højere for mænd i alle aldre undtagen bland personer der er mindst 99 år gamle.
[[file:./k2-aldersspecifikke-mortalitet-maend-kvinder-2011.pdf]]

* Aldersstandardisering
:PROPERTIES:
:CUSTOM_ID: Aldersstandardisering
:END:

Formålet med aldersstandardisering er at sammenligne mortalitetsrater
(og andre rater) mellem to eller flere befolkninger, som har
forskellige aldersfordelinger. Den overordnede idé er at udskifte den
rigtige aldersfordeling med en anden aldersfordeling, og at beregne
mortalitetsraten som den ville have været, hvis befolkningen havde
haft den anden aldersfordeling. På den måde kan man sammenligne
dødelighed mellem to eller flere befolkninger uanset
aldersfordeling. Her er det vigtigt, at man vælger den samme
aldersfordeling for alle befolkninger, som skal sammenlignes, men det er
typisk ikke så vigtigt hvilken aldersfordeling man vælger. For
eksempel kan vi spørge hvor meget højere, mortalitetsraten er blandt
danske mænd sammenlignet med danske kvinder, hvis aldersfordelingen
havde været den samme for mænd og kvinder. Vi mangler kun at
specificere den aldersfordeling, som de standardiserede rater skal
have til fælles. Her er der umiddelbart flere forskellige muligheder:
aldersfordeling blandt mænd, aldersfordeling blandt kvinder,
aldersfordeling blandt alle danskere uanset køn eller en helt anden
aldersfordeling.

Vi beskriver to standardiseringsformer, /direkte standardisering/
(afsnit ref:direkte_standardisering) og /indirekte standardisering/
(afsnit ref:indirekte_standardisering). Vi starter med en matematisk
forklaring af resultatet fra afsnit ref:samesumma (afsnit
ref:k2-kitagawa) og slutter med en sammenligning af direkte
og indirekte standardisering.

** Kitagawas dekomposition
:PROPERTIES:
:CUSTOM_ID: k2-kitagawa
:END:

For en given inddeling af en befolkning i aldersgrupper i en periode
\([t_1,t_2]\) er dens summariske mortalitetsrate et vægtet gennemsnit
af de aldersspecifikke mortalitetsrater. For at indse dette, skal vi
bruge aldersfordelingen af risikotid som vi har indført i afsnit
ref:risikotid_aldersgrupper. For aldersgruppe \(x\) er andelen af
risikotid givet som 
#+begin_export latex
\begin{align}\label{eq:risikotid_vaegte}
V_x &= \frac{R_x}{R}
\intertext{hvor \(R\) betegner befolkningens totale risikotid i perioden, lige som i formel \eqref{eq:sum_risikotid}. Vi omskriver formlen for den aldersspecifikke
mortalitetsrate \eqref{eq:aldersspecifikke_mortalitetsrate} sådan at antal dødsfald i aldersgruppen står isoleret:}
 D_x &= M_x R_x.\label{eq:D_lige_MR}
\end{align}
#+end_export

Vi betegner fortsat \(M\) som befolkningens summariske mortalitetsrate
og \(D\) som antal dødsfald i hele befolkningen i perioden. Det følgende regnestykke viser
at \(M\) er et vægtet gennemsnit af \(M_x\) hvor vægtene er
aldersfordelingen af risikotid:
#+begin_export latex
\begin{equation}\label{vgennemsnit}\begin{split}
M & = \frac{D}{R} \\& = \frac{D_1+D_2+...+D_m}{R} \\
&=
\frac{M_1R_1+M_2R_2+...+M_mR_m}{R}\\
& = M_1\frac{R_1}{R}+M_2\frac{R_2}{R}+...+M_m\frac{R_m}{R},\\
& =M_1V_1+M_2V_2+...+M_mV_m\\ &=\sum_{x=1}^m M_x V_x.
\end{split}
\end{equation}
#+end_export

I afsnit ref:samesumma har vi diskuteret at forskellen mellem kvinders
og mænds summariske mortalitetsrater skyldes ikke kun kønsforskellen
af mortalitetsrater men også kønsforskellen af
aldersfordelinger. Kitagawas dekomposition viser dette klart og mere
generelt som matematisk formel. I stedet for det specifikke valg,
kvinder og mænd, skal vi skrive formlen i abstrakt form for en
/studiebefolkning \(A\)/ og en /studiebefolkning \(B\)/. Vi kan anvende formel
eqref:vgennemsnit og skrive de to summariske mortalitetsrater som
#+begin_export latex
\begin{equation*}
M^A=\sum_{x=1}^m M^A_x V^A_x \text{ og }M^B=\sum_{x=1}^m M^B_x V^B_x
\end{equation*}
#+end_export
hvor \(V^A_x\) og \(V^B_x\) er aldersfordelinger af risikotid fra
henholdsvis studiebefolkning \(A\) og studiebefolkning \(B\).  Kitagawas dekomposition
beskriver forskellen mellem to summariske mortalitetsrater:
#+begin_export latex
\begin{equation}\label{eq:kitagawa}
\begin{split}
 M^A- M^B&=\sum_{x=1}^m M_x^A V_x^A - \sum_{x=1}^m M_x^B V_x^B\\
 &=\sum_{x=1}^m \left(M_x^A V_x^A - M_x^B V_x^B\right)\\
% &=\sum_{x=1}^m \left[M_x^A V_x^A - M_x^B V_x^B \color{red}+M_x^A V_x^B -M_x^A V_x^B + M_x^B V_x^A -M_x^B V_x^A\color{black}\right]\\
% &=\sum_{x=1}^m \left[(M_x^A V_x^A - \color{red}M_x^B V_x^A) - (M_x^A V_x^B - \color{black}M_x^B V_x^B) \\
% &\quad\qquad +\color{red}(M_x^B V_x^A  - M_x^A V_x^B) + \color{blue} (M_x^B V_x^A  - M_x^A V_x^B)\right]\\
 &=\underbrace{\sum_{x=1}^m(M_x^A-M_x^B)\frac{V_x^A+V_x^B}{2}}_{\text{Komponent 1}} +
\underbrace{\sum_{x=1}^m(V_x^A-V_x^B)\frac{M_x^A+M_x^B}{2}}_{\text{Komponent 2}} \\
\end{split}
\end{equation}
#+end_export
Her beskriver komponent 1 forskellen mellem de aldersspecifikke
mortalitetsrater vægtet med de gennemsnitlige andele af risikotid og
komponent 2 forskellen mellem aldersfordelingerne vægtet med de
gennemsnitlige mortalitetsrater. Det kræver lidt algebra hvis man vil indse hvorfor Kitagawas komposition holder: For 
hvert aldersinterval \(x\) gælder:

#+begin_export latex
\begin{equation}\label{eq:kitagawas_forklaring}
\begin{split}
(M_x^A V_x^A - M_x^B V_x^B) &= \frac{(M_x^A V_x^A - M_x^B V_x^B)+(M_x^A V_x^A - M_x^B V_x^B)}{2}\\
&=\frac{M_x^A V_x^A}{2} - \frac{M_x^B V_x^B}{2}+ \frac{M_x^A V_x^A}{2} - \frac{M_x^B V_x^B}{2}\\
&=\frac{M_x^A V_x^A}{2} - \frac{M_x^B V_x^B}{2}+ \frac{M_x^A V_x^A}{2} - \frac{M_x^B V_x^B}{2}\\
&\quad+ \color{red}\left(\frac{M_x^A V_x^B}{2} - \frac{M_x^A V_x^B}{2}\right)\color{black}+ \color{blue}\left(\frac{M_x^B V_x^A}{2} - \frac{M_x^B V_x^A}{2}\right)\\
&= \frac{M_x^A V_x^A}{2} + \frac{M_x^A V_x^B}{2} - \frac{M_x^B V_x^A}{2} - \frac{M_x^B V_x^B}{2} \\
&\quad + \frac{M_x^A V_x^A}{2} + \frac{M_x^B V_x^A}{2} - \frac{M_x^A V_x^B}{2} - \frac{M_x^B V_x^B}{2}\\
&=(M_x^A-M_x^B)\frac{V_x^A+V_x^B}{2}+(V_x^A-V_x^B)\frac{M_x^A+M_x^B}{2}.
\end{split}
\end{equation}
#+end_export
Da ligning eqref:eq:kitagawas_forklaring holder for hver aldersgruppe
\(x\), holder den også for summen over alle aldersgrupper, og det
giver formel eqref:eq:kitagawa.

** Direkte standardisering
:PROPERTIES:
:CUSTOM_ID: direkte_standardisering
:END:

Formålet med den såkaldte direkte standardisering er at sammenligne
mortalitetsrater mellem to befolkninger uanset forskelle i
aldersfordeling. Direkte standardisering er en metode, som
sammenfatter forskellen af mortalitetsrater med et tal der benævnes
/standardiserede rate ratio/. For at definere direkte standardisering
skal vi bruge to studiebefolkninger (A mod B) og en
standardbefolkning (S). Ideen er at se om studiebefolkning A har
højere mortalitet end studiebefolkning B hvis (hypotetisk) begge havde
sammen aldersfordeling som standardbefolkning S. Vi fortolker den
direkte standardiserede mortalitetsrate
#+begin_export latex
\begin{equation}\label{eq:direkte_standard_mort}
\tilde M^A_{S} =  \sum_{x=1}^m M_x^A V_x^S,
\end{equation}
#+end_export
som den mortalitetsrate vi ville have set i studiebefolkning \(A\),
hvis aldersfordeling af risikotid havde været den samme som i
standardbefolkning \(S\).  Ideen er at vi nu kan direkte sammenligne
de standardiserede mortalitetsrater fra studiebefolkninger \(A\) og
\(B\) hvis standardbefolkningen er den samme. Den hyppigste form der 
afrapporterer denne sammenligning mellem to standardiserede
mortalitetsrater er det /standardiserede rate ratio/:
#+begin_export latex
\begin{equation}\label{eq:SRR}
 \operatorname{SRR}(A,B,S) = \frac{\sum_{x=1}^m M_x^A V_x^S}{\sum_{x=1}^m M_x^B V_x^S}.
\end{equation}
#+end_export

*** Eksempel

For at illustrere idéen med at bruge den direkte standardisering fortsætter vi med 
eksemplet fra afsnit ref:k2-summariske-rater-2011, som viste at mænd
havde en lavere summarisk mortalitetsrate end kvinder i 2011. Vi
anvender direkte standardisering hvor vi bruger alle danske kvinder i
2011 som studiebefolkning \(A\), alle danske mænd i 2011 som
studiebefolkning \(B\), og vælger alle dansker i 2011 (uanset køn) som
standardbefolkning \(S\).

#+ATTR_LATEX: :options otherkeywords={hent_data,rename,intervAlder,left_join,mutate,select,tibble,filter}, deletekeywords={c,D,R,by,sum}
#+BEGIN_SRC R  :results output   :exports both  :session *R* :cache yes  
# Fordeling af risikotid i aldersintervaller
folk <- hent_data("FOLK1a","alder"=0:125,tid="2011K3",
                  køn = c(1,2,"TOT"))
af <- rename(af,R = INDHOLD)
af <- intervAlder(folk,breaks=c(0,25,50,75,125),by="KØN",vars="R")
# Antal døde i aldersintervaller
D <- hent_data("DOD","alder"="all_no_total",tid="2011",køn=c("M","K"))
dd <- rename(dd,D = INDHOLD)
dd <- intervAlder(D,breaks=c(0,25,50,75,125),by="KØN",vars="DD")
# Aldersspecifikke mortalitetsrater
# Kvinder
A <- left_join(filter(af,KØN == "Kvinder"),
               filter(dd, KØN == "Kvinder"),
               by = c("KØN","aldersinterval"))
A <- mutate(A,M = 1000*D/R)
A <- select(A,aldersinterval,M)
# Mænd
B <- left_join(filter(af,KØN == "Mænd"),
               filter(dd, KØN == "Mænd"),
               by = c("KØN","aldersinterval"))
B <- mutate(B,M = 1000*D/R)
B <- select(B,aldersinterval,M)
# Aldersfordeling i standardbefolkning 
S <- select(filter(af,KØN == "I alt"),!KØN)
S <- mutate(S,V=(R/sum(R)))
# Join
A <- left_join(A,S,by = "aldersinterval")
B <- left_join(B,S,by = "aldersinterval")
# Direkte standardisering
tibble("srate_kvinder" = pull(summarise(A,sum(M * V))),
       "srate_maend" = pull(summarise(B,sum(M * V))))
#+END_SRC

#+RESULTS[(2024-02-16 08:58:08) f18da991b72291a12fca20603b40ca1065018c84]:
: # A tibble: 1 × 2
:   srate_kvinder srate_maend
:           <dbl>       <dbl>
: 1          8.35        10.7

Resultatet fortolkes på følgende måde: Den standardiserede
mortalitetsrate i Danmark i 2011 var 8,4 døde per 1000 personår for
kvinder og 10,7 døde per 1000 personår for mænd, hvis
aldersfordelingen havde været den samme blandt alle dansker
i 2011. Dette bekræfter, at grunden til at den summariske
mortalitetsrate var højere for mænd end for kvinder i 2011, var
forskelle i aldersfordeling.

** Indirekte standardisering
:PROPERTIES:
:CUSTOM_ID: indirekte_standardisering
:END:

Formålet med den såkaldte indirekte standardisering er at sammenligne
mortalitetsrater i studiebefolkning \(A\) med mortalitetsrater i en
standardbefolkning \(S\). Konkret sammenligner man det totale antal
dødsfald i studiebefolkning \(A\) med det forventede antal døde i
studiebefolkning \(A\) hvis (hypotetisk) de aldersspecifikke
mortalitetsrater havde de samme som i standardbefolkning \(S\). Er
de forventede antal dødsfald højere kan man konkludere, at den
samlede dødelighed (det vil sige de aldersspecifikke mortalitetsrater
samlet set) har været højere i standardbefolkningen end i
studiebefolkning \(A\).

Beregningen af indirekte standardisering kræver kendskab til de
aldersspecifikke mortalitetsrater i standardbefolkning \(S\), de
aldersspecifikke risikotider i studiebefolkning \(A\) og det totale
antal dødsfald i studiebefolkning \(A\). For \(x=1,\dots,m\)
aldersgrupper er det totale antal dødsfald i studiebefolkning \(A\)
givet ved
#+begin_export latex
\begin{equation*}
D^A = D^A_1 + \cdots + D^A_{m} = \sum_{x=1}^m D_x^A= \sum_{x=1}^m M_x^A R_x^A.
\end{equation*}
#+end_export
Her har vi brugt formel eqref:eq:D_lige_MR. Relativt til den totale
risikotid \(R^A\) er det forventede antal døde hvis dødeligheden havde
været den samme i standardbefolkning \(S\) givet ved
#+begin_export latex
\begin{equation*}
\sum_{x=1}^m M_x^S V_x^A = \sum_{x=1}^m M_x^S \frac{R_x^A}{R^A} = \frac{1}{R^A} \sum_{x=1}^m M_x^S R_x^A.
\end{equation*}
#+end_export

En sammenligning af mortalitetsrater mellem studiebefolkning \(A\) og
standardbefolkning \(S\) er det såkaldte /standardiserede mortalitetsrateratio/:
#+begin_export latex
\begin{equation}\label{eq:SMR}
\begin{split}
 \operatorname{SMR(A,S)} &=\frac{\sum_{x=1}^m M_x^A V_x^A}{\sum_{x=1}^m M_x^S V_x^A}\\
 &=\frac{\sum_{x=1}^m M_x^A R_x^A}{\sum_{x=1}^m M_x^S R_x^A}\\
&=\frac{\sum_{x=1}^m D_x^A}{\sum_{x=1}^m M_x^S R_x^A}\\ 
&=\frac{\text{Observeret antal døde}}{\text{Forventet antal døde}}
\end{split}
\end{equation}
#+end_export
Den indirekte standardiserede mortalitetsrate i befolkning \(A\) er
givet ved
#+begin_export latex
\begin{equation}\label{eq:indirekt_std_rate}
{\bar{M}}^A_{S} = \operatorname{SMR(A,S)}\cdot M^S = \frac{\sum_{x=1}^m M_x^A V_x^A}{\sum_{x=1}^m M_x^S V_x^A} \sum_{x = 1}^m M_x^S V_x^S.
\end{equation}
#+end_export

** Direkte versus indirekte standardisering

Typisk ønsker man at sammenligne flere studiebefolkninger, og man vil
derfor beregne en standardiseret rate for hver studiebefolkning, idet
den samme standardbefolkning bruges i alle beregninger. Dødeligheden i
de forskellige befolkninger kan så sammenlignes ved at sammenligne de
standardiserede rater. Direkte standardisering kræver kendskab til
aldersfordelingen af risikotiden i standardbefolkningen. Kender man ikke
aldersfordelingen fra standardbefolkningen kan man ikke anvende direkte
standardisering og dermed ikke beregne SRR. Hvis man tilgengæld kender
de aldersspecifikke mortalitetsrater i standardbefolkningen kan man
beregne SMR. Man kan dog umiddelbart ikke direkte sammenligne SMR for
to studiebefolkninger \(A\) og \(B\), fordi \(\operatorname{SMR}(A,S)\)
afhænger aldersfordeling af studiebefolkning \(A\) og
\(\operatorname{SMR}(B,S)\) afhænger aldersfordeling af
studiebefolkning \(B\). Dette problem har direkte standardisering
\(\operatorname{SRR}(A,B,S)\) ikke. Derfor vil man bruge direkte
standardisering i en situation hvor man kan vælge mellem direkte og
indirekte standardisering.

For at foretage en direkte eller indirekte standardisering skal man
først have valgt en standardbefolkning. Valget vil typisk afspejle
problemstillingen. Hvis vi skal sammenligne dødeligheden i forskellige
lande i Europa, vil det være naturligt at vælge hele Europa som
standardbefolkning. Hvis vi vil sammenligne dødeligheden i
forskellige erhvervsgrupper, vil det være naturligt at bruge alle
erhvervsaktive som standardbefolkning. Det kan også være rimeligt at
vælge en af studiebefolkningerne eller de to
studiebefolkninger sat sammen som standardbefolkning.  I et enkelt tilfælde vil
en direkte standardisering og en indirekte standardisering altid give
det samme resultat: Hvis man har man to studiebefolkninger vil en
sammenligning baseret på en direkte standardisering med den ene
befolkning som standard være identisk med en sammenligning baseret på
en indirekte standardisering med den anden befolkning som standard.

# Det ses når vi bruger aldersfordeling fra studiebefolkning \(A\) som
# standardbefolkning i formlen for SRR:

* Opgaver :noexport:

** Aldersfordeling

- Beregn aldersfordeling i Danmark i 2010 i landdistrikterne og hovedstadsområdet og diskuter forskelle mellem 2010 og 2023.



** Header :noexport:

#+TITLE: Mortalitet og standardisering
#+AUTHOR: Anna-Vera Jørring Pallesen, Johan Sebastian Ohlendorff, Laust Hvas Mortensen and Thomas Alexander Gerds
#+DATE: 
#+LaTeX_CLASS: danish-article
#+OPTIONS: toc:nil
#+LaTeX_HEADER:\usepackage{authblk}
#+LaTeX_HEADER:\usepackage{natbib}
#+LaTeX_HEADER:\usepackage{listings}
#+LaTeX_HEADER:\usepackage{color}
#+LaTeX_HEADER:\usepackage[usenames,dvipsnames]{xcolor}
#+LaTeX_HEADER:\usepackage[utf8]{inputenc}
#+LaTeX_HEADER:\usepackage{hyperref}
#+LaTeX_HEADER:\usepackage{amssymb}
#+LaTeX_HEADER:\usepackage{latexsym}
#+LaTeX_HEADER:\usepackage[danish]{babel}
#+LaTeX_HEADER:\hyphenation{studie-be-folk-ning}
#+LaTeX_HEADER:\renewcommand\theequation{K2.\arabic{equation}}
#+OPTIONS:   H:3  num:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:t todo:t pri:nil tags:not-in-toc author:t
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://publicifsv.sund.ku.dk/~tag/styles/all-purpose.css" />
#+LATEX_HEADER: \RequirePackage{tcolorbox}
# #+LaTeX_HEADER:\usepackage[table,usenames,dvipsnames]{xcolor}
#+LaTeX_HEADER:\definecolor{lightGray}{gray}{0.98}
#+LaTeX_HEADER:\definecolor{medioGray}{gray}{0.83}
#+LATEX_HEADER:\definecolor{mygray}{rgb}{.95, 0.95, 0.95}
#+LATEX_HEADER:\newcommand{\mybox}[1]{\vspace{.5em}\begin{tcolorbox}[boxrule=0pt,colback=mygray] #1 \end{tcolorbox}}
#+superman-export-target: pdf
